### ISSUE TITLE
Can't get Bcache block device info for /dev/bcache0: Failed to get 'cache_size' for 'bcache0' Bcache device

### ISSUE THREAD

**Issue by maxtorm12138** [storaged-project/udisks#1020]
Can't get Bcache block device info for /dev/bcache0: Failed to get 'cache_size' for 'bcache0' Bcache device

CODE_FILE
    udiskslinuxblockbcache.c:236
CODE_FUNC
    udisks_linux_block_bcache_update
GLIB_DOMAIN
    udisks
PRIORITY
    4
THREAD_ID
    31619
_BOOT_ID
    8adad1e18ad34480b4192ceb6fe89308
_CAP_EFFECTIVE
    1ffffffffff
_CMDLINE
    /usr/libexec/udisks2/udisksd
_COMM
    udisksd
_EXE
    /usr/libexec/udisks2/udisksd
_GID
    0
_HOSTNAME
    nas.maxtorm.org
_MACHINE_ID
    8071e68d3e404d31b0a5db82cc70d4c1
_PID
    31619
_SELINUX_CONTEXT
    system_u:system_r:devicekit_disk_t:s0
_SOURCE_REALTIME_TIMESTAMP
    1663601136388782
_SYSTEMD_CGROUP
    /system.slice/udisks2.service
_SYSTEMD_INVOCATION_ID
    ec307d3c87734f5a98522e123865365a
_SYSTEMD_SLICE
    system.slice
_SYSTEMD_UNIT
    udisks2.service
_TRANSPORT
    journal
_UID
    0
__CURSOR
    s=cdf56a04428542618928e3ec951a3c1d;i=156aa;b=8adad1e18ad34480b4192ceb6fe89308;m=b825ad4c;t=5e90952c84ada;x=901d74ca1420f65
__MONOTONIC_TIMESTAMP
    3089476940
__REALTIME_TIMESTAMP
    1663601136388826

**Comment by maxtorm12138** [comment]
system: 5.19.9-200.fc36.x86_64 fedora 36
udisk2: udisks2-2.9.4-4.fc36.x86_64

**Comment by maxtorm12138** [comment]
> 

I have a 14t hdd, i use bcache to speed up bt download and cache upload requests.

**Comment by vojtechtrefny** [comment]
Are you using UDisks to set the bcache up or is this just an error you see in logs?

**Comment by maxtorm12138** [comment]
> 

setup bcache through cli(make-bcache )， and get err logs in cockpit storage page，

**Comment by tbzatek** [comment]
The `bcache` udisks module has been removed.
