### ISSUE TITLE
Dolphin: Filesystem type ntfs3,ntfs not configured in kernel

### ISSUE THREAD

**Issue by Firestar-Reimu** [storaged-project/udisks#1039]
If ntfs-3g is not installed, and Linux 5.15 ntfs3 (the new Paragon NTFS driver) is present, Dolphin tries to mount NTFS partition, but it will say an error: Filesystem type ntfs3,ntfs not configured in kernel

like this (Enter `udisksctl mount -b /dev/sda1`):

`Error mounting /dev/sda1: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error mounting /dev/sda1 at /run/media/(user_name)/(NTFS_disk): Filesystem type ntfs3,ntfs not configured in kernel.`

The old method is this: https://bugs.kde.org/show_bug.cgi?id=445468

As a workaround, add a such option to `/etc/udisks2/mount_options.conf` in `[defaults]` section:

`ntfs_defaults=uid=$UID,gid=$GID`

but now even this method do not work.

```
Operating System: Arch Linux
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7
Kernel Version: 6.0.7-arch1-1 (64-bit)
```

**Comment by tbzatek** [comment]
Please test the current git master, there were lots of changes regarding ntfs3. Don't forget to revert your workarounds.

**Comment by Firestar-Reimu** [comment]
https://archlinux.org/packages/extra/x86_64/udisks2/

udisks2 on archlinux is still the version one year before, so you mean it may be not compatible with linux kernel 6.0.7?

**Comment by tbzatek** [comment]
There were multiple ntfs3 compatibility issues and we need to know how the current git master works on various distributions.

**Comment by jackghg** [comment]
doesnt work here too. Is the ntfs3 thing in the last release ? if no... please make a release!

**Comment by Firestar-Reimu** [comment]
https://github.com/Paragon-Software-Group/linux-ntfs3/commit/1d07a9dfa19914ad27bdb9ec9ac0baa2329b2ae3

NTFS3 made a commit for `windows_names` and maybe udisks should make another change

**Comment by tbzatek** [comment]
> [Paragon-Software-Group/linux-ntfs3@1d07a9d](https://github.com/Paragon-Software-Group/linux-ntfs3/commit/1d07a9dfa19914ad27bdb9ec9ac0baa2329b2ae3)
> 
> NTFS3 made a commit for `windows_names` and maybe udisks should make another change

That's certainly nice, however too late. UDisks runs against variety of kernels and need to support older releases. By adding `windows_names` by default, it will fail on kernel versions not carrying this change.

**Comment by Firestar-Reimu** [comment]
can you make a release 2.9.5 with `windows_names` support and kernel versions not carrying this change use 2.9.4?

**Comment by tbzatek** [comment]
> can you make a release 2.9.5 with `windows_names` support and kernel versions not carrying this change use 2.9.4?

No further releases are planned in the 2.9 branch. Please test the git master as suggested.

**Comment by jackghg** [comment]
any release is welcomed

**Comment by jackghg** [comment]
https://www.phoronix.com/news/NTFS3-Linux-6.2-Features

**Comment by Firestar-Reimu** [comment]
thanks @jackghg , waiting for reply from Linus Torvalds.

**Comment by Firestar-Reimu** [comment]
> Please test the current git master, there were lots of changes regarding ntfs3. Don't forget to revert your workarounds.

Is there a git/testing/nightly release?

**Comment by tbzatek** [comment]
> Is there a git/testing/nightly release?

https://github.com/storaged-project/udisks/archive/refs/heads/master.zip
Alternatively Fedora and CentOS Stream rpm packages are available as nightly builds at https://copr.fedorainfracloud.org/coprs/g/storage/udisks-daily/

**Comment by jackghg** [comment]
just make a release!

**Comment by Firestar-Reimu** [comment]
![Screenshot_20230421_162620](https://user-images.githubusercontent.com/65082432/233588059-5ee4335e-fe74-40ba-bcd9-014676576449.png)

test on linux-6.2.11 dolphin-22.12.3-1

**Comment by tbzatek** [comment]
UDisks 2.10.0 has just been released, please test and reopen in case of any issue.

**Comment by Legion345** [comment]
Downloading and installing ntfs-3g fixed my problem!

**Comment by teohhanhui** [comment]
> Downloading and installing ntfs-3g fixed my problem!

You don't want to do that. That's just going backwards. The performance is much worse.
