### ISSUE TITLE
CI badge hard to see in GitHub's night theme

### ISSUE THREAD

**Issue by rffontenelle** [storaged-project/udisks#1043]
When GitHub's [night theme](https://github.com/settings/appearance) is set, this is how the badge is shown in the README:

![CI-badge](https://user-images.githubusercontent.com/1571783/201376060-4bd20887-a07e-49a5-800b-5cf1dba8b10b.png)

**Comment by vojtechtrefny** [comment]
I added a white background for the CI status. Not ideal, but it works. The new image will be available after the next CI run.
