### ISSUE TITLE
udisks_manager_get_supported_filesystems

### ISSUE THREAD

**Issue by jonnygrant** [storaged-project/udisks#1046]
Could udisks_manager_get_supported_filesystems check for nullptr? reject such calls.
https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/issues/230

**Comment by jonnygrant** [comment]
Hi @tbzatek 

I appreciate that some may think calling with a NULL pointer is ok, can't it be in the coding standard that functions must check pointers are valid? It's in all the ISO standards for safety critical software. Really bad to not check parameters are valid.

It's the same as getting an 'int' that is expected to be between 0 and 100, but never checking it is a valid percentage, just using it, so things break when it's passed as -1 or anything above 100.

**Comment by tbzatek** [comment]
This is an auto-generated code from a D-Bus interface using `gdbus-codegen`, the bug should go there (`glib/gio`). We can't do much in this regard on UDisks side.

Many public functions typically have object guards that would print a warning, not sure why `gdbus-codegen` doesn't do this by default.

In any case, you're accessing a `GDBusProxy` that needs to reach the daemon for the value.

**Comment by jonnygrant** [comment]
Thank you for your reply @tbzatek 
Ok I've filed on https://gitlab.gnome.org/GNOME/glib/-/issues/2817

So UDisks can't check parameters are non-NULL? it doesn't really cost any performance these days, code is so optimal, CPUs so fast.

I'm not the reporter, just looking at the ticket while I filed something else...

**Comment by pwithnall** [comment]
The [bug is in gnome-disk-utility](https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/issues/230#note_1601661), this issue can be closed.
