### ISSUE TITLE
The filesystem label is not sanitized when creating a mount point

### ISSUE THREAD

**Issue by bertogg** [storaged-project/udisks#1056]
Hello,

when UDisks mounts an external drive the name of the mount point is taken from the filesystem label (if available).

The problems is that, other than removing the slash character, the rest of the label is not sanitized so its contents go directly to the directory name.

This can result in mount points consisting on a sequence of non-printable characters. Apart from being cumbersome for the end user and error-prone it also can result on bugs like this one:

* Connect a removable device after setting a label like this one `# e2label /dev/mmcblk0p1 "$(echo -e 'MY\n\rDISK')`"
* Type `# umount /media<TAB>` and note how the bash completion produces a result that is escaped and therefore does not work
* Type `# ls /media/user/<TAB>` and note how the shell is unable to complete the name of the only existing directory.
* See `/proc/mounts` and note how the line feed is escaped (as `\012`) but the carriage return is not, producing a garbled output.
* Unplug the device and note how it is not unmounted automatically, presumably because of the way [the mount info is parsed](https://github.com/storaged-project/udisks/blob/udisks-2.9.4/src/udisksmountmonitor.c#L475). Trying to access the directory results in an I/O error.

I suggest that all characters below ASCII 0x20 be removed or replaced by underscores or something like that. I would even go a bit further and do the same with printable characters such as single quotes, double quotes or backslashes, that are potentially dangerous if not used carefully by scripts or other tools.

This was all tested with UDisks 2.9.4.

**Comment by tbzatek** [comment]
Good catch!

> This was all tested with UDisks 2.9.4.

Related to this, the current git master has been ported to the libblockdev filesystem API, changing label rules and validation, generally towards slightly more permissive way, depending on filesystem type (and in some cases to a corresponding mkfs tool version).

> Unplug the device and note how it is not unmounted automatically, presumably because of the way [the mount info is parsed](https://github.com/storaged-project/udisks/blob/udisks-2.9.4/src/udisksmountmonitor.c#L475). Trying to access the directory results in an I/O error.

Ah yeah, that might be another issue.

> I suggest that all characters below ASCII 0x20 be removed or replaced by underscores or something like that. I would even go a bit further and do the same with printable characters such as single quotes, double quotes or backslashes, that are potentially dangerous if not used carefully by scripts or other tools.

Sounds good, there's a lot of escaping with D-Bus object paths already and the end user/desktop is displaying UTF-8 label usually. Doesn't really matter what name exactly does the dynamically created mountpoint carry.

**Comment by bertogg** [comment]
> Sounds good, there's a lot of escaping with D-Bus object paths already and the end user/desktop is displaying UTF-8 label usually. Doesn't really matter what name exactly does the dynamically created mountpoint carry.

Exactly, I think the only possible issue is if an application relies on the mount point never changing between UDisks versions.

It's not going to be a problem for non-printable characters, it _might_ be a problem for some printable ones (with the patch that I sent: labels with single or double quotes, or backslashes). But I think that sanitizing the mount points in those cases is more important, and apps should not make those assumptions about where a removable device is going to be mounted.

**Comment by tbzatek** [comment]
> Exactly, I think the only possible issue is if an application relies on the mount point never changing between UDisks versions.

(Dynamic) mountpoint names have never been stable as udisks appends "-1", "-2" etc. suffixes on already existing directories. So no worries about that.
