### ISSUE TITLE
Mounting a filesystem on behalf of another user

### ISSUE THREAD

**Issue by bertogg** [storaged-project/udisks#1065]
Hello,

The `UDisks2.Filesystem.Mount` method mounts a filesystem on a sub-directory of `/run/media/$USER`, where `$USER` is whoever made the D-Bus method call.

I would like to be able to mount a filesystem (as root) on behalf of another user, who may not have logged in yet and has no active seat.

Is there a way to do this, and if not, does it sound like something worth adding to the API? Ideally I think that an additional parameter to specify the user ID would be enough.

Thanks.

**Comment by tbzatek** [comment]
I'm not aware of any existing way to do this as the caller UID is taken in account:

https://github.com/storaged-project/udisks/blob/6991f77e7c51354a4146216968c17a480f9f9aee/src/udiskslinuxfilesystem.c#L1237-L1253

It might be fairly easy to override this UID by an extra argument. I can't think of any security implications, except of re-routing through a different polkit rule (or simply requiring auth always as you suggested).

**Comment by tbzatek** [comment]
> I could try to prepare a patch adding this functionality if it sounds good to you.

Sounds great, thanks for picking up this work.
