### ISSUE TITLE
Auto-mount without GUI?

### ISSUE THREAD

**Issue by danergo** [storaged-project/udisks#1085]
In a purely command-line environment (Debian Bullseye) I wish to automount SD cards based on ther label, whenever they are inserted.

I tried many ways, but I couldn't make it work. running a script from udev when "mmcblk0p1" is added is too early for udisksctl.

How am I supposed to have and sd card mounted automatically under /media/sdcardlabel, in case a system without GUI?

**Comment by tbzatek** [comment]
UDisks itself only provides hints, you need something else that takes the actual (auto)mount action. Either you can run `gvfs` within a d-bus session in your shell or use tools like `udiskie`.

**Comment by tbzatek** [comment]
Since the UDisks daemon only provides hints and any kind of automounting policy is not considered to be included, you need a client for the job.

Have a look at https://github.com/storaged-project/udisks/discussions/1078, it roughly concerns the similar idea.

**Comment by danergo** [comment]
Thank you, I'll check it.

However, I encountered another problem which I can't solve:

`$ udisksctl mount -b /dev/mmcblk0p1 --no-user-interaction
Error mounting /dev/mmcblk0p1: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorizedCanObtain: Not authorized to perform operation`

Udev rule defines a shared mount to have it under /media folder:

`$ cat /etc/udev/rules.d/82-udisks2-sd.rules
# This file contains udev rules for udisks 2.x

# ------------------------------------------------------------------------
# rules for external SD

KERNEL=="mmcblk0p*", ENV{UDISKS_FILESYSTEM_SHARED}="1"`

Even the media folder is entirely owned by `pi:pi`:

`$ ls -all /media
total 12
drwxr-xr-x 1 pi   pi   4096 Apr  4 15:18 .
drwxr-xr-x 1 root root 4096 Aug  4  2017 ..
`

And, I have added a polkit rule also to let everything for an user with "plugdev" group:

`$ cat /etc/polkit-1/rules.d/50-udiskie.rules
polkit.addRule(function(action, subject) {
  var YES = polkit.Result.YES;
  var permission = {
    // required for udisks1:
    "org.freedesktop.udisks.filesystem-mount": YES,
    "org.freedesktop.udisks.luks-unlock": YES,
    "org.freedesktop.udisks.drive-eject": YES,
    "org.freedesktop.udisks.drive-detach": YES,
    // required for udisks2:
    "org.freedesktop.udisks2.filesystem-mount": YES,
    "org.freedesktop.udisks2.encrypted-unlock": YES,
    "org.freedesktop.udisks2.eject-media": YES,
    "org.freedesktop.udisks2.power-off-drive": YES,
    // required for udisks2 if using udiskie from another seat (e.g. systemd):
    "org.freedesktop.udisks2.filesystem-mount-other-seat": YES,
    "org.freedesktop.udisks2.filesystem-unmount-others": YES,
    "org.freedesktop.udisks2.encrypted-unlock-other-seat": YES,
    "org.freedesktop.udisks2.encrypted-unlock-system": YES,
    "org.freedesktop.udisks2.eject-media-other-seat": YES,
    "org.freedesktop.udisks2.power-off-drive-other-seat": YES
  };
  if (subject.isInGroup("plugdev")) {
    return permission[action.id];
  }
});
`

And of course my user (pi) is in plugdev group:

`$ groups
pi adm dialout cdrom sudo audio dip video plugdev staff systemd-journal bluetooth netdev pulse-access`


How could I do mounting as simple user?

**Comment by tbzatek** [comment]
Closing for the time being, doesn't look like there's anything to do from our side.
