### ISSUE TITLE
udisksctl mounts an EXT4 partition as root

### ISSUE THREAD

**Issue by jradxl** [storaged-project/udisks#1086]
udisksctl mounts an EXT4 partition as root
An exFAT partition  is mounted as $USER

I was expecting udisk2 to mount any partition type as the user executing udisksctl.
Have I misunderstood?
Is there some extra config necessary to do this?
I see little point in mounting an EXT4 partition as the User cannot write to the disk without Sudo, The whole point of udisks to avoid.
Or the USB Stick have a directory pre-created with correct permissions which implies a-priori knowledge of the User using the stick.

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdd2       7,1G   24K  6,8G   1% /media/john/PARTLEXT
/dev/sdd1       7,2G  160K  7,2G   1% /media/john/PARTLFAT

$ ls -al /media/john/
total 44
drwxr-x---+ 4 root    root     4096 abr  4 18:49 .
drwxr-xr-x  4 root    root     4096 abr  4 15:37 ..
drwxr-xr-x  3 root    root     4096 abr  3 20:50 PARTLEXT
drwxr-xr-x  4 john john 32768 abr  4 18:49 PARTLFAT
```

Is there some other way of a non-root user to mount an EXT4 partition without Sudo?
Same on Ubntu Mate 23.04 Lobster and Fedora 38 Gnome

**Comment by tbzatek** [comment]
These are two separate things: mounting and actual permissions of the filesystem. You need to `chown` or `chmod` the filesystem to your needs. You've chosen a filesystem that supports unix credentials, while fat/exfat do not.

You may use the `org.freedesktop.UDisks2.Filesystem.TakeOwnership()` method or even the _ take-ownership_ option of the `org.freedesktop.UDisks2.Block.Format()` method.
