### ISSUE TITLE
Support for more NTFS3 mount options

### ISSUE THREAD

**Issue by Firestar-Reimu** [storaged-project/udisks#1117]
Related to #1039 

https://github.com/storaged-project/udisks/blob/ea007e4a8fb723f15e597bb6484ab00371bc753f/data/builtin_mount_options.conf

https://docs.kernel.org/filesystems/ntfs3.html

please support `hide_dot_files`/`windows_names`/`force`/`acl` option, thanks!

**Comment by tbzatek** [comment]
Added some more options according to the kernel 6.4-rc7 sources. Note that we can't add `force`, only safe options are considered. If the kernel driver refuses mounting for some reason, user is advised to fix the filesystem first.

Feel free to submit a pull request directly next time, it's usually a faster way. FYI, we're set for new libblockdev and udisks releases next week.

**Comment by Firestar-Reimu** [comment]
> Note that we can't add `force`, only safe options are considered.

But `force` is what I really need 😰

https://unix.stackexchange.com/questions/748468/why-is-ntfs-has-a-dirty-mark-and-why-cant-ntfs3-mount-dirty-ntfs-partitions

**Comment by tbzatek** [comment]
In that case please open a bugreport on ntfs3 directly (kernel bugzilla I presume), we can't afford having more workarounds around a broken filesystem driver.

**Comment by tbzatek** [comment]
For the record, you're free to add whatever options you want, see http://storaged.org/doc/udisks2-api/latest/mount_options.html (will be updated once 2.10.0 is released). If you need to use `force` or any other option, you can redefine that on your system.

It's just that from upstream perspective that the default options need to be as much as universal as possible and safe at the same time, potentially supporting all possible releases of that particular filesystem driver. It's up to distributors and individual consumers to redefine the defaults at their own will.

**Comment by Firestar-Reimu** [comment]
So if I add a `force` in `/etc/udisks2/mount_options.conf` will it work as `Forces the driver to mount partitions even if volume is marked dirty`?

I mean `force` or other **unsafe options** ar **supported inside** but **not configured**, or there is **no such function** in udisks?

**Comment by tbzatek** [comment]
There's nothing hardcoded anymore since the 2.9.0 release. Apart from the default config file that is builtin to ensure at least anything is defined, all mount options can be fully overriden by the `/etc/udisks2/mount_options.conf` config file. So you can add `force` into `ntfs:ntfs3_defaults` and `ntfs:ntfs3_allow` on your system and you'll be all set.

**Comment by Firestar-Reimu** [comment]
Thanks!

**Comment by Firestar-Reimu** [comment]
note that `noacsrules` has been deleted in linux 6.4

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=267a36ba30a7

**Comment by tbzatek** [comment]
> note that `noacsrules` has been deleted in linux 6.4

That's not really a problem. UDisks needs to support all kernel releases that ever carried the `ntfs3` filesystem driver. Consequently, the default set of options needs to work across this whole range.
