### ISSUE TITLE
udisks forces the optional libnvme

### ISSUE THREAD

**Issue by rezso** [storaged-project/udisks#1138]
The nvme support is optional in libblockdev, but the libnvme/libblockdev-nvme is a hard dependency in udisks.
Why?

**Comment by tbzatek** [comment]
libblockdev is a general purpose library while udisks is a package that defines some core functionality and that comes with requirements.

What's the problem?

**Comment by whitslack** [comment]
I don't have any NVMe disks in my system. Why should I need to install libnvme? It should be a compile-time option.

See [Gentoo bug 910484 — sys-fs/udisks-2.10.0 headers missing with installed sys-libs/libblockdev-3.0.1[-nvme]](https://bugs.gentoo.org/910484).

**Comment by tbzatek** [comment]
> I don't have any NVMe disks in my system.

And that's a common misconception. You don't need to have physical NVMe devices to use NVMe.

NVMe is considered a core functionality, besides ATA and SCSI/SAS. It is important to have the UDisks D-Bus NVMe interfaces present.

Anyway, as there's no technical issue involved, closing this ticket.
