### ISSUE TITLE
 udisksctl mount some partitions in read mode for the user

### ISSUE THREAD

**Issue by geole** [storaged-project/udisks#1144]
Hello
 i summarize the problem.
When an external disk contains an ext4 partition, the user is not allowed to write to this partition.
 He must do a command 'sudo chown/chmod ....... and some users are not authorized!!!
It is not normal. This situation has lasted long enough. Do what is necessary so that the write mount of a USB medium is transparent to the user. It will do a lot of people a lot of good.

I think that anyone capable of using a computer has the right to write to a USB key regardless of its formatting.
You don't have to be a genius with superpowers!

enfants@p:/media/enfants$ ls -als
total 127
 4 drwxr-x---+ 25 root root 4096 juil. 5 09:11 .
 4 drwxr-xr-x 11 root root 4096 juil. 5 09:10 ..
16 drwxr-xr-x 1 root root 0 juil. 5 08:32 btrfs
 4 drwxr-xr-x 2 enfants enfants 4096 juil. 5 09:11 exfat
 4 drwxr-xr-x 3 root root 4096 juil. 5 08:32 ext2
 4 drwxr-xr-x 3 root root 4096 juil. 5 08:32 ext3
 4 drwxr-xr-x 3 root root 4096 juil. 5 08:32 ext4
 4 drwxr-xr-x 2 root root 4096 juil. 5 08:32 f2fs
16 drwxr-xr-x 2 enfants enfants 16384 janv. 1 1970 FAT16
 1 drwxr-xr-x 2 enfants enfants 512 janv. 1 1970 FAT32
 1 drwxr-xr-x 4 enfants enfants 512 janv. 1 1970 FAT-DEUXUSB
 0 drwxr-xr-x 1 enfants enfants 3 juil. 5 09:11 hfsplus
 1 drwxr-xr-x 2 root root 4096 juil. 5 08:34 nilfs2
 4 drwxrwxrwx 1 enfants enfants 4096 juil. 5 08:34 ntfs
 0 drwxr-xr-x 4 root root 80 juil. 5 09:11 reiserfs
 0 drwxr-xr-x 2 root root 6 juil. 5 08:35 xfs

enfants@p:/media/enfants$ cd ext4

enfants@p:/media/enfants/ext4$ sudo mkdir titi
enfants n'apparaît pas dans le fichier sudoers. Cet incident sera signalé.
enfants@p:/media/enfants/ext4$

Have a good day.

**Comment by mbiebl** [comment]
That's how ext4 works, though.
If you don't want this fs behaviour, don't use that file system but something like fat or ntfs.

**Comment by mbiebl** [comment]
fwiw, I would consider it a serious bug if udisks2 automatically changed the ownership of files on ext[234] partitions.

**Comment by Firestar-Reimu** [comment]
does this related to https://github.com/storaged-project/udisks/issues/1126 ?
