### ISSUE TITLE
Error opening directory "/usr/lib/x86_64-linux-gnu/udisks2/modules": No such file or directory

### ISSUE THREAD

**Issue by grigio** [storaged-project/udisks#1157]
I get this error on Debian 12, reported also here https://github.com/cockpit-project/cockpit/issues/14497
I've LUKS+EXT4 filesystem

**Comment by grigio** [comment]
it seems fixed with
sudo mkdir -p /usr/lib/x86_64-linux-gnu/udisks2/modules

**Comment by tbzatek** [comment]
This is a correct message, udisks is asked to load a module but the modules dir doesn't exist. A module can be loaded either by a D-Bus call, by daemon commandline switch or by a config file. In either case it won't be successful and an error message is to be reported.
