### ISSUE TITLE
Partition not recognized - Storage Device SSD 8.4TB

### ISSUE THREAD

**Issue by wribeirojr** [storaged-project/udisks#1181]
In Windows 11, I can format, read and write files to the device, but in Ubuntu (22.04 and 23.04) it's not possible.

In this device, there is a 2.2TB partition (NTFS) and a 6.2TB free space area.

**Disks application shows:**
- Model: SDK_SSD (5.00)
- Serial: SDK_SSD-0:0
- Size: 8.4 TB (8,388,608,000,000 bytes)
- Partitioning: Unknown()

Partition 1 - 2.2 TB (Unknown) 
- Size: 2.2 TB (2,199,021,158,400 bytes)
- Content: Unknown
- Device: /dev/sdd1
- Partition type: Unknown

**Enabled commands on options button (all others are disabled):**
- Format partition
- Edit partition
- Resize...
- Create image
- Restore image
- Analize performance

**Trying to Format (using NTFS or FAT) results:** 
"Erros wiping device: Failed to probe device '/dev/sdd1' (udisks-error-quark, 0)"

**FSCK Command:**
  sudo fsck /dev/sdd
  fsck from util-linux 2.37.2
  e2fsck 1.46.5 (30-Dec-2021)
  ext2fs_open2: Bad magic number in super block
  fsck.ext2: Invalid superblock, trying backup blocks...
  fsck.ext2: Bad magic number in super block trying to open /dev/sdd
  The superblock could not be read or does not describe an ext2/ext3/ext4 system
  valid. Whether the device is valid and actually contains an ext2/ext3/ext4 system
  (and not swap, ufs or something else), then the super-block is corrupt and
  You can try running e2fsck with an alternative superblock:
  e2fsck -b 8193 
  or
  e2fsck -b 32768 
  Found a dos partition table in /dev/sdd

**Comment by wribeirojr** [comment]
Hey guys!

Last week I wrote this report, but I haven't received any feedback so far. 
I'm apprehensive about some answers: Is the problem I'm having really an issue? 
Did I register it to the correct project (udisks)? 
Is the report above clear enough?

Also, is there any workaround for me to use an SSD storage device? I would appreciate it if someone could guide me.
Thanks!

**Comment by tbzatek** [comment]
> **Trying to Format (using NTFS or FAT) results:**
> "Erros wiping device: Failed to probe device '/dev/sdd1' (udisks-error-quark, 0)"

Hmm, can you please provide output of `udisksctl dump` and `udevadm info /dev/sdd1`?

> **Enabled commands on options button (all others are disabled):**

That's likely a different project than udisks, there's no GUI.

> sudo fsck /dev/sdd

`/dev/sdd` is likely a partitioned device and should not carry a filesystem signature. After all, it says it there:

> Found a dos partition table in /dev/sdd

**Comment by wribeirojr** [comment]
[udisksctl_dump_Output.txt](https://github.com/storaged-project/udisks/files/12676387/udisksctl_dump_Output.txt)
[udevadm_info_Output.txt](https://github.com/storaged-project/udisks/files/12676391/udevadm_info_Output.txt)

Hi, @tbzatek , thank you for your support.
Here are the 2 outputs.

**Comment by wribeirojr** [comment]
**udevadm info /dev/sdd1**

P: /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.3/1-3.3:1.0/host3/target3:0:0/3:0:0:0/block/sdd/sdd1
N: sdd1
L: 0
S: disk/by-path/pci-0000:00:14.0-usb-0:3.3:1.0-scsi-0:0:0:0-part1
S: disk/by-id/usb-SDK_SSD-0:0-part1
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3.3/1-3.3:1.0/host3/target3:0:0/3:0:0:0/block/sdd/sdd1
E: DEVNAME=/dev/sdd1
E: DEVTYPE=partition
E: DISKSEQ=51
E: PARTN=1
E: MAJOR=8
E: MINOR=49
E: SUBSYSTEM=block
E: USEC_INITIALIZED=19561757608
E: ID_VENDOR=SDK
E: ID_VENDOR_ENC=SDK\x20\x20\x20\x20\x20
E: ID_VENDOR_ID=048d
E: ID_MODEL=SSD
E: ID_MODEL_ENC=SSD\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_MODEL_ID=1234
E: ID_REVISION=5.00
E: ID_SERIAL=SDK_SSD-0:0
E: ID_TYPE=disk
E: ID_INSTANCE=0:0
E: ID_BUS=usb
E: ID_USB_INTERFACES=:080650:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usb-storage
E: ID_PATH=pci-0000:00:14.0-usb-0:3.3:1.0-scsi-0:0:0:0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_3_1_0-scsi-0_0_0_0
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:14.0-usb-0:3.3:1.0-scsi-0:0:0:0-part1 /dev/disk/by-id/usb-SDK_SSD-0:0-part1
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

**Comment by wribeirojr** [comment]
**sudo e2fsck /dev/sdd1**

e2fsck 1.46.5 (30-Dec-2021)
ext2fs_open2: Bad magic number in superblock
e2fsck: Invalid superblock, trying blocks from backup...
superblock has an invalid journal (inode 8).
Clear<y>? Yes

*** journal has been deleted ***

The filesystem size (according to the superblock) is  536870656 blocks
The physical size of the device is 536870400 blocks
Either the superblock or the partition table is likely to be corrupt!
Abort<y>?

**Comment by wribeirojr** [comment]
testdisk utility reports:

TestDisk 7.1, Data Recovery Utility, July 2019
Christophe GRENIER <grenier@cgsecurity.org>
https://www.cgsecurity.org

Disk /dev/sdd - 8388 GB / 7812 GiB - CHS 1000000 64 32
Current partition structure:
     Partition                  Start        End    Size in sectors

Warning: number of heads/cylinder mismatches 255 (NTFS) != 64 (HD)
Warning: number of sectors per track mismatches 63 (NTFS) != 32 (HD)
 1 P HPFS - NTFS              0   8  1 262143  55 32  536870400 [Novo volume]

Warning: Bad ending sector (CHS and LBA don't match)
No partition is bootable

**Comment by tbzatek** [comment]
> Warning: number of heads/cylinder mismatches 255 (NTFS) != 64 (HD)
> Warning: number of sectors per track mismatches 63 (NTFS) != 32 (HD)
> 1 P HPFS - NTFS 0 8 1 262143 55 32 536870400 [Novo volume]
> 
> Warning: Bad ending sector (CHS and LBA don't match)

Hmm, looks like a corrupted partition or partition table. Might be interesting what `fdisk /dev/sdd` (or `cfdisk`) says about the partition table.

In case you don't need to retrieve any data from the NTFS partition, I suggest to wipe the device, reinitialize the partition table, create a new partition and a filesystem on it.

**Comment by wribeirojr** [comment]
**sudo fdisk /dev/sdd**

Changes will remain in memory only, until you decide to write them. 
Be careful before using the write command.

fdisk: cannot open /dev/sdd: Input/output error

**Comment by wribeirojr** [comment]
It gives the impression that the device is defective, but in Windows 11 this device works very well, I can write and read files on the 2GB partition.

**Comment by tbzatek** [comment]
> fdisk: cannot open /dev/sdd: Input/output error

Yes, this indicates hardware problem with the device. Perhaps `dmesg` will give you more specific details. There's not much we can do from higher-level storage layers (UDisks) unless the low-level tools (such as fdisk) work properly.

**Comment by wribeirojr** [comment]
I found a report similar to mine, from a year ago.

https://www.linux.org/threads/external-ssd-dont-work-on-linux-but-work-with-windows-please-help-me.40461/

**Comment by wribeirojr** [comment]
> > fdisk: cannot open /dev/sdd: Input/output error
> 
> Yes, this indicates hardware problem with the device. Perhaps `dmesg` will give you more specific details. There's not much we can do from higher-level storage layers (UDisks) unless the low-level tools (such as fdisk) work properly.



Good news! I got a workaround to mount the partition and access the files on my SSD device:
I noticed that although the Disks application does not recognize the partitioning or its file system, GParted can recognize the file system and also its label. This gave me hope!
So, I manually created the /media/wxyz/bkp folder and mounted the drive in it using the command line "sudo mount /dev/sdd1 /media/wxyz/bkp". To my surprise, it worked.
From this, I think we can conclude:
1) The device is not defective
2) Some component of the Linux environment is incompatible with the new high-capacity SSD models.

**Comment by wribeirojr** [comment]
I discovered that this HD SSD only accepts exFAT formatting and Ubuntu does not natively support exFAT. So, I installed exfatprogs and exfat-fuse packages. So I manually mounted it and am writing and reading files to it. So far it's working.

**Comment by tbzatek** [comment]
Interesting, thanks for the report. Still, this doesn't look like a UDisks issue. Closing for the moment.
