### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by barracuda156** [storaged-project/udisks#1184]
Is this supported / can it be supported on macOS? We have a project which works on Linux and which we want to support on macOS, and currently it uses `udisks2`.

**Comment by vojtechtrefny** [comment]
You might want to take a look at [bsdisks](https://foss.heptapod.net/bsdutils/bsdisks), FreeBSD implementation of the udisks2 API. We have some changes from the project incorporated in udisks to be able to compile only the client code to run with bsdisks (see https://github.com/storaged-project/udisks/pull/693) so something similar might be possible for MacOS.

**Comment by tbzatek** [comment]
While the daemon objects are structured to carry multiple implementations for various platforms, currently only linux is supported. It's heavy udev-dependent so any straightforward port is impossible.

I have no problem with accepting implementation for other systems to be part of UDisks, however it will have to come with a promise of maintainership of such code.

**Comment by barracuda156** [comment]
@tbzatek @vojtechtrefny Thank you for the info!
