### ISSUE TITLE
Update LUKS2 creation to use argon2id key-derivation function (KDF) by default

### ISSUE THREAD

**Issue by rugk** [storaged-project/udisks#1186]
> Seeing https://mjg59.dreamwidth.org/66429.html ("PSA: upgrade your LUKS key derivation function", as it is otherwise likely insecure nowadays), it advises not only to switch to LUKS2 `argon2id` instead of `argon2i`. Does GNOME-Disks use this?

from https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/issues/193#note_1726156

I read gnome-disks uses [udisk under the hood and you may have actually already switched to LUKS2, which is good](https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/merge_requests/49), so it may actually be a good idea to use this new best-practise KDF too.

downstream: https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/issues/309

**Comment by vojtechtrefny** [comment]
We don't set KDF in udisks (or libblockdev), we just use the default from cryptsetup, which should be argon2id since 2.4.0. You can check the default from `cryptsetup --help`:

```
Default PBKDF for LUKS2: argon2id
```
