### ISSUE TITLE
Error mounting NTFS drives through Dolphin and ntfs-3g since the latest update

### ISSUE THREAD

**Issue by RAIACAD0564** [storaged-project/udisks#1190]
Hi, I am on Arch Linux and after updating udisks to udisks2-2.10.1, I can't correctly mount my NTFS drives. 

I get the error: "An error occurred while accessing 'Old Seagate 4TB Storage HDD', the system responded: The requested operation has failed: Error mounting /dev/sdb1 at /run/media/raiacad0564/Old Seagate 4TB Storage HDD: wrong fs type, bad option, bad superblock on /dev/sdb1, missing codepage or helper program, or other error"

Before the update, everything worked as expected and I was able to mount my drives. I also tried downgrading systemd to see if it was the issue and I still had the issue. The only things I saw in the update that may be causing the issue is either udisks (this), libblockdev, or libnvme. Could also be a change conflicting with ntfs-3g. Feel free to correct me if it is one of those other packages.

**Comment by stasadev** [comment]
I downgraded both packages to make them work again on Arch:

```
extra/libblockdev  3.0.3-4  -> 2.28-4
extra/udisks2      2.10.1-1 -> 2.9.4-4
```

**Comment by tbzatek** [comment]
You need either the kernel `ntfs3` module or `ntfs-3g`. Both options are supported, `ntfs3` is still having some stability issues.

**Comment by RAIACAD0564** [comment]
I already have ntfs-3g installed. The issue only started occurring once I updated udisks and libblockdev. Trying to mount now gives me the error I mentioned.

**Comment by RAIACAD0564** [comment]
Oops, mispress, I apologize.

**Comment by RAIACAD0564** [comment]
![Screenshot_20230921_073013_Crop](https://github.com/storaged-project/udisks/assets/113588483/761b2db6-4aa1-488b-9448-bca84218a1fc)
Here what I have installed. udisks2, libblockdev, and libnvme being the ones that I recently updated.

**Comment by RAIACAD0564** [comment]
Okay, regular shell mount works. `/etc/udisks2/mount_options.conf` does not even exist, only the example. Here's some logs for each.

When using `sudo mount -t ntfs /dev/sdb1 /mnt/ntfs1` journalctl says:
Sep 21 08:26:50 Rukia sudo[5345]: raiacad0564 : TTY=pts/1 ; PWD=/home/raiacad0564 ; USER=root ; COMMAND=/usr/bin/mount -t ntfs /dev/sdb1 /mnt/ntfs1
Sep 21 08:26:50 Rukia sudo[5345]: pam_unix(sudo:session): session opened for user root(uid=0) by raiacad0564(uid=1000)
Sep 21 08:26:50 Rukia ntfs-3g[5352]: Version 2022.10.3 external FUSE 29
Sep 21 08:26:50 Rukia ntfs-3g[5352]: Mounted /dev/sdb1 (Read-Write, label "Old Seagate 4TB Storage HDD", NTFS 3.1)
Sep 21 08:26:50 Rukia ntfs-3g[5352]: Cmdline options: rw
Sep 21 08:26:50 Rukia ntfs-3g[5352]: Mount options: allow_other,nonempty,relatime,rw,fsname=/dev/sdb1,blkdev,blksize=4096
Sep 21 08:26:50 Rukia ntfs-3g[5352]: Ownership and permissions disabled, configuration type 7
Sep 21 08:26:50 Rukia sudo[5345]: pam_unix(sudo:session): session closed for user root

`udevadm info /dev/sdb1` output:
P: /devices/pci0000:00/0000:00:01.2/0000:02:00.1/ata2/host1/target1:0:0/1:0:0:0/block/sdb/sdb1
M: sdb1
R: 1
U: block
T: partition
D: b 8:17
N: sdb1
L: 0
S: disk/by-uuid/01D6E77770A38F20
S: disk/by-diskseq/2-part1
S: disk/by-partuuid/6ff79fb0-e777-01d6-d8cb-fbb7bb73eb00
S: disk/by-path/pci-0000:02:00.1-ata-2.0-part1
S: disk/by-id/wwn-0x5000c500c6bf62ce-part1
S: disk/by-id/ata-ST4000DM004-2CV104_ZFN3L6FW-part1
S: disk/by-partlabel/Basic\x20data\x20partition
S: disk/by-label/Old\x20Seagate\x204TB\x20Storage\x20HDD
S: disk/by-path/pci-0000:02:00.1-ata-2-part1
Q: 2
E: DEVPATH=/devices/pci0000:00/0000:00:01.2/0000:02:00.1/ata2/host1/target1:0:0/1:0:0:0/block/sdb/sdb1
E: DEVNAME=/dev/sdb1
E: DEVTYPE=partition
E: DISKSEQ=2
E: PARTN=1
E: PARTNAME=Basic data partition
E: MAJOR=8
E: MINOR=17
E: SUBSYSTEM=block
E: USEC_INITIALIZED=4496823
E: DM_MULTIPATH_DEVICE_PATH=0
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=ST4000DM004-2CV104
E: ID_MODEL_ENC=ST4000DM004-2CV104\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=0001
E: ID_SERIAL=ST4000DM004-2CV104_ZFN3L6FW
E: ID_SERIAL_SHORT=ZFN3L6FW
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=1
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=502
E: ID_ATA_FEATURE_SET_SECURITY_ENHANCED_ERASE_UNIT_MIN=502
E: ID_ATA_FEATURE_SET_SECURITY_FROZEN=1
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=5425
E: ID_WWN=0x5000c500c6bf62ce
E: ID_WWN_WITH_EXTENSION=0x5000c500c6bf62ce
E: ID_PATH=pci-0000:02:00.1-ata-2.0
E: ID_PATH_TAG=pci-0000_02_00_1-ata-2_0
E: ID_PATH_ATA_COMPAT=pci-0000:02:00.1-ata-2
E: ID_PART_TABLE_UUID=dfe6a3e0-ceee-03ad-f8a8-f9b7bb73eb00
E: ID_PART_TABLE_TYPE=gpt
E: ID_FS_LABEL=Old_Seagate_4TB_Storage_HDD
E: ID_FS_LABEL_ENC=Old\x20Seagate\x204TB\x20Storage\x20HDD
E: ID_FS_BLOCKSIZE=4096
E: ID_FS_SIZE=4000785100800
E: ID_FS_UUID=01D6E77770A38F20
E: ID_FS_UUID_ENC=01D6E77770A38F20
E: ID_FS_TYPE=ntfs
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=gpt
E: ID_PART_ENTRY_NAME=Basic\x20data\x20partition
E: ID_PART_ENTRY_UUID=6ff79fb0-e777-01d6-d8cb-fbb7bb73eb00
E: ID_PART_ENTRY_TYPE=ebd0a0a2-b9e5-4433-87c0-68b6b72699c7
E: ID_PART_ENTRY_NUMBER=1
E: ID_PART_ENTRY_OFFSET=2048
E: ID_PART_ENTRY_SIZE=7814033408
E: ID_PART_ENTRY_DISK=8:16
E: DEVLINKS=/dev/disk/by-uuid/01D6E77770A38F20 /dev/disk/by-diskseq/2-part1 /dev/disk/by-partuuid/6ff79fb0-e777-01d6-d8cb-fbb7bb73eb00 /dev/disk/by-path/pci-0000:02:00.1-ata-2.0-part>
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

**Comment by RAIACAD0564** [comment]
Also, trying to use Dolphin again, I think I may have found the issue. It seems to be trying to call on ntfs3 instead strangely enough (I didn't used to see this). It is weird though I only had this issue after updating libblockdev and udisks though. Anyways, here's what journalctl says for using Dolphin to mount:

Sep 21 08:39:30 Rukia polkitd[1031]: Operator of unix-session:2 successfully authenticated as unix-user:raiacad0564 to gain TEMPORARY authorization for action org.freedesktop.udisks2.filesystem-mount-system for system-bus-name::1.326 [/usr/bin/dolphin] (owned by unix-user:raiacad0564)
Sep 21 08:39:30 Rukia kernel: ntfs3: Max link count 4000
Sep 21 08:39:30 Rukia kernel: ntfs3: Enabled Linux POSIX ACLs support
Sep 21 08:39:30 Rukia kernel: ntfs3: Read-only LZX/Xpress compression included
Sep 21 08:39:30 Rukia kernel: ntfs3: sdb1: It is recommened to use chkdsk.
Sep 21 08:39:31 Rukia kernel: ntfs3: sdb1: volume is dirty and "force" flag is not set!

In Dolphin's GUI it then says: "
An error occurred while accessing 'Old Seagate 4TB Storage HDD', the system responded: The requested operation has failed: Error mounting /dev/sdb1 at /run/media/raiacad0564/Old Seagate 4TB Storage HDD: wrong fs type, bad option, bad superblock on /dev/sdb1, missing codepage or helper program, or other error"

**Comment by RAIACAD0564** [comment]
Ah ha! Similar behavior with specifying `-t ntfs3` 

journalctl says: 
Sep 21 09:00:22 Rukia sudo[7549]: raiacad0564 : TTY=pts/1 ; PWD=/home/raiacad0564 ; USER=root ; COMMAND=/usr/bin/mount -t ntfs3 /dev/sdb1 /mnt/ntfs1
Sep 21 09:00:22 Rukia sudo[7549]: pam_unix(sudo:session): session opened for user root(uid=0) by raiacad0564(uid=1000)
Sep 21 09:00:22 Rukia kernel: ntfs3: sdb1: It is recommened to use chkdsk.
Sep 21 09:00:22 Rukia sudo[7549]: pam_unix(sudo:session): session closed for user root

Terminal displays:
mount: /mnt/ntfs1: wrong fs type, bad option, bad superblock on /dev/sdb1, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.

dmesg says:
[ 1126.453369] ntfs3: Max link count 4000
[ 1126.453372] ntfs3: Enabled Linux POSIX ACLs support
[ 1126.453373] ntfs3: Read-only LZX/Xpress compression included
[ 1126.454156] ntfs3: sdb1: It is recommened to use chkdsk.
[ 1126.792391] ntfs3: sdb1: volume is dirty and "force" flag is not set!
[ 2377.997543] ntfs3: sdb1: It is recommened to use chkdsk.
[ 2378.070307] ntfs3: sdb1: volume is dirty and "force" flag is not set!

**Comment by tbzatek** [comment]
So yeah, the recommended way is to run `ntfsfix` or any other windows fsck. There must be a reason why the kernel `ntfs3` driver recommends it and prevents the mount. Using the `force` mount option is generally usafe and may lead to data loss.

**Comment by randomusername-a** [comment]
Shouldn't udisks at least be more clear with the error it returns? The message "Error mounting $DISK at $PATH: wrong fs type, bad option, bad superblock on $DISK, missing codepage or helper program, or other error" is hilariously vague.

**Comment by tbzatek** [comment]
That's a kernel/libmount limitation. Feel free to open a ticket at https://github.com/util-linux/util-linux/

**Comment by Barrettloganj13** [comment]
I am experiencing the same issue and none of the steps work one drive started to not mount and now two drives are not mounting

**Comment by Barrettloganj13** [comment]
and it is not the drives

**Comment by RealityVoid** [comment]
Also on Arch, also have this issue when trying to mount using either Dolphin or Konqueror. Mount form command line runs just fine, ran  ntfsfix but did not find any issues. I have a bunch of other drives, and those seem to work fine, it's just the one ntfs drive that seems to have problems. 

Unmounting it from the same places works just fine.

**Comment by Barrettloganj13** [comment]
apparently it did not work for me

**Comment by RealityVoid** [comment]
@Barrettloganj13  did you run a chkdsk on the drive? I do not have a Windows system I can easily run on the drive, curious if that would do anything.

**Comment by Barrettloganj13** [comment]
can not at this time

**Comment by Wunst** [comment]
Was having the same issue.
Fixed it by clearing the dirty flag manually using `ntfsfix -d`. Don't know if this is a "good thing" to do though

**Comment by tbzatek** [comment]
See my comment above: https://github.com/storaged-project/udisks/issues/1190#issuecomment-1729635413

UDisks cannot perform any fsck as part of mounting, nor any modifications to the fileystem. This should be brought to the kernel driver maintainers.

Clients may offer you a possibility to run additional Check or Repair function: http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Filesystem.html#gdbus-method-org-freedesktop-UDisks2-Filesystem.Repair

**Comment by manhhieu2909** [comment]
Start the Windows operating system then run cmd with Administrator rights. Use the following command to fix NTFS `chkdsk C: /f`  (C replace with the partition to fix). Restart and boot into linux. Re-mount the drive

**Comment by tbzatek** [comment]
I'm going to close this ticket since the discussion is unrelated to UDisks. See my comments above. The dirty-flag mount operation refusal should be brought to the kernel ntfs3 maintainers.

**Comment by unoexperto** [comment]
@Wunst thank you for mentioning `-d` flag. It helped me on Kubuntu 23.10.

**Comment by XChaosSaMa** [comment]
> Was having the same issue. Fixed it by clearing the dirty flag manually using `ntfsfix -d`. Don't know if this is a "good thing" to do though

Worked for me! I have a "Seagate Barracuda Q5 - 2TB". Same situation, using "mount" manually was fine, but now i can mount it with Dolphin without problem.

**Comment by teohhanhui** [comment]
I'm just a stranger on the Internet, but please don't use `ntfsfix`. You're asking for data loss.

https://github.com/storaged-project/udisks/pull/917#issuecomment-2144194371

**Comment by stronger1234** [comment]
`ntfsfix -d` works for me too. I also have dual boot systems installed (with Debian 13 and Windows 11).

However, if boot to Windows after `ntfsfix`, and power off and on (not reboot) to Debian, the error message "wrong fs type, ..." appears again when mount the NTFS partition from Dolphin (or `udisksctl mount` without explicitly specifying `-t ntfs` option). I have to run `ntfsfix -d` again once power off from Windows.

I think the NTFS partition may be somehow affected by the Fast-Startup feature on Windows, which was turned on by default. Now I turn that feature off, then powering off from Windows won't dirty my NTFS partition anymore. Mounting NTFS partition in Dolphin always works for me now.
