### ISSUE TITLE
[2.10.1] 100% of CPU usage and OOM at startup

### ISSUE THREAD

**Issue by dbermond** [storaged-project/udisks#1192]
When upgrading udisks from 2.9.4 to 2.10.1, the system becomes extremely slow and unresponsive at startup. The process `udisksd` gets 100% of CPU usage and the udisks service is killed by the OOM killer. Version 2.9.4 works fine for me.

Service log:
```
-- Boot 8a5b79c817a649ca83276ba6a798feca --
set 21 14:18:20 myhostname systemd[1]: Starting Disk Manager...
set 21 14:18:20 myhostname udisksd[1060]: udisks daemon version 2.10.1 starting
set 21 14:19:50 myhostname systemd[1]: udisks2.service: start operation timed out. Terminating.
set 21 14:21:05 myhostname systemd[1]: udisks2.service: A process of this unit has been killed by the OOM killer.
set 21 14:21:05 myhostname systemd[1]: udisks2.service: Killing process 1060 (udisksd) with signal SIGKILL.
set 21 14:21:06 myhostname systemd[1]: udisks2.service: Main process exited, code=killed, status=9/KILL
set 21 14:21:06 myhostname systemd[1]: udisks2.service: Failed with result 'timeout'.
set 21 14:21:06 myhostname systemd[1]: Failed to start Disk Manager.
set 21 14:21:06 myhostname systemd[1]: udisks2.service: Consumed 2min 26.011s CPU time.
set 21 14:21:30 myhostname systemd[1]: Starting Disk Manager...
set 21 14:21:30 myhostname udisksd[1327]: udisks daemon version 2.10.1 starting
set 21 14:23:38 myhostname systemd[1]: udisks2.service: State 'stop-sigterm' timed out. Killing.
set 21 14:23:38 myhostname systemd[1]: udisks2.service: Killing process 1327 (udisksd) with signal SIGKILL.
set 21 14:23:38 myhostname systemd[1]: udisks2.service: Killing process 1328 (gmain) with signal SIGKILL.
set 21 14:23:38 myhostname systemd[1]: udisks2.service: Killing process 1329 (pool-spawner) with signal SIGKILL.
set 21 14:23:38 myhostname systemd[1]: udisks2.service: Killing process 1331 (gdbus) with signal SIGKILL.
set 21 14:23:38 myhostname systemd[1]: udisks2.service: Killing process 1332 (probing-thread) with signal SIGKILL.
set 21 14:23:39 myhostname systemd[1]: udisks2.service: Main process exited, code=killed, status=9/KILL
set 21 14:23:39 myhostname systemd[1]: udisks2.service: Failed with result 'timeout'.
set 21 14:23:40 myhostname systemd[1]: Stopped Disk Manager.
set 21 14:23:40 myhostname systemd[1]: udisks2.service: Consumed 2min 9.155s CPU time. 
```

- System: Arch Linux x86_64
- udisksctl dump (from working 2.9.4): [udisksctl-dump.txt](https://github.com/storaged-project/udisks/files/12689981/udisksctl-dump.txt)
- libblockdev: 3.0.3 (updated from 2.28 alongside with udisks 2.10.1)
- libnvme: 1.5

**Comment by tbzatek** [comment]
Yuck, sounds like a uevent storm - `udevadm monitor` might reveal the suspicion. The attched udisksctl dump looks sane, we'll need some backtrace to see what's going on. Anything in `coredumpctl`? Another option might be to start `udisksd` in `gdb` and gradually see where is it being stuck on.

**Comment by dbermond** [comment]
Thank you for the reply. `udevadm monitor` shows nothing. There is nothing in `coredumpctl` for udisks. Since the service is being killed by the OOM killer, there is no back trace / core dump of a crash, as the program does not crashes itself. It just consumes all the memory and is externally killed. I tried to run in gdb to find something, but it's a bit difficult since udisks uses glib. The issue starts when calling g_main_loop_run(), but this tells nothing. I'm not used to glib (and neither to udisks source code) to know where to properly set some breakpoints in order at least determine what part of code can be causing the issue. And depending on how this is happening, it may not even be stuck in some line of code, but only somehow consuming memory until being externally killed.

**Comment by tbzatek** [comment]
Good, at least it's not caused by a uevent storm. Similar issue has been reported in #1195, let's try to debug both in parallel.

Can you try running valgrind on udisksd? Something like `G_DEBUG=resident-modules valgrind --leak-check=full --leak-resolution=high --num-callers=20 --log-file=vgdump.log /usr/libexec/udisks2/udisksd --replace --debug --disable-modules`

**Comment by dbermond** [comment]
I updated libnvme to 1.6, and the problem persists.

Valgrind shows only the header message (copyright, version, etc). In the terminal, only the udisks start message is printed (udisks daemon version 2.10.1 starting). Nothing more is printed to the valgrind log file or to the terminal. No valgrind diagnostic messages or report summary. I let udisksd run until it is killed. Since the program does not finish (but is killed instead), valgrind cannot properly output the summary, as it effectively determines if the allocated memory was freed only when the program terminates.

**Comment by tbzatek** [comment]
One hint to check: try setting a breakpoint for `bd_nvme_find_ctrls_for_ns()` and see if the call returns or gets stuck.

**Comment by dbermond** [comment]
Execution does not reach breakpoint `bd_nvme_find_ctrls_for_ns`. The memory consumption starts before it. Also tried `find_drive` as the initial breakpoint, as it's from where `bd_nvme_find_ctrls_for_ns` is called, and the result is the same (issue starts before reaching it). Please let me know if you wish me to try another breakpoints.

**Comment by tbzatek** [comment]
Thanks, let's try moving closer. If we assume this is NVMe-specific, then the first drive probing happens in `udisks_linux_device_reprobe_sync()`. Perhaps also `udisks_linux_device_subsystem_is_nvme()` might be interesting to you since there's a loop over a device hierarchy.

On a related note, this fix might potentially make a difference, though not directly related: https://github.com/storaged-project/libblockdev/pull/969

**Comment by dbermond** [comment]
Execution reaches both breakpoints `udisks_linux_device_reprobe_sync` and `udisks_linux_device_subsystem_is_nvme` before starting the issue. When going further with `next`commands, the issue starts from both breakpoints at the same place:

- at [`bd_nvme_get_namespace_info()`](https://github.com/storaged-project/udisks/blob/udisks-2.10.1/src/udiskslinuxdevice.c#L214).

By stepping in libblockdev's `bd_nvme_get_namespace_info()` with the `step` command, it looks like the program enters an infinite loop at [this for loop](https://github.com/storaged-project/libblockdev/blob/3.0.3-1/src/plugins/nvme/nvme-info.c#L636-L661), since the following code is repeated by gdb so many times without proceeding down in source:

```
637                 struct nvme_ns_id_desc *d = (void *) desc + i;
(gdb) n
639                 if (!d->nidl)
(gdb) n
641                 len = d->nidl + sizeof (*d);
(gdb) n
643                 switch (d->nidt) {
(gdb) n
650                         info->nguid = g_malloc0 (d->nidl * 2 + 1);
(gdb) n
651                         for (i = 0; i < d->nidl; i++)
(gdb) n
652                             snprintf (info->nguid + i * 2, 3, "%02x", d->nid[i]);
(gdb) n
651                         for (i = 0; i < d->nidl; i++)
(gdb) n
652                             snprintf (info->nguid + i * 2, 3, "%02x", d->nid[i]);
(gdb) n
651                         for (i = 0; i < d->nidl; i++)
(gdb) n
637                 struct nvme_ns_id_desc *d = (void *) desc + i;
...
```

I see that this for loop is changed in the libblockdev merged pull request that you pointed. I have yet to try it. Do you think it has the potential to fix it?

**Comment by dbermond** [comment]
I've just tested it, and I can confirm that applying commit https://github.com/storaged-project/libblockdev/commit/2ae0d949eb87142b0212e5953a0e5ad1a146ed6b on top of libblockdev 3.0.3 **fixes** the issue for me. The `udisksd` service runs normally at startup without being killed by the OOM killer. No memory increase and no 100% of usage anymore. System is stable at startup.

Thank you for your assistance and for fixing it!

**Comment by tbzatek** [comment]
Interesting, thanks for debugging this! This really looks like stack corruption, even though the cycle looks reasonably guarded, the working memory is already garbage.
