### ISSUE TITLE
Test fails with clang

### ISSUE THREAD

**Issue by MANGOPIE3** [storaged-project/udisks#1200]
Hi，I have a question about `/udisks/daemon/spawned_job/abnormal_termination.`  unit test.
I failed when execute with clang。
In related issue[#891](https://github.com/storaged-project/udisks/issues/891), he did a special treatment for clang.
![image](https://github.com/storaged-project/udisks/assets/17828807/2fa6b564-b0d9-419e-a18f-c08052217bf5)
Does Clang compile always emit a signal **SIGILL (4)** when accessing null pointers? 
such as codes in `src\tests\helper.c`
```c
case 4:
  /* cause abnormal termination, segfault */
  g_print ("OK, deliberately causing a segfault\n");
  {
	const gchar **p = NULL;
	/* coverity[var_deref_op] */
	*p = "fail";
  }
  g_assert_not_reached ();
  break;
```
I test it on all version of clang on godbolt, it all emited **SIGSEGV (11)** not **SIGILL (4)**!
https://godbolt.org/z/xzW3dKxv7

In what scenarios will the abnormal_termination test emit **SIGILL (4)** ?

**Comment by tbzatek** [comment]
I suppose this may vary depending on the CPU architecture used, compiler and kernel version. Would be nice to cover both scenarios.

**Comment by MANGOPIE3** [comment]
I may have found the reason.
I find the null pointer dereference code will emit SIGILL (4) when the version  of clang is lower than 13.0.0 and compiled with -O2 option on x86.
The -O2 optimization will delete the null pointer dereference on clang-13, but on clang-12, the null pointer dereference  will be replace with the `ud2` instuction which casues  the invalid opcode exception and emit signal SIGILL (4).
![image](https://github.com/storaged-project/udisks/assets/17828807/02d19f32-ccf1-424a-b356-29db84af467d)

I have a solution, add optimize -O0 option to the main function of `src/tests/helper.c` and it could always emit SIGSEGV (11) signal.
```c
#if __clang__
__attribute__((optnone))  
#else
__attribute__((optimize((0))))
#endif
int
main (int argc, char *argv[])
{
  gint ret;

  ret = 1;

  g_assert_cmpint (argc, ==, 2);
  switch (strtol (argv[1], NULL, 10))
    {
```

**Comment by tbzatek** [comment]
Yeah, this looks fine. Might be also worth changing the Makefile to ignore all CFLAGS.
https://github.com/storaged-project/udisks/blob/master/src/tests/Makefile.am

**Comment by MANGOPIE3** [comment]
I learned from the article about Flag-Variables-Ordering  of automake
https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html.
Ignoring all CFLAGS in Makefile.am is a good idea, we'd better not modify CFLAGS in Makefile.am.
