### ISSUE TITLE
case-sensitive iso mount

### ISSUE THREAD

**Issue by walkero-gr** [storaged-project/udisks#1202]
I am using `udisksctl mount` to mount an iso9660 image file but all the filenames are lower case.

I tried mount with the following parameters
`mount -t iso9660 -o loop,check=relaxed,map=off,norock,nojoliet` and that makes the files case-sensitive, but I would like to use udisksctl for that. 
Would it be possible to do the same with udisksctl?
I tried the `--options` with udisksctl but doesn't seem to work, getting errors that those options are not supported
Any help is much appreciated

**Comment by tbzatek** [comment]
You can always redefine mount options yourself: http://storaged.org/doc/udisks2-api/latest/mount_options.html

I've added `map` and `check` options for `iso9660` - see the referenced pull request and test it if possible please.
