### ISSUE TITLE
teardown fails on locked LUKS block dev: Call failed: Error synchronizing after initial wipe: Timed out waiting for object

### ISSUE THREAD

**Issue by martinpitt** [storaged-project/udisks#1204]
About a week ago, cockpit's storage tests against the nightly udisks COPR [started to fail](https://github.com/cockpit-project/cockpit/issues/19445) in `testOverMounting`. This creates a GPT partition, a (really two, but that doesn't matter) LUKS partition on it, locks it, and then tries to re-format the whole device with tear-down. This works fine in Fedora 38's udisks2-2.9.4-7.fc38.x86_64, but fails with udisks2-2.11.0-1.20231011045721822941.master.73.g2fc7aae4.fc38.x86_64 from https://copr.fedorainfracloud.org/coprs/g/storage/udisks-daily

Pure CLI reproducer:

1. Update to daily COPR:
```
dnf -y copr enable @storage/udisks-daily; dnf -y --setopt=install_weak_deps=False update
```

2. Create a storage device. `scsi_debug` works fine:
```
modprobe scsi_debug dev_size_mb=100
```
This usually creates `/dev/sda`. If you already have that, it'll be a different one. The following reproducer assumes /dev/sda.

3. Format it with GPT:
```
busctl call org.freedesktop.UDisks2 /org/freedesktop/UDisks2/block_devices/sda org.freedesktop.UDisks2.Block Format 'sa{sv}' 'gpt' 0
```

4. Create a LUKS ext4 partition on it, with fstab/crypttab options and tracking parents:
```
busctl call org.freedesktop.UDisks2 /org/freedesktop/UDisks2/block_devices/sda org.freedesktop.UDisks2.PartitionTable CreatePartitionAndFormat 'ttssa{sv}sa{sv}' 0 50000000 '' '' 0 ext4 3 encrypt.type s luks2 encrypt.passphrase s foobar config-items "a(sa{sv})" 2      fstab 6 track-parents b true dir ay 9 47 114 117 110 47 102 111 111 0 type ay 5 97 117 116 111 0 opts ay 14 110 111  97 117 116 111  44 110 111 102  97 105 108 0 freq i 0 passno i 0      crypttab 2 options ay 14 110 111  97 117 116 111  44 110 111 102  97 105 108 0 passphrase-contents ay 1 0
```
This is quite a mouthful and hard to read due to the byte arrays.  I translated this from Cockpit's D-Bus call, whose JSON dump is this:

```json
[
    0,
    50000000,
    "",
    "",
    {

    },
    "ext4",
    {
        "tear-down": {
            "t": "b",
            "v": true
        },
        "encrypt.passphrase": {
            "t": "s",
            "v": "foobar"
        },
        "encrypt.type": {
            "t": "s",
            "v": "luks2"
        },
        "config-items": {
            "t": "a(sa{sv})",
            "v": [
                [
                    "crypttab",
                    {
                        "options": {
                            "t": "ay",
                            "v": "bm9hdXRvLG5vZmFpbAA="
                        },
                        "track-parents": {
                            "t": "b",
                            "v": true
                        },
                        "passphrase-contents": {
                            "t": "ay",
                            "v": "AA=="
                        }
                    }
                ],
                [
                    "fstab",
                    {
                        "dir": {
                            "t": "ay",
                            "v": "L3J1bi9mb28A"
                        },
                        "type": {
                            "t": "ay",
                            "v": "YXV0bwA="
                        },
                        "opts": {
                            "t": "ay",
                            "v": "bm9hdXRvLG5vZmFpbAA="
                        },
                        "freq": {
                            "t": "i",
                            "v": 0
                        },
                        "passno": {
                            "t": "i",
                            "v": 0
                        },
                        "track-parents": {
                            "t": "b",
                            "v": true
                        }
                    }
                ]
            ]
        }
    }
]
```

`opts`/`options` is `noauto,nofail`, `type` is `ext4`, `dir` is `/run/foo`. The crypttab `track-parents` option does not actually exist, so my CLI reproducer above does not contain it.

This creates a crypttab entry like
```
luks-8b81a135-59fa-4190-bd70-c61b40792128 UUID=8b81a135-59fa-4190-bd70-c61b40792128 none noauto,nofail
```
and an fstab entry like
```
UUID=10f5289e-f225-4c16-8d6c-d426db2bb893 /run/foo auto noauto,nofail,x-parent=8b81a135-59fa-4190-bd70-c61b40792128 0 0
```

5. Now lock the device (without that step, everything works):
```
busctl call org.freedesktop.UDisks2 /org/freedesktop/UDisks2/block_devices/sda1 org.freedesktop.UDisks2.Encrypted Lock 'a{sv}' 0
```

6. Try to reformat the drive:
```
busctl call org.freedesktop.UDisks2 /org/freedesktop/UDisks2/block_devices/sda org.freedesktop.UDisks2.Block Format 'sa{sv}' 'gpt' 1 'tear-down' b true
```

The latter will hang, and eventually fail with
```
Call failed: Error synchronizing after initial wipe: Timed out waiting for object
```

the journal says
```
udisksd[11637]: Locked device /dev/sda1 (was unlocked as /dev/dm-0)
udisksd[11637]: Error re-reading partition table (BLKRRPART ioctl) on /dev/sda: Device or resource busy
udisksd[11637]: Error synchronizing after initial wipe: Timed out waiting for object
```

Use `systemctl stop udisks2; rmmod scsi_debug` to clean up. Sometimes stopping udisks hangs, or scsi_debug is busy, but some combination of retrying these and calling `cryptsetup luksClose ...` works.

See https://github.com/cockpit-project/cockpit/issues/19445 for debugging details.

**Comment by martinpitt** [comment]
This is apparently not entirely new -- I just [spotted it with RHEL 9.4's udisks](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19487-20231016-080950-f7ea2a06-rhel-9-4-storage/log.html#32). It just happens very rarely there, as opposed to being 100% reliably failing with the daily COPR.

**Comment by martinpitt** [comment]
Affects [RHEL 9.3](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19489-20231016-144148-9757b8f4-rhel-9-3-storage/log.html#32) as well.

**Comment by tbzatek** [comment]
Hmmm, I don't know what to do with this one. I was not able to reproduce this neither on F39 or RHEL 9.4. Judging by the symptoms, I tend to think this is related to a kernel change. Still, UDisks needs to align with any such change.

I've tried to translate your exhaustive description into a testcase: #1213. The only difference is that we use LIO iSCSI devices instead of `scsi_debug`.

FYI, just posted #1212 that brings voluntary block device locking around re-reading partition table. It's a different codepath though, lvm only, but I think I've seen similar issues.

**Comment by martinpitt** [comment]
I tested the reproducer on current F39 cloud image, out of "thin air":
```
curl -o fedora.qcow2 -L https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2
# nothing fancy, just admin:foobar and root:foobar
curl -L -O https://github.com/cockpit-project/bots/raw/main/machine/cloud-init.iso
qemu-system-x86_64 -cpu host -enable-kvm -nographic -m 2048 -drive file=fedora.qcow2,if=virtio -snapshot -cdrom cloud-init.iso -net nic,model=virtio -net user,hostfwd=tcp::2201-:22

ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=no -p 2201 admin@localhost
sudo -i
```

The reproducer fails reliably there.

```
udisks2-2.11.0-1.20231110114333589745.master.83.gbad0fc97.fc39.x86_64
libblockdev-3.0.4.1-1.20231110145502407903.master.32.ga4e6484e.fc39.x86_64
kernel-core-6.5.6-300.fc39.x86_64
```

So perhaps LIO iSCSI vs. scsi_debug makes a difference here?

**Comment by tbzatek** [comment]
> So perhaps LIO iSCSI vs. scsi_debug makes a difference here?

I modified the tests for `scsi_debug` and my results were the same. I think my development VM is cursed.

> I tested the reproducer on current F39 cloud image, out of "thin air":

Interestingly, it reproduces!

**Comment by tbzatek** [comment]
> Interestingly, it reproduces!

Interestingly, it reproduces only when one CPU is given to the VM. Add `-smp 6` (my host native logical CPU count) and everything works.

**Comment by tbzatek** [comment]
Not only a single CPU is needed, udisksd also needs to run as a systemd service. When spawning udisksd from a shell (unconfied), the error doesn't happen either. Might be a consequence of cgroups assignment perhaps. SELinux is permissive in all cases.

Okay, further experiments revealed that the device is held busy for a short period of time, from unknown side. It was not supposed to be udev since udisks acquired the BSD lock just fine. Such thing will inevitably happen all the time. Thus, the most dumb way of work around this is to just try harder...

**Comment by martinpitt** [comment]
Thanks @tbzatek for fixing! I suppose "not running from systemd service" may exactly be what happens in the integration tests?

**Comment by tbzatek** [comment]
> Thanks @tbzatek for fixing! I suppose "not running from systemd service" may exactly be what happens in the integration tests?

Also the case with most of the `dbus-tests` in our CI runs.

Except of perhaps different SELinux context and cgroups membership I don't see any major difference nor explanation why things should work differently.
