### ISSUE TITLE
Frequent crashes involving libc

### ISSUE THREAD

**Issue by fdw** [storaged-project/udisks#1208]
I have absolutely no idea if this the right place to report this, so please close the issue if I'm wrong.

I'm on Manjaro, using udisks2 `2.10.1-2` and glibc `2.38-7`, kernel `6.4.16-5-MANJARO`. Since about the last update to udisks 2.10, it frequently crashes for me and leaves coredumps. As far as I can see, it's always in some combination with libc.6.so, but in different places with (at least) SIGSEGV and SIGABRT.

I haven't found a related issue anywhere. What can I do to help fix this?

**Comment by tbzatek** [comment]
What is your libblockdev version? We'll need a backtrace to see what's happening.

**Comment by fdw** [comment]
> What is your libblockdev version?

`3.0.3-4`

> We'll need a backtrace to see what's happening.

Sorry for the dumb question, but how can I send it to you? I'm new to coredumps and all that stuff, sorry.

**Comment by tbzatek** [comment]
Please test `libblockdev-3.0.4`, there were some more fixes.

**Comment by DistantThunder** [comment]
Hello, I'm on Arch Linux and also started experiencing consistent crashes in UDISKS2 when using Gnome Disks:

* 2.10.1-2
* libblockdev: 3.0.4-1

> Process 796521 (gnome-disks) of user 1000 dumped core.
>
>udisksd[1141572]: free(): double free detected in tcache 2
[...]

                                                      Stack trace of thread 796521:
                                                      #0  0x00007fac497cf077 g_type_check_instance_cast (libgobject-2.0.so.0 + 0x3b077)
                                                      #1  0x00007fac489d7ee4 hdy_header_bar_set_subtitle (libhandy-1.so.0 + 0x34ee4)
                                                      #2  0x0000556c60ef901e n/a (gnome-disks + 0x4101e)
                                                      #3  0x00007fac484d44f6 n/a (libffi.so.8 + 0x74f6)
                                                      #4  0x00007fac484d0f5e n/a (libffi.so.8 + 0x3f5e)
                                                      #5  0x00007fac484d3b73 ffi_call (libffi.so.8 + 0x6b73)
                                                      #6  0x00007fac497ae8a4 g_cclosure_marshal_generic (libgobject-2.0.so.0 + 0x1a8a4)
                                                      #7  0x00007fac497a86c0 g_closure_invoke (libgobject-2.0.so.0 + 0x146c0)
                                                      #8  0x00007fac497d6a36 n/a (libgobject-2.0.so.0 + 0x42a36)
                                                      #9  0x00007fac497c7a42 n/a (libgobject-2.0.so.0 + 0x33a42)
                                                      #10 0x00007fac497c7c77 g_signal_emit_valist (libgobject-2.0.so.0 + 0x33c77)
                                                      #11 0x00007fac497c7d34 g_signal_emit (libgobject-2.0.so.0 + 0x33d34)
                                                      #12 0x00007fac48ad0b00 n/a (libudisks2.so.0 + 0x7eb00)
                                                      #13 0x00007fac496a33ee n/a (libglib-2.0.so.0 + 0x5b3ee)
                                                      #14 0x00007fac496a1f69 n/a (libglib-2.0.so.0 + 0x59f69)
                                                      #15 0x00007fac49700327 n/a (libglib-2.0.so.0 + 0xb8327)
                                                      #16 0x00007fac496a0162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
                                                      #17 0x00007fac498d5b16 g_application_run (libgio-2.0.so.0 + 0xdfb16)
                                                      #18 0x0000556c60ece843 main (gnome-disks + 0x16843)
                                                      #19 0x00007fac48550cd0 n/a (libc.so.6 + 0x27cd0)
                                                      #20 0x00007fac48550d8a __libc_start_main (libc.so.6 + 0x27d8a)
                                                      #21 0x0000556c60ece885 _start (gnome-disks + 0x16885)
                                                      
                                                      Stack trace of thread 796522:
                                                      #0  0x00007fac4863773d syscall (libc.so.6 + 0x10e73d)
                                                      #1  0x00007fac496fb2b7 g_cond_wait (libglib-2.0.so.0 + 0xb32b7)
                                                      #2  0x00007fac4966d1b4 n/a (libglib-2.0.so.0 + 0x251b4)
                                                      #3  0x00007fac496d5a7e n/a (libglib-2.0.so.0 + 0x8da7e)
                                                      #4  0x00007fac496d39f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
                                                      #5  0x00007fac485b59eb n/a (libc.so.6 + 0x8c9eb)
                                                      #6  0x00007fac486397cc n/a (libc.so.6 + 0x1107cc)
                                                      
                                                      Stack trace of thread 796523:
                                                      #0  0x00007fac4862bf6f __poll (libc.so.6 + 0x102f6f)
                                                      #1  0x00007fac49700276 n/a (libglib-2.0.so.0 + 0xb8276)
                                                      #2  0x00007fac496a0162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
                                                      #3  0x00007fac496a01b2 n/a (libglib-2.0.so.0 + 0x581b2)
                                                      #4  0x00007fac496d39f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
                                                      #5  0x00007fac485b59eb n/a (libc.so.6 + 0x8c9eb)
                                                      #6  0x00007fac486397cc n/a (libc.so.6 + 0x1107cc)
                                                      
                                                      Stack trace of thread 796526:
                                                      #0  0x00007fac4862bf6f __poll (libc.so.6 + 0x102f6f)
                                                      #1  0x00007fac49700276 n/a (libglib-2.0.so.0 + 0xb8276)
                                                      #2  0x00007fac496a0162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
                                                      #3  0x00007fac47195fde n/a (libdconfsettings.so + 0x5fde)
                                                      #4  0x00007fac496d39f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
                                                      #5  0x00007fac485b59eb n/a (libc.so.6 + 0x8c9eb)
                                                      #6  0x00007fac486397cc n/a (libc.so.6 + 0x1107cc)
                                                      
                                                      Stack trace of thread 796524:
                                                      #0  0x00007fac4862bf6f __poll (libc.so.6 + 0x102f6f)
                                                      #1  0x00007fac49700276 n/a (libglib-2.0.so.0 + 0xb8276)
                                                      #2  0x00007fac496a2b97 g_main_loop_run (libglib-2.0.so.0 + 0x5ab97)
                                                      #3  0x00007fac4990814c n/a (libgio-2.0.so.0 + 0x11214c)
                                                      #4  0x00007fac496d39f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
                                                      #5  0x00007fac485b59eb n/a (libc.so.6 + 0x8c9eb)
                                                      #6  0x00007fac486397cc n/a (libc.so.6 + 0x1107cc)
                                                      ELF object binary architecture: AMD x86-64

This always happens when trying to create a new partition now, whichever the device. However, I was able to resize an existing FAT32 one for example, on the very same device.

**Comment by tbzatek** [comment]
> Gnome Disks

This is unrelated to UDisks.

**Comment by DistantThunder** [comment]
@tbzatek Wrong stack trace sorry, edited with the correct one.

**Comment by vojtechtrefny** [comment]
I have found a problem in libblockdev that could be causing this, but I am not really sure where the problem really is. From the backtrace it looks like the double free is caused by `fdisk_unref_parttype` which we shouldn't call from libblockdev (and https://github.com/storaged-project/libblockdev/pull/985 will fix this), but `fdisk_unref_parttype` itself should guard against this issue and I wasn't able to reproduce the crash.

**Comment by DistantThunder** [comment]
@vojtechtrefny 
For the record, my system is a bit like this:

![image](https://github.com/storaged-project/udisks/assets/3923810/dfcd151a-1c7e-499c-9220-b9e984bb57bf)

**Comment by fdw** [comment]
After an update (mainly kernel and libglib), my original problem seems to be solved. Thanks for your effort 🙂
Feel free to close it, if you want.

**Comment by tbzatek** [comment]
Thanks @fdw, I think it was just another occurrence of the stack smashing issue (that still exists in the kernel) that we provided workarounds in `libblockdev` and `libnvme` for.

@DistantThunder any chance to test the `libblockdev` patch @vojtechtrefny mentioned?

This ticket is messy so I'd like to close it soon.

**Comment by DistantThunder** [comment]
@tbzatek Hello yes, sorry if this wasn't related but I just tested the patch mentioned and I'm able to create/delete partitions in Gnome Disks again without it and Udisks crashing when using lastest git `libblockdev-3.0.4.1.34.ga1dcf489`.

**Comment by tbzatek** [comment]
Thanks for testing! Closing as fixed.
