### ISSUE TITLE
handle_resize does not update the state of the dbus object before returning

### ISSUE THREAD

**Issue by tasleson** [storaged-project/udisks#121]
From looking at the implementation of `handle_resize` it appears that nothing is done to ensure that the dbus object state is updated before it returns to the caller.  I'm thinking that the dbus service only gets updated once the udev event causes the lvm update to occur which could easily happen after the client has already gotten the return value from the resize dbus method.

This would explain why commit 86492479b170eeb587bb734fedee6d823b360188 made things work more reliably.

See also: https://github.com/storaged-project/storaged/issues/117

**Comment by tbzatek** [comment]
I believe this should be fixed by the synthetic uevent tagging work: commit 45fc9b20e766a0194ee0b6bc0434d5b59cd216c2. The `udisks_linux_block_object_trigger_uevent_sync()` call should return once the block object has finished updating all conected D-Bus interfaces.
