### ISSUE TITLE
Wine creates corrupted directories in ntfs3 mounted partitions without `windows_names`

### ISSUE THREAD

**Issue by blacklightpy** [storaged-project/udisks#1243]
When creating a Wine prefix, `dosdevices` folder has symlinks with colons, and somehow they create corrupted directories. This is generally solved by adding `windows_names` to mount options.

This may mean mean that proper Wine directories cannot be created in partitions mounted with ntfs3, but it is better than having them mounted with corrupt directories.

I'm creating a PR that
- Adds `windows_names` to `ntfs3_defaults`
- Also updates the docs to add the new ntfs3 mount options added in #1125, which weren't updated there.

**Comment by tbzatek** [comment]
As explained in #1244 and a couple of times in the past, we can't make this change globally. Distributors are encouraged to tweak the defaults depending on what kernel versions they intend to support.

**Comment by blacklightpy** [comment]
Ok.. I didn't see that before.

**Comment by tbzatek** [comment]
> This may mean mean that proper Wine directories cannot be created in partitions mounted with ntfs3, but it is better than having them mounted with corrupt directories.

On a personal note, this simply doesn't make sense. You cannot expect non-native filesystems to be fully POSIX compliant. In case an inode that is non-native to that filesystem is created and fsck on the native OS is run on it, there's a chance such inodes would be lost.

**Comment by blacklightpy** [comment]
It should be something that's fixed upstream I guess.

You're right, a Check Disk scan would probably destroy those file records. I forgot to consider that.
