### ISSUE TITLE
Whitelisting Mount Options

### ISSUE THREAD

**Issue by Amirmohammadomidi** [storaged-project/udisks#1245]
Please whitelist the 'compress_chksum', 'atgc' and 'gc_merge' mount 
options related to the F2FS file system. It would be great if we could use these options in _mount_option.conf_ under _f2fs_defaults_ section.
As far as I know, they are considered safe and commonly used for mounting a F2FS file system, and they are also recommended by the Archwiki.

**Comment by tbzatek** [comment]
Sounds good, thanks for the heads-up, we're not actively watching such additions to the kernel.
