### ISSUE TITLE
Not able to mount any external ssd/hdd using udisksctl

### ISSUE THREAD

**Issue by parham-dev27** [storaged-project/udisks#1247]
I updated yesterday my arch machine and since then I am not able to mount any SSDs/HDDs.
- It works when I use sudo mount /dev/sdd1 /tmp/sdd
- It shows the following error when I use PcmanFM or gnome-disks: Error mounting /dev/sdd1 at /run/media/user/sdd: wrong fs type, bad option, bad superblock on /dev/sdd1, missing codepage or helper program, or other error
- It shows the following error when I use udisksctl mount -b: Error mounting /dev/sdd1: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error mounting /dev/sdd1 at /run/media/user/sdd: wrong fs type, bad option, bad superblock on /dev/sdd1, missing codepage or helper program, or other error

Since mount  works, I think that the problem is with udisksctl . Already looked at the issues, was not able to find anything related to this problem. 

Package Version: local/udisks2 2.10.1-2
Thanks in advance!

**Comment by vojtechtrefny** [comment]
Please check journal for additional errors from the kernel. Also what type of filesystem do you have on sdd1 or does this happen with all devices regardless of filesystem? Please add here output of `udisksctl info -b /dev/sdd1`

**Comment by tbzatek** [comment]
@parham-dev27, any luck?

**Comment by parham-dev27** [comment]
The problem that happened was that all of my 4 external sdd's file system got corrupted. This was fixed for me using the `fsck` command.  The only thing that I wonder about is that, how `mount` worked but `udisksctl` returned an error.
