### ISSUE TITLE
Whitelist some ext4 mount options

### ISSUE THREAD

**Issue by Amirmohammadomidi** [storaged-project/udisks#1248]
## Issue Description

It would be beneficial to be able to use the `commit` mount option in _mount_option.conf_ under _ext4_defaults section_.

### `commit=nrsec`

The `commit=nrsec` option triggers a journal commit every `nrsec` seconds, providing control over the frequency of journal commits.

> source: Linux manual page

**Comment by tbzatek** [comment]
Added, please test.
