### ISSUE TITLE
udisksctl unlock --key-file fails with BitLocker encrypted disk

### ISSUE THREAD

**Issue by ralfixx** [storaged-project/udisks#1252]
OS is either Opensuse 15.4, udisks2-2.9.2-150400.3.3.1.x86_64, or Ubuntu 22.04 with udisks 2.9.4-1

I have a USB drive where BitLocker encyption was enabled on Windows.
If I insert this drive in my Linux PC (Opensuse 15.4 or Ubuntu 22.04), I can open the drive interactively, like this:
```
$ udisksctl unlock -b /dev/sdc1
Passphrase: 
Unlocked /dev/sdc1 as /dev/dm-0.
```
However, if I put the passphrase in a keyfile, and use that as --key-file, the command fails:
```
$ echo -n passphrase > /tmp/keyfile
$ udisksctl unlock -b /dev/sdc1 --key-file /tmp/keyfile
Error unlocking /dev/sdc1: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: No key available to unlock device /dev/sdc1
```
Should --key-file work with BitLocker encryption?

**Comment by ralfixx** [comment]
Thanks for the reply. If I understand it correctly, --key-file currently does NOT work with BitLocker encryption, only with LUKS encryption? 

As for the patch #1255, note that TCRYPT in cryptsetup(8) also mentions --key-file. Does this also need to be checked there?

**Comment by vojtechtrefny** [comment]
> Thanks for the reply. If I understand it correctly, --key-file currently does NOT work with BitLocker encryption, only with LUKS encryption?

Yes, that's correct.

> 
> As for the patch #1255, note that TCRYPT in cryptsetup(8) also mentions --key-file. Does this also need to be checked there?

Keyfiles in TrueCrypt/VeraCrypt are a little bit different, we need a bigger change in udisksctl for that to work, see https://github.com/storaged-project/udisks/issues/1191

**Comment by ralfixx** [comment]
> > Thanks for the reply. If I understand it correctly, --key-file currently does NOT work with BitLocker encryption, only with LUKS encryption?
> 
> Yes, that's correct.

Thanks for the confirmation. I will switch to LUKS for now.

**Comment by vskode** [comment]
This issue is marked as closed even though as stated here:

> > Thanks for the reply. If I understand it correctly, --key-file currently does NOT work with BitLocker encryption, only with LUKS encryption?
> 
> Yes, that's correct.

the issue is still unresolved. Was this moved to another issue that I am unable to find?
