### ISSUE TITLE
Support specifying PBKDF options

### ISSUE THREAD

**Issue by adombeck** [storaged-project/udisks#1259]
I see that libblockdev supports specifying PBKDF options (`max_memory_kb`, `iterations`, etc.) via the `BDCryptoLUKSExtra` struct in the call to `bd_crypto_luks_format`: https://github.com/storaged-project/libblockdev/blob/291a642f9cebf18334ab2e035a33011d6abbb22a/src/plugins/crypto.c#L929

It would be useful if udisks' `Format` method would also support that.

**Comment by adombeck** [comment]
Would you be open for PRs for this?

**Comment by vojtechtrefny** [comment]
My only problem with this is that we would add quite a lot of new options to the [Block.Format](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-method-org-freedesktop-UDisks2-Block.Format) function. It already has 9 extra options and two of them LUKS-specific option and we would now add 6 more LUKS specific options. This could make the function a little bit too complicated. But I guess we can live that, it's a price we pay for having a single "generic" format function. Thoughts @tbzatek

**Comment by tbzatek** [comment]
Hmm, given that the `Format()` method is the only way to create new LUKS volume in UDisks, I guess we'll have to add these options.
