### ISSUE TITLE
UDisks2.Manager.LoopSetup argument 'read-only' is seemingly ignored.

### ISSUE THREAD

**Issue by ilar** [storaged-project/udisks#1272]
I keep getting the error
```dbus.exceptions.DBusException: org.freedesktop.UDisks2.Error.Failed: Error mounting /dev/loop44p2 at /media/ilar/rootfs: /dev/loop44p2 is write-protected but explicit read-write mode requested```

It doesn't seem like the partition should be, in any way, write-protected. I am explicitly requesting read-only to be false when setting up the Loop, specifically because the entire point of this is to write in the IMG file. And it's not an ISO, so that's not the issue, I can mount the same img just fine with sudo mount, so there's not an issue with the image.

Example code to repeat the issue on Ubuntu:

```python
import dbus

mounts = []
bus = dbus.SystemBus()

try:
    f = open('examples/temp_sensor/therm.img', 'rb')
    manager = bus.get_object('org.freedesktop.UDisks2', '/org/freedesktop/UDisks2/Manager')
    loop_device = manager.LoopSetup(f.fileno(), {'auth.no_user_interaction': False, 'read-only': False},
                                    dbus_interface='org.freedesktop.UDisks2.Manager')
    block_device = bus.get_object('org.freedesktop.UDisks2', loop_device)
    partition_table = block_device.Get('org.freedesktop.UDisks2.PartitionTable', 'Partitions',
                                       dbus_interface='org.freedesktop.DBus.Properties')

    for device_path in partition_table:
        part_proxy = bus.get_object('org.freedesktop.UDisks2', device_path)
        part = dbus.Interface(part_proxy, dbus_interface='org.freedesktop.DBus.Properties')
        part.Mount({'auth.no_user_interaction': False, 'options': 'rw'}, 
                   dbus_interface='org.freedesktop.UDisks2.Filesystem')
finally:
    f.close()
```

This won't actually put in anything in /media/$USER/, because the mount fails, but keep in mind your DE will likely pick up on the new loopback and automount them read-only AFTER the failure, so don't forget to go clean that up.

And yes, it happens after- if you change the mount call to be ro, it happily mounts them. Add a time.sleep, and it will complain they're already mounted, so that's not the issue.

**Comment by vojtechtrefny** [comment]
`f = open('examples/temp_sensor/therm.img', 'rb')`

You need to open the image for writing as well, changing the mode to `r+b` should fix this.

**Comment by ilar** [comment]
That's what I get for coding until 5AM. Thanks a lot!
