### ISSUE TITLE
The system detects internal disks as external disks

### ISSUE THREAD

**Issue by ogarcia** [storaged-project/udisks#1282]
It [comes from here](https://gitlab.gnome.org/GNOME/gvfs/-/issues/738) (GNOME GVFS) and [here](https://bbs.archlinux.org/viewtopic.php?id=295958) (Arch Linux forum).

Initially a Kernel update caused disks, which are not in the fstab, to appear automatically mounted. Seeing that this was triggered by upgrading the kernel from a 6.8 to a 6.9 version it was determined that the culprit change [might be this commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=45b96d65ec68f625ad26ee16d2f556e29f715005). After recompiling the kernel by reverting that change it was found that this commit was indeed the culprit.

With `udisksctl info --block-device /dev/sdb` and the old kernel (before 6.9) `HintAuto` is set to `false`. But from kernel version 6.9 onwards (after the change) it appears set to `true`.

For now there is no open issue in the Kernel for this reason.

**Comment by ogarcia** [comment]
https://lore.kernel.org/regressions/c0de8262-dc4b-4c22-9fac-33432e5bddd3@t-8ch.de/

Finally, the bug has been fixed in the Kernel itself as of version 6.9.6:

> Damien Le Moal (4):
> ata: libata-scsi: Set the RMB bit only for removable media devices

https://lwn.net/Articles/979263/

**Comment by tbzatek** [comment]
Oh nice! Thanks for keeping an eye on this!

**Comment by t-8ch** [comment]
@ghtesting2020 If your nvme drive is affected, this surely is another bug.

Maybe you can try to remove `x-gvfs-show` from your fstab entries?

**Comment by ogarcia** [comment]
> @ghtesting2020 If your nvme drive is affected, this surely is another bug.

I agree, it's probably a different bug.
