### ISSUE TITLE
Feature request: auto mount ntfs as read only

### ISSUE THREAD

**Issue by kurokawachan** [storaged-project/udisks#1318]
## What is the issue
The ntfs usb disk on debian is mounted as read write 

## How to reproduce the issue

-  Using debian stable bookworm with lxde env
- do not change default options
- connect ntfs usb disk 
- The disk is auto mounted as read write

## What do you like to see
The disk is auto mounted as read only
## Why do you believe you have to request  
Ntfs is a proprietary file system. The support for linux is not as fully working as on windows. 
Writing large files to disk sometimes have failures. It is not a good practice to use write to  ntfs disk on linux

As a non technical user, when something defaults to read and write, the user ASSUMES that it would work
 
I suggest we set the default option for mounting ntfs disk as read only.

**Comment by tbzatek** [comment]
Please see https://storaged.org/doc/udisks2-api/latest/mount_options.html

**Comment by kurokawachan** [comment]
Hello @tbzatek Thanks for such quick response, read only is also the default mounting for [Mac](https://www.apple.com/mac/) when they mount ntfs disks. Is there any design decision to mount it as read write

**Comment by kurokawachan** [comment]
Thanks @tbzatek
