### ISSUE TITLE
unlocking Bitlocker encrypted partition with key-file not working

### ISSUE THREAD

**Issue by vskode** [storaged-project/udisks#1325]
I am aware that this issue was supposedly fixed with this merge request #1255 and is addressed in this issue #1252 but for me I still encounter errors when trying to unlock a bitencrypted partition using a key-file:

`udisksctl unlock -b /dev/nvme0n1p7 --key-file /path/to/file`

I get:
`Error unlocking /dev/nvme0n1p7: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: No key available to unlock device /dev/nvme0n1p7`

When I omit the `--key-file` option and enter the passphrase manually it works fine. 
Any help would be appreciated, thank you!

**Comment by vojtechtrefny** [comment]
Which version of udisks are you using? The fix is included only in the [2.10.90](https://github.com/storaged-project/udisks/releases/tag/udisks-2.10.90) pre-release which might not yet be available in your distribution (for example in Debian it's available only in experimental).

**Comment by vskode** [comment]
Oh, thanks for pointing that out. I thought I read it in the Release Notes of 2.9.0 and thus thought something was wrong. I'm on 2.10.0 using Ubuntu 24, so I guess it could be a while until it's supported for that.
Thanks!

**Comment by tbzatek** [comment]
Okay, I'm going to close this now, feel free to reopen once you get to test the 2.10.90 (pre-)release.
