### ISSUE TITLE
Systemd Journal is full of udisksd errors when I put my HDD to sleep

### ISSUE THREAD

**Issue by nick-s-b** [storaged-project/udisks#177]
Hi all,
I have several disks in my machine and one of them is an older 2TB Seagate disk that I use for backup. I tend to put that disk to sleep so it doesn't make any noise since it's very loud.
However, after I do that, my systemd log is full of errors like this (this repeats ever 30 seconds):

```
Jan 16 16:38:04 host2 spindown[447]: suspending sdb
Jan 16 16:38:09 host2 udisksd[721]: Error updating ATA smart for /org/freedesktop/UDisks2/drives/ST2000NC000_2DA164_Z2B777YY: Disk is in sleep mode and the nowakeup option was passed (udisks-error-quark, 13)
Jan 16 16:38:39 host2 udisksd[721]: Error updating ATA smart for /org/freedesktop/UDisks2/drives/ST2000NC000_2DA164_Z2B777YY: Disk is in sleep mode and the nowakeup option was passed (udisks-error-quark, 13)
Jan 16 16:39:09 host2 udisksd[721]: Error updating ATA smart for /org/freedesktop/UDisks2/drives/ST2000NC000_2DA164_Z2B777YY: Disk is in sleep mode and the nowakeup option was passed (udisks-error-quark, 13)
Jan 16 16:39:39 host2 udisksd[721]: Error updating ATA smart for /org/freedesktop/UDisks2/drives/ST2000NC000_2DA164_Z2B777YY: Disk is in sleep mode and the nowakeup option was passed (udisks-error-quark, 13)
Jan 16 16:40:09 host2 udisksd[721]: Error updating ATA smart for /org/freedesktop/UDisks2/drives/ST2000NC000_2DA164_Z2B777YY: Disk is in sleep mode and the nowakeup option was passed (udisks-error-quark, 13)
....
```

How do I stop this endless stream of error messages? Is there a way to tell udisks2 not to report these "errors" about not being able to read smart data for a disk while it's sleeping?

I've come across references to `/etc/udisks2/udisks2.conf` file but I'm not sure what I could put in there to possibly stop these "errors".

Thanks!

**Comment by vojtechtrefny** [comment]
#228 changes these messages to debug, so the log should look better with this. The original problem is somewhere in GNOME -- it shouldn't ask udisks to update the SMART data for sleeping drives. I'll try to find what program is doing this a report the issue to them.
