### ISSUE TITLE
Support for MTP devices?

### ISSUE THREAD

**Issue by coldfix** [storaged-project/udisks#187]
I think udisks/storaged would make a great place to provide MTP support (e.g. using libmtp), enabling clients to easily iterate and manage/mount MTP devices.

What do you think about this? If you are interested, maybe I could dedicate some time to help implement this (disclaimer: I don't have any experience with mtp yet).

**Comment by tsmetana** [comment]
@phatina this looks like your area of expertise, right? ;)

**Comment by alex3kov** [comment]
Would be great to have this.

**Comment by tbzatek** [comment]
MTP devices are handled reasonably well by GVfs, including device discovery and hotplug. GVfs provides POSIX access through `gvfsd-fuse` for non-native GIO clients. There are also several FUSE-based MTP projects out there.

What is your use case, i.e. what do you expect udisks would help you with?

**Comment by alex3kov** [comment]
> What is your use case, i.e. what do you expect udisks would help you with?  

To have MTP devices handled by `udiskie` along with all the other removable drives.

**Comment by tbzatek** [comment]
Then I suggest to embrace `GIO` to access these kind of resources if you want `udiskie` act as an automounter. The `gvfs` `MTPVolumeMonitor` is taking care of device hotplug monitoring, enumeration, mounting, all this via `libmtp`. The `GVfsBackendMtp` then takes care of file access and necessary request serialization, or you can reach out to `libmtp`-based FUSE alternatives.

This is why GVfs exists in the first place, to provide access to non-POSIX compatible devices. And while `udisks` primarily manages local storage system-wide, access to hotpluggable devices or network resources user-wise is provided by upper layer - GVfs in this case (or similar desktop environment alternatives such as `KIO`).

Duplicating the effort to provide similar functionality in `udisks` doesn't seem right to me.

**Comment by alex3kov** [comment]
Let's see what @coldfix will say then - it was his idea to have MTP functionality in `udisks` rather than in `udiskie`. I'm just an end user of both.

**Comment by coldfix** [comment]
Hi,

I was hoping for integration in udisks since adding another big dependency may add substantial complexity in clients such as udiskie, depending on how different the APIs of the different backends are (synchronously/asynchronously designed, etc). However, if you believe that MTP is outside udisks scope, that's fair enough.

That being said, I didn't in fact know about `MTPVolumeMonitor`, so I'm very thankful for the reference. Since I seem to be unable to find any documentation about this service specifically, I assume it is somehow integrated into the [`Gio.VolumeMonitor`](https://lazka.github.io/pgi-docs/#Gio-2.0/classes/VolumeMonitor.html) class. On the other hand, I tried something like

```python
$ python
>>> from gi.repository import Gio
>>> m = Gio.VolumeMonitor.get()
>>> m.get_connected_drives()
[...]
```

and found only system devices, not the connected USB drive nor MTP device. So maybe, I need in fact another entrypoint.. Moreover, a single class that handles all kinds of devices the like would be more like an udisks replacement than an extension.

Using qdbusviewer, I found that there is an `org.gtk.vfs.MTPVolumeMonitor` service that implements `org.gtk.Private.RemoteVolumeManager` interface - which looks like it is not supposed to be used directly.

Since you are clearly more familiar with this topic, could you give me some more pointers?


Best, Thomas

**Comment by niksingh710** [comment]
is this feature is being considered?

**Comment by tbzatek** [comment]
> is this feature is being considered?

Nope, this is out of scope of udisks. Please use gvfs (through gio) instead.
