### ISSUE TITLE
Resolve or report issues with btrfs uevents

### ISSUE THREAD

**Issue by vpodzime** [storaged-project/udisks#200]
As described in https://github.com/storaged-project/storaged/pull/199 properties of btrfs-related DBus objects are not updated properly because on new kernels (e.g. ``4.10.0-0.rc7.git1.1.fc26.x86_64``) we are not getting the proper uevents when doing btrfs operations. (older kernels, e.g. ``4.9.7-201.fc25.x86_64`` work just fine). We need to either work around the issue or report it to btrfs developers so it gets resolved on their side.

**Comment by tbzatek** [comment]
This is not a rare phenomenon and certainly not related just to `btrfs`. With synthetic uevent tagging in place now we'll just trigger uevent after making any changes that would affect udev properties. It brings the advantage of updating object properties before a method call returns.

My attempt to fix this is #750 where I've reverted most of #199.
