### ISSUE TITLE
Syntax errors in translation files

### ISSUE THREAD

**Issue by piotrdrag** [storaged-project/udisks#206]
Almost every translation has fatal syntax errors:

https://l10n.gnome.org/module/udisks/

It's because %u variables are incorrectly translated as %d.

**Comment by vojtechtrefny** [comment]
Unfortunately Zanata doesn't treat these as errors by default (it only shows a warning) and changing it doesn't mark the invalid translations as fuzzy. I've reported a bug, so I hope Zanata developers will fix that or provide some workaround (other than downloading the po files and changing it manually).

**Comment by piotrdrag** [comment]
I've corrected every .po file directly in Zanata, so it should be fixed with the next pull.

**Comment by vojtechtrefny** [comment]
Thank you. I'll update the po files in git before next release.

**Comment by vojtechtrefny** [comment]
New release 2.6.5 fixes this.
