### ISSUE TITLE
fhs-media configure option

### ISSUE THREAD

**Issue by tgurr** [storaged-project/udisks#220]
In udisks 2.6.4 when specifying --disable-fhs-media the media still gets mounted in /media rather than /run/media. The /run/media behaviour currently seems to be only possible when not passing the fhs-media switch to configure at all which is confusing, both the --enable and --disable configure switch should work.

**Comment by vojtechtrefny** [comment]
Thak you for the report, #223 should fix this.

**Comment by vpodzime** [comment]
> Thank you for the report, #223 should fix this.

Merged.
