### ISSUE TITLE
Udisks does not report sdcards as removable devices

### ISSUE THREAD

**Issue by aruiz** [storaged-project/udisks#236]
udisks does not report sdcards as removable devices:

$ gdbus call --system --dest org.freedesktop.UDisks --object-path /org/freedesktop/UDisks/devices/mmcblk0 --method org.freedesktop.DBus.Properties.Get org.freedesktop.UDisks.Device DeviceIsRemovable
(<false>,)

**Comment by vpodzime** [comment]
The logic is:
```
  if (udisks_drive_get_media_removable (iface) ||
      g_strcmp0 (udisks_drive_get_connection_bus (iface), "usb") == 0 ||
      g_strcmp0 (udisks_drive_get_connection_bus (iface), "sdio") == 0 ||
      g_strcmp0 (udisks_drive_get_connection_bus (iface), "ieee1394") == 0)
    removable_hint = TRUE;
udisks_drive_set_removable (iface, removable_hint);
```
(from https://github.com/storaged-project/udisks/blob/master/src/udiskslinuxdrive.c#L881)

which definitely seems insufficient for many cases.

**Comment by vpodzime** [comment]
Although in this case I'd expect ``udisks_drive_get_media_removable (iface)`` to be ``TRUE`` as the SD card is a removable media. This definitely needs some debugging.

**Comment by aruiz** [comment]
sdio should return true right?

**Comment by vpodzime** [comment]
I think I can see the problem here. :)

> $ gdbus call --system --dest org.freedesktop.UDisks --object-path /org/freedesktop/UDisks/devices/mmcblk0 --method org.freedesktop.DBus.Properties.Get org.freedesktop.UDisks.Device DeviceIsRemovable

This is the very old *UDisks* (1). *udisks2* has a different API and the ``org.freedesktop.UDisks2.Drive.Removable`` property says ``True`` on SD cards just fine. @aruiz, could you please test this with *UDisks2*?

**Comment by aruiz** [comment]
Indeed UDisks2 works fine.

One reason I was using the old Udisk is that there is no way to list devices other than introspecting org.freedesktop.UDisks2 and filtering /block_devices/ paths which is rather ugly. At least from what I can tell in the introspection data in d-feet.

Should I file another bug to request this feature?

**Comment by vpodzime** [comment]
Yes, please file a new RFE for that. Also I think that the client library that wraps the DBus interface has a function like that.
