### ISSUE TITLE
don't do buffered writes to USB sticks, can't cancel copies, misleading UI

### ISSUE THREAD

**Issue by cmurf** [storaged-project/udisks#244]
1. Nautilus, copy a large file (1GiB) to a USB stick that's FAT32 formatted.
2. Within about 2 seconds, the copy status in Nautilus indicates 1GiB of 1GiB is copied, but the status UI hasn't gone away yet, it still has a cancel button.
3. Meanwhile iotop shows the system is still writing to the drive.
4. Click the cancel button in Nautilus and it now says "Cancelled"
5. Back in iotop it's still showing writes happening to the stick, minutes later.
6. Pull the USB stick.

Apr 19 21:58:03 f26h.localdomain kernel: usb 3-1: USB disconnect, device number 6
Apr 19 21:58:03 f26h.localdomain kernel: sd 2:0:0:0: [sda] tag#0 FAILED Result: hostbyte=DID_NO_CONNECT driverbyte=DRIVER_OK
Apr 19 21:58:03 f26h.localdomain kernel: sd 2:0:0:0: [sda] tag#0 CDB: Write(10) 2a 00 00 0a 80 e8 00 00 f0 00
Apr 19 21:58:03 f26h.localdomain kernel: blk_update_request: I/O error, dev sda, sector 688360
Apr 19 21:58:04 f26h.localdomain udisksd[1780]: Cleaning up mount point /run/media/chris/LEXAR (device 8:1 no longer exist)
Apr 19 21:58:04 f26h.localdomain kernel: FAT-fs (sda1): unable to read boot sector to mark fs as dirty

Right.

So maybe the test is something like, if it's USB, and if it's less than 128GiB, and if it's any fat variant, then always use O_DIRECT.

**Comment by cmurf** [comment]
OK, it's actually worse with ext4 and Btrfs. With those, Nautilus instantly says it's copied with a different notification, it has no cancellation, click the X and the notification goes away as if it's really done.

So the "if it's any fat" variant doesn't work; although at least these file systems fix themselves at mount time; it's still unsatisfactory UI to claim it's done when it's got ages to go.

**Comment by vojtechtrefny** [comment]
Hi, this is definitely not an issue for udisks -- it doesn't copy the files or provide progress for copying. Udisks only takes care of mounting the device (in this case). This is a problem somewhere in Nautilus or gvfs.

**Comment by cmurf** [comment]
Filed a bug against Nautilus.
https://bugzilla.gnome.org/show_bug.cgi?id=781775

**Comment by vpodzime** [comment]
> Filed a bug against Nautilus.
> https://bugzilla.gnome.org/show_bug.cgi?id=781775

Thanks!
