### ISSUE TITLE
should run fsck when kernel reports dirty file system, rather than silently rw mount it

### ISSUE THREAD

**Issue by cmurf** [storaged-project/udisks#245]
This starts with #244 where the USB stick is yanked and now it's got the dirty bit set.

When I plug the stick back in: 

Apr 19 22:07:09 f26h.localdomain kernel: usb 3-1: new high-speed USB device number 7 using xhci_hcd
Apr 19 22:07:09 f26h.localdomain kernel: usb 3-1: New USB device found, idVendor=05dc, idProduct=a731
Apr 19 22:07:09 f26h.localdomain kernel: usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Apr 19 22:07:09 f26h.localdomain kernel: usb 3-1: Product: JD FireFly
Apr 19 22:07:09 f26h.localdomain kernel: usb 3-1: Manufacturer: Lexar
Apr 19 22:07:09 f26h.localdomain kernel: usb 3-1: SerialNumber: SXAN8P40ABWAHAL63J5C
Apr 19 22:07:09 f26h.localdomain kernel: usb-storage 3-1:1.0: USB Mass Storage device detected
Apr 19 22:07:09 f26h.localdomain kernel: scsi host2: usb-storage 3-1:1.0
Apr 19 22:07:09 f26h.localdomain mtp-probe[26487]: checking bus 3, device 7: "/sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/0000:02:02.0/0000:37:00.0/usb3/3-1"
Apr 19 22:07:09 f26h.localdomain mtp-probe[26487]: bus: 3, device: 7 was not an MTP device
Apr 19 22:07:11 f26h.localdomain kernel: scsi 2:0:0:0: Direct-Access     Lexar    JD FireFly       1100 PQ: 0 ANSI: 0 CCS
Apr 19 22:07:11 f26h.localdomain kernel: sd 2:0:0:0: Attached scsi generic sg0 type 0
Apr 19 22:07:11 f26h.localdomain kernel: sd 2:0:0:0: [sda] 3915776 512-byte logical blocks: (2.00 GB/1.87 GiB)
Apr 19 22:07:11 f26h.localdomain kernel: sd 2:0:0:0: [sda] Write Protect is off
Apr 19 22:07:11 f26h.localdomain kernel: sd 2:0:0:0: [sda] Mode Sense: 43 00 00 00
Apr 19 22:07:11 f26h.localdomain kernel: sd 2:0:0:0: [sda] No Caching mode page found
Apr 19 22:07:11 f26h.localdomain kernel: sd 2:0:0:0: [sda] Assuming drive cache: write through
Apr 19 22:07:11 f26h.localdomain kernel:  sda: sda1
Apr 19 22:07:11 f26h.localdomain kernel: sd 2:0:0:0: [sda] Attached SCSI removable disk
Apr 19 22:07:11 f26h.localdomain kernel: FAT-fs (sda1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
Apr 19 22:07:11 f26h.localdomain udisksd[1780]: Mounted /dev/sda1 at /run/media/chris/LEXAR on behalf of uid 1000

a. Nautilus doesn't report this possible corruption, so the user has no idea.
b. For while now on UEFI with FAT EFI System partition, fstab uses fs_passno 1 so dosfsck is run against the ESP to fix things up during startup, and this is unattended.

Therefore do the same thing here instead of mounting rw. (Fix it, then rw mount it.)

Or actually, could just pre-emptively do dosfsck -av before even attempting to mount it, and verbosely log the output. Then rw mount.

**Comment by vpodzime** [comment]
> Or actually, could just pre-emptively do dosfsck -av before even attempting to mount it, and verbosely log the output. Then rw mount.

This is not really a good thing to do as it may lead into more data loss than user doing the repair interactively. But what's more important here is that it's the desktop environment doing the mount (e.g. *gvfs* in case of *GNOME*) so it's that what needs to do the check before mounting, not *udisks*.

**Comment by BillDietrich** [comment]
Filed https://gitlab.gnome.org/GNOME/gvfs/issues/443
