### ISSUE TITLE
 Mountpoint folder not automatically deleted when shutting down system

### ISSUE THREAD

**Issue by rieje** [storaged-project/udisks#249]
If I shut down the system without manually unmounting and/or locking an external drive that is LUKS-encrypted, the mountpoint folder will not be removed. For example, if I plug in the drive and it gets mounted to `/media/external_HDD` automatically, then `/media/external_HDD` will not be removed when the drive is not manually unmounted and/or locked (if it is, it gets automatically removed). 

This is important because if the folder is not removed, then the next time the drive gets mounted, it will mount to `/media/external_HDD1` instead. I would have to unmount this mountpoint, and remove both `/media/external_HDD` and `/media/external_HDD1` so mounting back the drive will mount to the correct `/media/external_HDD`.

I assume the system unmounts and locks the HDD safely when shutting down the system, but this mountpoint folder is not deleted (not the system's responsibility, so it makes sense). Is this behavior expected and is there a way to deal with it nicely? 

Or are udisk users simply required to manually dismount the drive in order for the mountpoint folder to be removed? Otherwise, the folder needs to be manually deleted with root permissions.

Thanks.

Also, a workaround I've read was that `/media` can be a tmpfs so any empty mount point folders there get automatically removed on shutdown. However, it seems kind of dangerous data is so close to a tmpfs... seems kind of dirty.

**Comment by vpodzime** [comment]
> Also, a workaround I've read was that /media can be a tmpfs so any empty mount point folders there get automatically removed on shutdown. However, it seems kind of dangerous data is so close to a tmpfs... seems kind of dirty.

*UDisks2* now defaults to mounting to ``/run/media`` which is a *tmpfs* FS unless configured with ``--enable-fhs-media``. Where are you using *udisks* and in which version?

**Comment by vpodzime** [comment]
There's basically no way to remove the created mount point directories on shut down.

**Comment by vojtechtrefny** [comment]
#430 fixed this
