### ISSUE TITLE
UDisksClient API missing ability to Delete MDRaid

### ISSUE THREAD

**Issue by tasleson** [storaged-project/udisks#254]
`udisks_manager_call_mdraid_create` exists which allows a client to create a mdraid.  It would be good to have a method which allows a client to delete one as well.

**Comment by vpodzime** [comment]
It's interesting, that there is a ``Delete`` method on the ``org.freedesktop.UDisks2.MDRaid`` DBus interface, but no such function is in the generated library code while there are functions for other DBus methods.

**Comment by tbzatek** [comment]
Good catch! The C API symbols were all there properly, it was just about API docs.
