### ISSUE TITLE
NVME drives: missing Label field

### ISSUE THREAD

**Issue by mixmastamyk** [storaged-project/udisks#258]
(This is Udisks2, correct?  Not especially clear.)

Using Ubuntu Zesty, with an older than I expected Udisks2:  `2.1.8-1ubuntu1`

Anyway, a few layers of the OS are not able to display the partition volume labels I've set on partitions of NVME drives, even though the system seems to recognize them at some level.  Other `/dev/sd*` type partitions appear to work fine.

Here's a partial dump:

```
/org/freedesktop/UDisks2/block_devices/nvme0n1p2:
  org.freedesktop.UDisks2.Block:
    Configuration:              [('fstab', {'fsname': <b'UUID=ea9a3920-8ce9-462d-847a-a9d9ded69000'>, 'dir': <b'/'>, 'type': <b'ext4'>, 'opts': <b'errors=remount-ro,relatime'>, 'freq': <0>, 'passno': <1>})]
    CryptoBackingDevice:        '/'
    Device:                     /dev/nvme0n1p2
    DeviceNumber:               66306
    Drive:                      '/org/freedesktop/UDisks2/drives/373B52RPKSJU'
    Id:                         by-id-nvme-THNSN5512GPUK_NVMe_TOSHIBA_512GB_373B52RPKSJU-part2
    IdLabel:                    
    IdType:                     ext4
    ReadOnly:                   false
    Size:                       32768000000
    Symlinks:                   /dev/disk/by-id/nvme-...-part2
                                /dev/disk/by-id/nvme-eui.00080d03000fea38-part2
                                /dev/disk/by-partlabel/Ubuntu
```

Note the blank IdLabel field, but the correct symlink path.  

Could very well be an Ubuntu problem in having such an old Udisks2, but wanted to make sure upstream is aware, since I found no NVME related bugs here.

**Comment by vpodzime** [comment]
> (This is Udisks2, correct? Not especially clear.)

Yes, this is UDisks2 upstream.

The labels are read from the *udev* database. So it looks like *udev* itself doesn't recognize/read the label. You could check that using the ``udevadm info`` command. If that's the case, please report the issue to *udev* (and it may then get further to *libbklid*,...).

Thanks for the report anyway!

**Comment by mixmastamyk** [comment]
Hmm, seems to recognize it:

```
⏵ udevadm info /dev/nvme0n1p2 
P: /devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p2
N: nvme0n1p2
S: disk/by-partlabel/Ubuntu
...
E: DEVNAME=/dev/nvme0n1p2
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/0000:03:00.0/nvme/nvme0/nvme0n1/nvme0n1p2
E: DEVTYPE=partition
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_FS_UUID=ea9a3920-8ce9-462d-847a-a9d9ded69000
E: ID_PART_ENTRY_NAME=Ubuntu
E: ID_PART_ENTRY_NUMBER=2
E: ID_PART_TABLE_TYPE=gpt
E: ID_SERIAL=THNSN5512GPUK NVMe TOSHIBA 512GB_373B52RPKSJU
E: MAJOR=259
E: MINOR=2
E: PARTN=2
E: PARTNAME=Ubuntu
E: SUBSYSTEM=block
E: TAGS=:systemd:
```

I did just notice that it is my only GPT partitioned disk, perhaps that is related.  Oh, and my optical disc volume names on `/dev/sr0` appear to work fine also.

**Comment by vojtechtrefny** [comment]
The "IdLabel" property contains only filesystem label. You are looking for partition name -- it is in property `Name` of `org.freedesktop.UDisks2.Partition` interface. (And this happens only on GPT disks because only GPT supports partition names.)

**Comment by mixmastamyk** [comment]
Oh, well *I am looking* for the Label, but perhaps what you are telling me is that the Disks tool labeled the partition instead of the filesystem?  Interesting, will investigate.

**Comment by mixmastamyk** [comment]
Wow, thanks all, that was it.  Turns out it has nothing to do with NVME.

For a long time I avoided EFI stuff on my own laptop, and this is my first computer with a GPT partitioned disk.  Had no idea there was a difference between a partition and filesystem name, and the "Disks" app doesn't give any guidance on the two.  Thanks again.

**Comment by vpodzime** [comment]
> Wow, thanks all, that was it. Turns out it has nothing to do with NVME.

Cool!

> 
> For a long time I avoided EFI stuff on my own laptop, and this is my first computer with a GPT partitioned disk. Had no idea there was a difference between a partition and filesystem name, and the "Disks" app doesn't give any guidance on the two. Thanks again.

Please file an issue for the *Disks* tool about that. If there's a file system on the partition, it should set the FS label instead. If not, it should make it clear that it is setting Partition's name/label.

**Comment by mixmastamyk** [comment]
I've not had a lot of luck writing bugs for gnome (think I'm 0/10) but here goes:

- https://bugzilla.gnome.org/show_bug.cgi?id=782665

**Comment by vpodzime** [comment]
> I've not had a lot of luck getting bugs for gnome taken seriously (think I'm 0/10) but here goes:
> 
>     https://bugzilla.gnome.org/show_bug.cgi?id=782665

Thanks! And welcome to the party ;)
