### ISSUE TITLE
udisksd(8) still has --no-debug

### ISSUE THREAD

**Issue by marcosfrm** [storaged-project/udisks#262]
`--no-debug` was removed (https://github.com/storaged-project/udisks/commit/52367c11f4edac673cf749d230707b04706395b2 and https://github.com/storaged-project/udisks/commit/f639f67aa3f44a4e7e182cff7e6fc7ba5872c94a), but the man page was not updated.

**Comment by vojtechtrefny** [comment]
Thank you, https://github.com/storaged-project/udisks/pull/263 fixes this.

**Comment by marcosfrm** [comment]
Better also add `--debug` there.

**Comment by vojtechtrefny** [comment]
Good idea, I've updated the pull request.

**Comment by marcosfrm** [comment]
Thanks.
