### ISSUE TITLE
RFE: support TrueCrypt encryption

### ISSUE THREAD

**Issue by vpodzime** [storaged-project/udisks#282]
Once [*libblockdev* supports TrueCrypt](https://github.com/rhinstaller/libblockdev/issues/200), *UDisks* should support it too next to LUKS encryption.

**Comment by segfault3** [comment]
Hi, we at [Tails](https://tails.boum.org) plan to work on this in the next months. We track this at https://labs.riseup.net/code/issues/6337. 

I saw that you already implemented the support in libblockdev, which is awesome. Did you already start adding this to udisks, too? And what is the best channel to ask questions which might arrive?

**Comment by vpodzime** [comment]
> Did you already start adding this to udisks, too?

No, not really yet.

**Comment by vpodzime** [comment]
> And what is the best channel to ask questions which might arrive?

Feel free to use this issue.

**Comment by vpodzime** [comment]
Thanks!

**Comment by intrigeri** [comment]
See #495 and storaged-project/libblockdev#320 :)

**Comment by vojtechtrefny** [comment]
#495 is merged now and truecrypt support will be part of the next release.
