### ISSUE TITLE
Support building udisks without MDRAID support

### ISSUE THREAD

**Issue by tgurr** [storaged-project/udisks#288]
```
[...]
checking libblockdev-loop presence... yes
checking libblockdev-swap presence... yes
checking libblockdev-mdraid presence... no
configure: error: BLOCKDEV MDRAID support requested but header or library not found
[...]
```

libblockdev offers the option to disable MDRAID support but udisks-2.7.0 has a hard requirement on it and fails during configure if MDRAID support in libblockdev isn't found. Since some other stuff is optional as well it would be great if MDRAID support could be made optional too.

**Comment by vpodzime** [comment]
I'm afraid this is not possible because the MDRAID support is part of the core API.

**Comment by tbzatek** [comment]
See the recent discussion: https://github.com/storaged-project/udisks/discussions/1314

There are currently no plans to change this.
