### ISSUE TITLE
Wrong translation about RAID

### ISSUE THREAD

**Issue by SergioAtSUSE** [storaged-project/udisks#311]
As you can see on the screenshot, the verb "activar" is used to describe a status.
The text should be "activo" o "activado".

![disks-wrong_translation](https://user-images.githubusercontent.com/25484865/27278614-2225aa20-54e2-11e7-9320-d23804faeea6.jpg)

**Comment by vpodzime** [comment]
Translations are handled in [Zanata](https://fedora.zanata.org/iteration/view/udisks/udisks?dswid=9345)

**Comment by SergioAtSUSE** [comment]
@vpodzime, thanks to point me to the Zanata project.

Sadly I am not able to find that translation. https://fedora.zanata.org/webtrans/translate?project=udisks&iteration=udisks&localeId=es&locale=en-US&dswid=-3270#view:doc;doc:udisks2;search:Activar

Can someone point me how to find it? Is this translation perhaps not part of udisk?

**Comment by vpodzime** [comment]
> Can someone point me how to find it? Is this translation perhaps not part of udisk?

What about https://git.gnome.org/browse/gnome-disk-utility/tree/po ?

**Comment by SergioAtSUSE** [comment]
@vpodzime, yes that it is. Thanks!

**Comment by vpodzime** [comment]
> @vpodzime, yes that it is. Thanks!

No problem. :)
