### ISSUE TITLE
fsadm has changed incompatibly, need to adapt

### ISSUE THREAD

**Issue by mvollmer** [storaged-project/udisks#312]
Storaged uses fsadm indirectly via lvresize when resizing a LVM2 logical volume.  For some filesystem types (and depending on whether the volume shrinks or grows), fsadm needs to unmount the filesystem.

When needing to unmount, fsadm has always prompted the user to confirm this.  However, the behavior has changed incompatibly when stdin is not a tty, which is the case when storaged runs it:

https://sourceware.org/git/?p=lvm2.git;a=commit;h=1fe4f80e45a6bfcceed5aaab97fc0e27dfcf2b88

Thus, fsadm used to unmount the fs, but will now fail.

I think storaged needs to compensate for this somehow and keep its old behavior.

**Comment by mvollmer** [comment]
> I think storaged needs to compensate for this somehow and keep its old behavior.

Or maybe not... My current plan is now for Cockpit to avoid this trap altogether: https://trello.com/c/KmwyB8R2/523-storage-better-resizing-by-better-knowledge

**Comment by vojtechtrefny** [comment]
#327 fixes this

**Comment by vojtechtrefny** [comment]
#327 actually doesn't fix this, because the `--yes` option doesn't work. (This -- https://sourceware.org/git/?p=lvm2.git;a=commit;h=e3f63693a4ea76975fb01f8456f1f263b029b07f -- commit should fix it.)

**Comment by mvollmer** [comment]
> #327 fixes this

Great!  Even if it doesn't work now, it is still the right thing for storaged to do, of course.  Luckily old versions of lvresize already support the "--yes" option.
