### ISSUE TITLE
Create primary partition as last partition on dos label

### ISSUE THREAD

**Issue by squimrel** [storaged-project/udisks#318]
This is currently not possible since `bd_part_create_part` is told to be smart: [src/udiskslinuxpartitiontable.c#L292](https://github.com/storaged-project/udisks/blob/6de468f34593483c7f8480a56a6dd61ddd5bf299/src/udiskslinuxpartitiontable.c#L292). Therefore it'll always try to create an extended partition.
Should the user not be able to specify the partition type?

**Comment by vpodzime** [comment]
Looks like we need to add support for something like ``part-type`` to the ``CreatePartition()``'s ``options`` parameter.

**Comment by squimrel** [comment]
@vpodzime Sounds like a good idea since it doesn't break the API (in terms of backwards compatibility).

**Comment by vpodzime** [comment]
> @vpodzime Sounds like a good idea since it doesn't break the API (in terms of backwards compatibility).

Yeap, that's what I was aiming for.

**Comment by squimrel** [comment]
/me self-assigns this issue.

Sorry I was unavailable until now.
I do question though how the user should know the different between partition type (as in filesystem type) and partition type (primary, extended, logical)?

For example the documentation currently refers to the filesystem type when it mentions "type of partition" which isn't incorrect since it's the type of the partition in some sense but we need to be able to differentiate these two types.

A comment on this naming issue would be appreciated.

**Comment by squimrel** [comment]
By the way it appears that I don't have a use-case for this anymore.

**Comment by vpodzime** [comment]
> A comment on this naming issue would be appreciated.

I think *partition type* should be just fine if we add something like *(primary/extended on MBR/dos, no options on GPT)*.

**Comment by vpodzime** [comment]
> By the way it appears that I don't have a use-case for this anymore (for now). I could still add that option if anyone cares.

That would be great, creating 4 primary partitions is not that uncommon case.

**Comment by vpodzime** [comment]
Resolved with #328
