### ISSUE TITLE
Don't fail if some runtime packages are not present

### ISSUE THREAD

**Issue by bdubbs** [storaged-project/udisks#330]
udisks-2.7.0 fails at runtime if the following are not present:

btrfs-progs
dosfstools
gptfdisk
mdadm
xfsprogs

These were not required in version 2.6.5 and appear to be an artifact of adding a required dependency on libblockdev.  Many of our users have no need for these capabilities and are complaining of bloat.  Please allow the package to continue to work with vanilla ext2/3/4 partitions and fdisk without requiring these capabilities.  

  -- Bruce Dubbs
     linuxfromscratch.org

**Comment by vpodzime** [comment]
This actually hasn't changed much, *udisks* has always relied on having e.g. ``mdadm`` available and ``btrfs-progs`` should only be required for the ``udisks-btrfs`` module which is optional and should be packaged/shipped separately. But I can see your point. 

The file system utilities are strictly required by *libblockdev* now which is definitely wrong and something we have to address. Thanks for the report!

**Comment by RecklessProcedure** [comment]
Thanks for taking the time to allow the clipping off and building without unneeded features and dependency.

**Comment by vpodzime** [comment]
> The file system utilities are strictly required by libblockdev now which is definitely wrong and something we have to address. Thanks for the report!

At least this part should be resolved now with *libblockdev-2.10* and newer.
