### ISSUE TITLE
Regression on udisks2 2.7.0. : Mount syscall failed: 13

### ISSUE THREAD

**Issue by geplus** [storaged-project/udisks#334]
Hi,
In these links there are the details of the issue:
https://forum.manjaro.org/t/mount-dvd-error-mount-syscall-failed-13/26750
https://bugs.archlinux.org/task/54644
Of course, I can confirm the issue.
Downgrading to version 2.6.5 fix the problem

**Comment by vpodzime** [comment]
I believe this is related to and resolved by https://github.com/storaged-project/libblockdev/commit/721f4bee9fa74ef4403db238b8745f151303a540. I'm going to do a new release of *libblockdev* today so it should be available for testing soon.

**Comment by vpodzime** [comment]
*libblockdev-2.10* released, please try if the problems persist even with the new version of the library.

**Comment by DeadMetaler** [comment]
@vpodzime   Thanks. Mounting loop devices is fixed for me with   _libblockdev-2.10_

**Comment by vpodzime** [comment]
> @vpodzime Thanks. Mounting loop devices is fixed for me with libblockdev-2.10

Cool, thanks for the confirmation! I'm closing this issue for now, anybody feel free to reopen it if there's a chance it's still not fixed.
