### ISSUE TITLE
UDF: Wrong usage of mkudffs

### ISSUE THREAD

**Issue by pali** [storaged-project/udisks#338]
Look at https://github.com/storaged-project/udisks/blob/master/src/udiskslinuxfsinfo.c#L172
mkudffs is called as:
```
mkudffs --vid $LABEL $DEVICE
```

But label is set via parameter `--lvid`, not only `--vid`. Since mkudffs 1.1 is available also alias parameter `--label` or `-l` which set label. If you want to support mkudffs pre 1.1, then you need to supply also parameter `--blocksize=` with value of logical sector size of device (blockdev --getss).

Also I suggest to specify parameters `--utf8` (means that label is encoded in UTF-8), `--media-type=hd` (formatting hard disk) and `--udfrev=0x201` (use version 2.01).

So correct usage is:
```
mkudffs --utf8 --media-type=hd --udfrev=0x201 --blocksize=`blockdev --getss "$DEVICE"` --lvid="$LABEL" --vid="$LABEL" "$DEVICE"
```

**Comment by pali** [comment]
Also note that according to UDF specification `--lvid` and `--vid` should be non-empty strings, which means label should be defined. If those options are not specified, then mkudffs set them to `LinuxUDF`.

But if you want for any reason want to set empty strings to `--lvid` or `--vid` options (which violates specification), then such empty strings needs to be stored to UDF disk specially, which mkudffs does not support yet. Currently it stores them incorrectly which could cause problems for UDF readers (I have no idea about could happen). Fix for empty strings is ready for mkudffs 1.4, which was not released yet.

So I suggest to exclude `--lvid` and `--vid` options from mkudffs call in case $LABEL is empty to prevent creating invalid file system. mkudffs would set both options to `LinuxUDF`.

**Comment by pali** [comment]
I looked into udisks code and seems that shell backticks in udisks format command are not supported. So calling blockdev is not straightforward as I thought.

Note that with `--utf8` parameter set (must be first!) strings are expected to be encoded in UTF-8 by caller. I'm not sure what applications tends to use now, but it was a good way to respect current LC_CTYPE encoding. Starting with (still unreleased) mkudffs 1.4 default encoding would be based on LC_CTYPE, prior is UTF-8.

And please also note that mkudffs prior to 1.1 has broken `--utf8` support and is able to process only ASCII strings, therefore passing UTF-8 label with older mkudffs version would cause problems (label is truncated at first non-invariant UTF-8 character).

I hope I wrote all problems and needed information for correct fix of UDF.

For inspiration patch which adds UDF support into GParted is there:
https://git.gnome.org/browse/gparted/commit/?id=5f327feb25bcb8b55ffa2eab1bb86d5f75d75fba

**Comment by vpodzime** [comment]
> I looked into udisks code and seems that shell backticks in udisks format command are not supported. So calling blockdev is not straightforward as I thought.

We can definitely get the block size by other means. AFAICT, it should just be a single ``ioctl()``. However, I don't really understand why ``mkudffs`` doesn't get the block size on its own?

**Comment by pali** [comment]
> AFAICT, it should just be a single ioctl()

Yes, `ioctl(fd, BLKSSZGET, &size)`.

> why `mkudffs` doesn't get the block size on its own?

It can, but only since mkudffs 1.1. Prior to 1.1 it sets it to 2048 which create UDF filesystem on HDD incompatible with everything else on the world.

**Comment by vpodzime** [comment]
> It can, but only since mkudffs 1.1. Prior to 1.1 it sets it to 2048 which create UDF filesystem on HDD incompatible with everything else on the world.

That's quite sad. But something we can definitely easily work around with the above ``ioctl()``.

**Comment by vpodzime** [comment]
@pali, plaese take a look at #360

**Comment by pali** [comment]
I added just one note, otherwise looks good.

Another thing which I have not mentioned here yet. --vid can contain maximally 30 Unicode code points below U+FF and only 15 if there is some above U+FF. --lvid (which is used as label) can contain 126 resp. 63.

So in current implementation if LABEL has more then 30 (resp. 15) code points mkudffs throw error and refuse to format disk.

If you are going to handle also this problem and problems with UTF-8 encoding in pre 1.1 versions, you can look for inspiration into gparted code:
https://git.gnome.org/browse/gparted/commit/?id=861bc8df5d65c1df500161fc9904b0285773357c

Gparted truncates --vid to just 30 (resp. 15) code points to allow setting long labels (up to 126 chars).

**Comment by vpodzime** [comment]
This is actually a common problem for the code doing FS formatting in *udisks*. Generally, it needs to check and apply restrictions for labels.

Fixing this (just) for UDF would make the code even more complex. Let's keep things like proposed in #360 for now and deal with label restrictions and related stuff in general in another issue and PR. Does that sound acceptable?

**Comment by pali** [comment]
Yes, #360 is fine, when user specify non-empty ASCII-only label then UDF file system is formatted correctly. When label is long then mkudffs throw error and do nothing.

Special cases like test for non-ASCII label on mkudffs 1.0 or empty label can be added later (if you are planning to implement it), same for long 126 chars labels. I think other filesystem has also limitation of allowed characters, so such checks seems like future request, not as bug.

I'm happy with #360 as in most cases (when user enter non-empty ASCII-only label) all mkudffs versions either format disk correctly or throw error with exit code 1. (I hope that you verify that exit code is 0 and propagate such error). So for me it is enough.

**Comment by vpodzime** [comment]
Great, thanks! :)

**Comment by vpodzime** [comment]
Created #363 in relation to the above discussion/comments.

**Comment by pali** [comment]
Which MBR id and GPT GUID is used when creating new UDF partition? Because for interopability with Windows systems it is needed to use one which is supported by Windows. 0x07 should be used. See for long details: https://serverfault.com/a/829172

**Comment by vpodzime** [comment]
Both ``CreatePartition()`` and ``CreatePartitionAndFormat()`` methods accept the ``partition-type`` optional argument. [1] I think it should be GNOME Disks or something specifying the partition type, not udisks somehow magically deriving it.

[1] http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.PartitionTable.html

**Comment by pali** [comment]
Ok. But if `partion-type` for `CreatePartitionAndFormat()` is optional, then what is default value?

I'm asking because in file `data/org.freedesktop.UDisks2.xml` I found this description:
```
        If the option <parameter>update-partition-type</parameter> is
        set to %TRUE and the object in question is a partition, then
        its type (cf. the #org.freedesktop.UDisks2.Partition:Type
        property) will be set to the <emphasis>natural</emphasis>
        partition type matching @type, if any. For example, if
        formatting a GPT partition with a FAT filesystem, the
        <quote>Microsoft Basic Data</quote> partition type will be
        chosen; similar, if formatting a DOS partition with a Ext4
        filesystem then partition type 0x83 is chosen.
```
Which I understand that for UDF we need correct MBR id and GPT GUID mapping.

Also in file src/udiskslinuxblock.c I found structure partition_types_by_id which contains such mapping. But have not looked at it deeply to check how are used.

**Comment by vpodzime** [comment]
> Also in file src/udiskslinuxblock.c I found structure partition_types_by_id which contains such mapping.

Oh, that's right! We need to update the mapping then. Could you please file a separate issue for it? Thanks!
