### ISSUE TITLE
O_RDWR file descriptor without O_DIRECT | O_SYNC

### ISSUE THREAD

**Issue by squimrel** [storaged-project/udisks#339]
How to get a read/write file descriptor without using `OpenForBenchmark`? Because I don't want to benchmark.

**Comment by vpodzime** [comment]
> How to get a read/write file descriptor without using OpenForBenchmark because I don't want to benchmark?

Using ``open()``? But you'd like to do that not being root, I guess?

**Comment by MartinBriza** [comment]
Yes

**Comment by vpodzime** [comment]
What about ``OpenForRestore()``?

**Comment by MartinBriza** [comment]
We've talked about this a while back. OpenForRestore doesn't allow you to
read the data you've written (or at least it seems it doesn't allow it). If
you make a consecutive OpenForBackup call, you may lose the authentication
so it's necessary to be able to do both these things in one call.

2017-07-12 16:46 GMT+02:00 Vratislav Podzimek <notifications@github.com>:

**Comment by vpodzime** [comment]
Oh, I do recall that now. I think it might be best to just add a generic ``OpenDevice()`` method which would accept something like ``mode`` and ``flags`` as parameters. Does that make sense @squimrel @MartinBriza?

**Comment by squimrel** [comment]
Sounds good to me.

**Comment by squimrel** [comment]
Wait if I have to implement this can you assign me to this issue?

**Comment by vojtechtrefny** [comment]
@squimrel I am already working on this.

**Comment by squimrel** [comment]
@vojtechtrefny++
