### ISSUE TITLE
removal of 'udisks_state_add_loop' breaks gnome shell auto mount function

### ISSUE THREAD

**Issue by djfd** [storaged-project/udisks#356]
Hi,

originlly there was a call to ```udisks_state_add_loop``` routine in udisks manager (see [here](https://github.com/storaged-project/udisks/blob/udisks2/src/udiskslinuxmanager.c#L427))

Now it is missing and gnome shell auto mount stops working because ```should_automount()``` (see [here](https://git.gnome.org/browse/gnome-shell/tree/js/ui/components/automountManager.js?h=gnome-3-24#n161)) is now returning ```false``` as a due of a negative check result [here](https://git.gnome.org/browse/gvfs/tree/monitor/udisks2/gvfsudisks2volume.c?h=gnome-3-24#n468)

So please, any plans to restore the feature? 

*BTW*, there were nothing similar to ```udisks_state_remove/drop_loop```, is it by design?

Thanks

**Comment by vojtechtrefny** [comment]
Thank you for finding this, we have accidentally removed the `udisks_state_add_loop` call when rewriting the code to use libblockdev.

> BTW, there were nothing similar to `udisks_state_remove/drop_loop`, is it by design?

There initially was some code to remove the loop "information" but it has been deleted long time ago -- https://github.com/storaged-project/udisks/commit/c87431f146a50ca7e05d57220f977adcac6d58cc There is a check to remove obsolete entries in the `udisks_state_add_loop` function. And also the information about loop devices is stored in `/run/udisks2/loop` so everything is discarded after shutdown/reboot so I guess there is no need for a special cleanup function.

**Comment by djfd** [comment]
Hi guys,

thank you for all your efforts, but still does not work. I mean gnome auto mount.

I compared your changes with my own, they do look absolutely the same, however ones of mine do work fixing auto mount issue in gnome, unlike yours, sorry

Presumably (not checked) you are doing it too late, after gnome had detected loop device.

Please review your changes once more.

Thanks


```diff
diff -aur src.org/udisks-udisks-2.7.2/src/udiskslinuxmanager.c src/udisks-udisks-2.7.2/src/udiskslinuxmanager.c
--- src.org/udisks-udisks-2.7.2/src/udiskslinuxmanager.c        2017-08-03 20:47:01.000000000 +1000
+++ src/udisks-udisks-2.7.2/src/udiskslinuxmanager.c    2017-08-20 16:45:46.552242018 +1000
@@ -401,6 +401,14 @@
 
   loop_device = g_strdup_printf ("/dev/%s", loop_name);
 
+  udisks_state_add_loop(
+    udisks_daemon_get_state(manager->daemon),
+    loop_device,
+    path,
+    0,
+    caller_uid
+  );
+
   /* Determine the resulting object */
   error = NULL;
   wait_data.loop_device = loop_device;
```

**Comment by vojtechtrefny** [comment]
@djfd Can you please check if #419 fixes this issue for you?

**Comment by djfd** [comment]
@vojtechtrefny 

Sorry, I cannot confirm right now, just cannot get sources compiled.

Tried to apply you patch over master branch and got
```
 udisksdaemon.c:292:29: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ 
[-Werror=format=]
             udisks_warning ("Failed to load the '%s' libblockdev plugin",
```
For this simple case I replaced format specifier as it does not matter for this test, then get a couple of extra errors
```
udisksdaemon.c: In function ‘udisks_daemon_constructed’:
udisksdaemon.c:269:9: error: implicit declaration of function ‘bd_switch_init_checks’ [-Werror=implicit-function-declaration]
   ret = bd_switch_init_checks (FALSE, &error);
         ^~~~~~~~~~~~~~~~~~~~~
udisksdaemon.c:269:9: warning: nested extern declaration of ‘bd_switch_init_checks’ [-Wnested-externs]
In file included from udisksdaemon.c:26:0:
udisksdaemon.c:293:29: error: implicit declaration of function ‘bd_get_plugin_name’; did you mean ‘bd_get_plugin_soname’? [-Werror=implicit-function-declaration]
                             bd_get_plugin_name ((*plugin_p)->name));
                             ^
```

These do look as trivial (at least for me), thus I tried to checkout right from your commit number ```7ff5b7f6e5c25e622ffdce3eeee5fdb6607cb48e```...
Well, first error has gone, but recent two are still here.

Could you please advise or fix the code tree to get it compiled?

BTW. At the [old good] SVN times there was a rule of thumb, that any code in repository must at least compile, at any point of the time. Nowadays it does not apply anymore? Or am I missing something when compiling?

**Comment by djfd** [comment]
**UPD**
I applied your patch over 2.7.3 branch and it works! Thank you!

Also I use a following polkit rule to make life easier, ie. no need to enter passwords for those who is in ```storage``` group
```js
// @ /etc/polkit-1/rules.d/60-automount-storage.rules

polkit.addRule(function(action, subject) {
    var udisks = [
        "org.freedesktop.udisks2.loop-modify-others",
        "org.freedesktop.udisks2.filesystem-mount-system",
    ];

    if (udisks.indexOf(action.id) >= 0 && subject.isInGroup("storage")) {
        return polkit.Result.YES;
    }
});
```
Maybe include that as well? Or is it packagers business, not yours?

And, likely, your teammates are right saying that gnome have to detect later changes in attributes, but honestly their [gnome] team is something like big blue, too slow and unresponsive. Did tried to report a couples of bugs to them but never heard nothing back ))

**Comment by vpodzime** [comment]
> Maybe include that as well? Or is it packagers business, not yours?

Please submit this change as a pull request so that we can discuss it publicly and visibly.

**Comment by vpodzime** [comment]
> And, likely, your teammates are right saying that gnome have to detect later changes in attributes, but honestly their [gnome] team is something like big blue, too slow and unresponsive. Did try to report a couples of bugs to them but never heard nothing back ))

lol :)

**Comment by vojtechtrefny** [comment]
> BTW. At the [old good] SVN times there was a rule of thumb, that any code in repository must at least compile, at any point of the time. Nowadays it does not apply anymore? Or am I missing something when compiling?

You need new libblockdev 2.13, we are using some new functionality from it.
