### ISSUE TITLE
Check and/or apply restrictions for format labels

### ISSUE THREAD

**Issue by vpodzime** [storaged-project/udisks#363]
Formats that support labels always also specify some restrictions for such labels. *udisks* needs to check the labels it is given and either refuse the bad ones or transform them into acceptable ones (truncate, change to upper/lower case,...). This is already being done partially in some cases, but we need a better and more versatile solution.

**Comment by tbzatek** [comment]
I think I've added this test within #1005 by calling `bd_fs_check_label()`
