### ISSUE TITLE
What about old udisks (udisks 1)?

### ISSUE THREAD

**Issue by jsarenik** [storaged-project/udisks#373]
Hi there!

I did not find any clear note pointing to any connection between udisks 1 and 2 apart from the blog article at http://davidz25.blogspot.co.il/2012/03/simpler-faster-better.html

There is no mention of previous version at https://www.freedesktop.org/wiki/Software/udisks/

Is the source code and documentation of the old udisks available somewhere?

Thanks!

**Comment by jsarenik** [comment]
Seems like this repository contains everything since the beginning of udisks development. Closing.

**Comment by jsarenik** [comment]
46da5bcaeecfb0d088a57061a293b43e0d13e45a seems to be the latest udisks1 commit. Am I right?

**Comment by vpodzime** [comment]
> 46da5bc seems to be the latest udisks1 commit. Am I right?

Yes, that looks correct.

**Comment by jsarenik** [comment]
@vpodzime Thanks for feedback!
