### ISSUE TITLE
No Drive.Ata interface for NVME SSDs

### ISSUE THREAD

**Issue by pothos** [storaged-project/udisks#386]
Forwarding this bug from https://bugzilla.gnome.org/show_bug.cgi?id=778906

The model property is empty and there is no Drive.Ata interface for drives like INTEL SSDPEKKF256G7L or Samsung SSD 950 PRO 512GB.

**Comment by stove-panini** [comment]
Hello, I'm one of the reporters on the GNOME Bugzilla incident.  Please let me know if I can offer any more information.

**Comment by boscowitch** [comment]
Dito, Im the original reporter, happy to provide more information too on the samsung model...

**Comment by vpodzime** [comment]
> The model property is empty and there is no Drive.Ata interface for drives like INTEL SSDPEKKF256G7L or Samsung SSD 950 PRO 512GB.

The ``Drive.Model`` property being empty is a bug. But there's no ``Drive.Ata`` interface because NVME simply is not ATA.

**Comment by vpodzime** [comment]
@tasleson, would you mind trying to see what the problem with the ``Drive.Model`` property is? I know you have an NVME disk.

**Comment by pothos** [comment]
Ah, and the SMART related things are part of the ATA interface… That means there is no API yet to get SMART data.

**Comment by boscowitch** [comment]
smartctl /dev/nvme0 -a 
works, so i guess a second case/api  for nvme disks is needed.

**Comment by vpodzime** [comment]
> smartctl /dev/nvme0 -a
> works, so i guess a second case/api for nvme disks is needed.

Yes, but it shouldn't be ``Drive.ATA``, but rather ``Drive.NVME``.

**Comment by tasleson** [comment]
@vpodzime Sure I can look into the NVME property not working, which interface is this property on?

**Comment by vpodzime** [comment]
> @vpodzime Sure I can look into the NVME property not working, which interface is this property on?

[``Drive``](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Drive.html)

**Comment by tasleson** [comment]
@vpodzime Looks to me that this data is derived from the udev db and that the udev db doesn't have what we are looking for.  Udev db dumps of NVME and another box that has a typical SATA disk:

```
P: /devices/pci0000:00/0000:00:1d.0/0000:3e:00.0/nvme/nvme0/nvme0n1
N: nvme0n1
S: disk/by-id/nvme-SAMSUNG_MZVKW512HMJP-000L7_S35BNX0J509280
S: disk/by-id/nvme-eui.002538c571b06a6d
S: disk/by-path/pci-0000:3e:00.0-nvme-1
E: DEVLINKS=/dev/disk/by-path/pci-0000:3e:00.0-nvme-1 /dev/disk/by-id/nvme-SAMSUNG_MZVKW512HMJP-000L7_S35BNX0J509280 /dev/disk/by-id/nvme-eui.002538c571b06a6d
E: DEVNAME=/dev/nvme0n1
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/0000:3e:00.0/nvme/nvme0/nvme0n1
E: DEVTYPE=disk
E: ID_PART_TABLE_TYPE=dos
E: ID_PART_TABLE_UUID=18c29f08
E: ID_PATH=pci-0000:3e:00.0-nvme-1
E: ID_PATH_TAG=pci-0000_3e_00_0-nvme-1
E: ID_SERIAL=SAMSUNG MZVKW512HMJP-000L7_S35BNX0J509280
E: ID_SERIAL_SHORT=S35BNX0J509280
E: ID_WWN=eui.002538c571b06a6d
E: MAJOR=259
E: MINOR=0
E: MPATH_SBIN_PATH=/sbin
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=12280621
```

```
P: /devices/pci0000:00/0000:00:11.0/host0/target0:0:0/0:0:0:0/block/sda
N: sda
W: 43
S: block/8:0
S: disk/by-id/ata-Hitachi_HDS721010CLA332_JP2921HQ08NUDA
S: disk/by-id/scsi-SATA_Hitachi_HDS7210_JP2921HQ08NUDA
S: disk/by-path/pci-0000:00:11.0-scsi-0:0:0:0
S: disk/by-id/wwn-0x5000cca35dc3f11f
E: UDEV_LOG=3
E: DEVPATH=/devices/pci0000:00/0000:00:11.0/host0/target0:0:0/0:0:0:0/block/sda
E: MAJOR=8
E: MINOR=0
E: DEVNAME=/dev/sda
E: DEVTYPE=disk
E: SUBSYSTEM=block
E: ID_ATA=1
E: ID_TYPE=disk
E: ID_BUS=ata
E: ID_MODEL=Hitachi_HDS721010CLA332
E: ID_MODEL_ENC=Hitachi\x20HDS721010CLA332\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
E: ID_REVISION=JP4OA25C
E: ID_SERIAL=Hitachi_HDS721010CLA332_JP2921HQ08NUDA
E: ID_SERIAL_SHORT=JP2921HQ08NUDA
E: ID_ATA_WRITE_CACHE=1
E: ID_ATA_WRITE_CACHE_ENABLED=0
E: ID_ATA_FEATURE_SET_HPA=1
E: ID_ATA_FEATURE_SET_HPA_ENABLED=1
E: ID_ATA_FEATURE_SET_PM=1
E: ID_ATA_FEATURE_SET_PM_ENABLED=1
E: ID_ATA_FEATURE_SET_SECURITY=1
E: ID_ATA_FEATURE_SET_SECURITY_ENABLED=0
E: ID_ATA_FEATURE_SET_SECURITY_ERASE_UNIT_MIN=232
E: ID_ATA_FEATURE_SET_SMART=1
E: ID_ATA_FEATURE_SET_SMART_ENABLED=1
E: ID_ATA_FEATURE_SET_AAM=1
E: ID_ATA_FEATURE_SET_AAM_ENABLED=0
E: ID_ATA_FEATURE_SET_AAM_VENDOR_RECOMMENDED_VALUE=128
E: ID_ATA_FEATURE_SET_AAM_CURRENT_VALUE=254
E: ID_ATA_FEATURE_SET_PUIS=1
E: ID_ATA_FEATURE_SET_PUIS_ENABLED=0
E: ID_ATA_FEATURE_SET_APM=1
E: ID_ATA_FEATURE_SET_APM_ENABLED=0
E: ID_ATA_DOWNLOAD_MICROCODE=1
E: ID_ATA_SATA=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN2=1
E: ID_ATA_SATA_SIGNAL_RATE_GEN1=1
E: ID_ATA_ROTATION_RATE_RPM=7200
E: ID_WWN=0x5000cca35dc3f11f
E: ID_WWN_WITH_EXTENSION=0x5000cca35dc3f11f
E: ID_SCSI_COMPAT=SATA_Hitachi_HDS7210_JP2921HQ08NUDA
E: ID_PATH=pci-0000:00:11.0-scsi-0:0:0:0
E: ID_PART_TABLE_TYPE=dos
E: LVM_SBIN_PATH=/sbin
E: DEVLINKS=/dev/block/8:0 /dev/disk/by-id/ata-Hitachi_HDS721010CLA332_JP2921HQ08NUDA /dev/disk/by-id/scsi-SATA_Hitachi_HDS7210_JP2921HQ08NUDA /dev/disk/by-path/pci-0000:00:11.0-scsi-0:0:0:0 /dev/disk/by-id/wwn-0x5000cca35dc3f11f
E: UDISKS_PRESENTATION_NOPOLICY=0
E: UDISKS_PARTITION_TABLE=1
E: UDISKS_PARTITION_TABLE_SCHEME=mbr
E: UDISKS_PARTITION_TABLE_COUNT=2
E: UDISKS_ATA_SMART_IS_AVAILABLE=1
```

We have some custom code in the function `udisks_linux_drive_update` for mmc ref. (https://github.com/storaged-project/udisks/blob/master/src/udiskslinuxdrive.c#L781), so we could add another check for nvme, however IMHO I think what we should really probably look at is how we can get more information about the NVMe device populated into the udev database as there is much that is missing in comparison.

***Notes: Udev db dump for NVME was on F26, other udev dump from RHEL6***

**Comment by vpodzime** [comment]
Looks like there's not much we can do about this in *udisks* at this moment.

**Comment by sghosh151** [comment]
Is there a tracking bug on udev to include the NVME data?

**Comment by vpodzime** [comment]
> When looking at an actual block device on NVMe - udev reports UDISKS_IGNORE=1. May be that is a place to start?

This only affects the [HintIgnore property](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-property-org-freedesktop-UDisks2-Block.HintIgnore).

**Comment by vpodzime** [comment]
> Is there a tracking bug on udev to include the NVMe data? What data should be there?

I'm not aware of any.

**Comment by hjmallon** [comment]
Hi, what is going on here or needed? I found the description a little confusing. I can look into this probably. Here is the systemd change for ID_MODEL on NVMe

https://github.com/systemd/systemd/commit/e2c2d70ba7cc7497b03c4a377bfb529035540aa7#diff-27a09d9af06c9587b4302de923986a9d

Here is the change for ID_REVISION:

https://github.com/systemd/systemd/commit/2c4370d66c8060de30477cdf6d6ce4db65561599#diff-27a09d9af06c9587b4302de923986a9d

They are both pretty recent but RedHat backported some of the udev NVMe changes to CentOS7 so maybe they will be backported?

**Comment by sl1pkn07** [comment]
Hi

any notice of this?

greetings

**Comment by tbzatek** [comment]
We're currently waiting for the first public release of https://github.com/linux-nvme/libnvme.

**Comment by hjmallon** [comment]
So libnvme rather than smartmontools? I understand that library is preferred over shelling out, but smartmontools has a lot more hardware support.

**Comment by tbzatek** [comment]
> So libnvme rather than smartmontools? I understand that library is preferred over shelling out, but smartmontools has a lot more hardware support.

`smartmontools` is focused on SMART only, `libnvme` is focused on NVMe drive management. You're talking about #433.

**Comment by hjmallon** [comment]
> smartmontools is focused on SMART only, libnvme is focused on NVMe drive management. You're talking about #433.

Correct, sorry :)

**Comment by sl1pkn07** [comment]
@tbzatek libnvme releases 1.0

https://github.com/linux-nvme/libnvme/releases/tag/v1.0
