### ISSUE TITLE
UDISKS_PRESENTATION_NAME no longer works

### ISSUE THREAD

**Issue by mathstuf** [storaged-project/udisks#387]
I have the `UDISKS_PRESENTATION_NAME` udev attribute set, but it no longer gets used as the name of the file placed under `/dev/mapper`. This used to happen. Was the attribute used for this changed?

Using 2.6.5.

**Comment by vojtechtrefny** [comment]
The name of the attribute has been changed to `UDISKS_NAME` (https://github.com/storaged-project/udisks/commit/19b8eb210e96de7713a300b8dac591ddcf48be61).

**Comment by mathstuf** [comment]
Thanks.

That's a really old commit though. Any idea why has it been working through Fedora 25 and changed in Fedora 26 suddenly?

**Comment by vojtechtrefny** [comment]
That's weird. I'll test this a little more with Fedora 25 and 26. Can you copy here the udev rule you are using?

**Comment by mathstuf** [comment]
In Fedora 25 (which works):

```udev
ENV{ID_FS_UUID}=="XXXXXXX", ENV{UDISKS_AUTO}="1", ENV{UDISKS_SYSTEM}="0", ENV{UDISKS_ICON_NAME}="security-high", ENV{UDISKS_SYMBOLIC_ICON_NAME}="security-high-symbolic", ENV{UDISKS_PRESENTATION_NAME}="keys", ENV{UDISKS_PRESENTATION_ICON_NAME}="security-high"
```

…which is actually provided by `storaged-2.6.2-6.fc25.x86_64` and the switch back to `udisk2` is probably what causes the difference.

**Comment by mathstuf** [comment]
On Fedora 27, this still isn't naming the entry correctly in `/dev/mapper`:

```
ENV{ID_FS_UUID}=="XXXXXXXX", ENV{UDISKS_AUTO}="1", ENV{UDISKS_SYSTEM}="0", ENV{UDISKS_ICON_NAME}="security-high", ENV{UDISKS_SYMBOLIC_ICON_NAME}="security-high-symbolic", ENV{UDISKS_NAME}="keys", ENV{UDISKS_PRESENTATION_ICON_NAME}="security-high"
```

I'm using `udisks2-2.7.3-1.fc27.x86_64`.

**Comment by vpodzime** [comment]
> ENV{ID_FS_UUID}=="XXXXXXXX"

Are you sure you are using the UUID of the LUKS format in the above?

**Comment by mathstuf** [comment]
Yes, it matches a) what works on Fedora 25 (using storaged) and b) the `/dev/mapper/luks-XXXXXX` path which does appear now.

**Comment by vojtechtrefny** [comment]
I tested this with both Fedora 25 and 27 and I have different results:

- The `UDISKS_PRESENTATION_NAME` doesn't work for me, I have to use `UDISKS_NAME` on both 25 and 27 to get at least some "visible" result.
- The `/dev/mapper` link was always set to `luks-UUID`, I wasn't able to reproduce the behavior with changing this to the given name.
- Only thing that changed for me was name (and icon) in Nautilus. And this works in both Fedora 25 and 27.

It is possible that I'm doing something wrong but I wasn't able to find any code that should do the /dev/mapper link renaming. What tool do you use to open the luks device -- Nautilus or something else? This definitely looks like something than else was doing this on F25.

**Comment by mathstuf** [comment]
I used to use `cryptsetup` manually: that obviously worked since I basically named it myself. I then started using `udiskie` which did make an entry in `/dev/mapper` following `UDISKS_PRESENTATION_NAME`. Maybe it changed behavior? Is what that is called an argument to the mount request over DBus?

**Comment by vpodzime** [comment]
> Maybe it changed behavior? Is what that is called an argument to the mount request over DBus?

The *Mount()* method has nothing to do with the name under ``/dev/mapper``. That name cannot be specified using the *Unlock()* method at all and it has always used to be the case. However, it is read from the ``/etc/crypttab`` file (if specified there). So maybe you used to have an entry in that file specifying the name?

**Comment by mathstuf** [comment]
Ah, OK. Yes, I have an entry there. Is there a reason it stopped working? It's specified on machines where it did work and now it doesn't.

**Comment by vpodzime** [comment]
> It's specified on machines where it did work and now it doesn't.

So you have an entry in the ``/etc/crypttab`` file for that specific device and udisks is not using the name specified there when unlocking the device? That would be a regression.

**Comment by vojtechtrefny** [comment]
So it was actually bug in our code. We made a change that caused that we didn't read the configuration from /etc/crypttab when opening the device. #445 should fix this (I'll backport the fix to F26 too).

@mathstuf Thank you for helping us with debuging this issue.

**Comment by mathstuf** [comment]
Thanks! (A small typo in your comment, it is #455.)

**Comment by vojtechtrefny** [comment]
New build for F26 with this fix -- https://bodhi.fedoraproject.org/updates/FEDORA-2017-b5196b11f2
