### ISSUE TITLE
[[BUILD 2.7.2]] doc fail without enabled any modules

### ISSUE THREAD

**Issue by Obarun** [storaged-project/udisks#389]
hi,

May be a do a mistake but the compilation fail for me 

> make[3] : on entre dans le répertoire « /home/obarun/Archives/pkgbuild/udisks2/src/udisks-udisks-2.7.2/doc »
Makefile:1158: avertissement : surchargement de la recette pour la cible « udisks2-docs.xml »
Makefile:1057: avertissement : ancienne recette ignorée pour la cible « udisks2-docs.xml »
  DOC   Scanning header files
  DOC   Introspecting gobjects
.libs/udisks2-scan.o: In function `main':
udisks2-scan.c:(.text.startup.main+0x3a): undefined reference to `udisks_block_bcache_get_type'
udisks2-scan.c:(.text.startup.main+0x46): undefined reference to `udisks_block_bcache_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0x52): undefined reference to `udisks_block_bcache_skeleton_get_type'
udisks2-scan.c:(.text.startup.main+0x6a): undefined reference to `udisks_block_lvm2_get_type'
udisks2-scan.c:(.text.startup.main+0x76): undefined reference to `udisks_block_lvm2_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0x82): undefined reference to `udisks_block_lvm2_skeleton_get_type'
udisks2-scan.c:(.text.startup.main+0xa6): undefined reference to `udisks_block_zram_get_type'
udisks2-scan.c:(.text.startup.main+0xb2): undefined reference to `udisks_block_zram_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0xbe): undefined reference to `udisks_block_zram_skeleton_get_type'
udisks2-scan.c:(.text.startup.main+0x17e): undefined reference to `udisks_filesystem_btrfs_get_type'
udisks2-scan.c:(.text.startup.main+0x18a): undefined reference to `udisks_filesystem_btrfs_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0x196): undefined reference to `udisks_filesystem_btrfs_skeleton_get_type'
udisks2-scan.c:(.text.startup.main+0x202): undefined reference to `udisks_linux_block_bcache_get_type'
udisks2-scan.c:(.text.startup.main+0x21a): undefined reference to `udisks_linux_block_lvm2_get_type'
udisks2-scan.c:(.text.startup.main+0x232): undefined reference to `udisks_linux_block_zram_get_type'
udisks2-scan.c:(.text.startup.main+0x262): undefined reference to `udisks_linux_drive_lsm_get_type'
udisks2-scan.c:(.text.startup.main+0x26e): undefined reference to `udisks_linux_drive_lsm_local_get_type'
udisks2-scan.c:(.text.startup.main+0x292): undefined reference to `udisks_linux_filesystem_btrfs_get_type'
udisks2-scan.c:(.text.startup.main+0x2aa): undefined reference to `udisks_linux_iscsi_session_get_type'
udisks2-scan.c:(.text.startup.main+0x2b6): undefined reference to `udisks_linux_iscsi_session_object_get_type'
udisks2-scan.c:(.text.startup.main+0x2c2): undefined reference to `udisks_linux_logical_volume_get_type'
udisks2-scan.c:(.text.startup.main+0x2ce): undefined reference to `udisks_linux_logical_volume_object_get_type'
udisks2-scan.c:(.text.startup.main+0x2e6): undefined reference to `udisks_linux_manager_bcache_get_type'
udisks2-scan.c:(.text.startup.main+0x2f2): undefined reference to `udisks_linux_manager_btrfs_get_type'
udisks2-scan.c:(.text.startup.main+0x30a): undefined reference to `udisks_linux_manager_iscsi_initiator_get_type'
udisks2-scan.c:(.text.startup.main+0x316): undefined reference to `udisks_linux_manager_lsm_get_type'
udisks2-scan.c:(.text.startup.main+0x322): undefined reference to `udisks_linux_manager_lvm2_get_type'
udisks2-scan.c:(.text.startup.main+0x32e): undefined reference to `udisks_linux_manager_zram_get_type'
udisks2-scan.c:(.text.startup.main+0x36a): undefined reference to `udisks_linux_physical_volume_get_type'
udisks2-scan.c:(.text.startup.main+0x38e): undefined reference to `udisks_linux_volume_group_get_type'
udisks2-scan.c:(.text.startup.main+0x39a): undefined reference to `udisks_linux_volume_group_object_get_type'
udisks2-scan.c:(.text.startup.main+0x3a6): undefined reference to `udisks_logical_volume_get_type'
udisks2-scan.c:(.text.startup.main+0x3b2): undefined reference to `udisks_logical_volume_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0x3be): undefined reference to `udisks_logical_volume_skeleton_get_type'
udisks2-scan.c:(.text.startup.main+0x3ee): undefined reference to `udisks_manager_bcache_get_type'
udisks2-scan.c:(.text.startup.main+0x3fa): undefined reference to `udisks_manager_bcache_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0x406): undefined reference to `udisks_manager_bcache_skeleton_get_type'
udisks2-scan.c:(.text.startup.main+0x412): undefined reference to `udisks_manager_btrfs_get_type'
udisks2-scan.c:(.text.startup.main+0x41e): undefined reference to `udisks_manager_btrfs_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0x42a): undefined reference to `udisks_manager_btrfs_skeleton_get_type'
udisks2-scan.c:(.text.startup.main+0x442): undefined reference to `udisks_manager_lvm2_get_type'
udisks2-scan.c:(.text.startup.main+0x44e): undefined reference to `udisks_manager_lvm2_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0x45a): undefined reference to `udisks_manager_lvm2_skeleton_get_type'
udisks2-scan.c:(.text.startup.main+0x47e): undefined reference to `udisks_manager_zram_get_type'
udisks2-scan.c:(.text.startup.main+0x48a): undefined reference to `udisks_manager_zram_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0x496): undefined reference to `udisks_manager_zram_skeleton_get_type'
udisks2-scan.c:(.text.startup.main+0x592): undefined reference to `udisks_physical_volume_get_type'
udisks2-scan.c:(.text.startup.main+0x59e): undefined reference to `udisks_physical_volume_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0x5aa): undefined reference to `udisks_physical_volume_skeleton_get_type'
udisks2-scan.c:(.text.startup.main+0x616): undefined reference to `udisks_volume_group_get_type'
udisks2-scan.c:(.text.startup.main+0x622): undefined reference to `udisks_volume_group_proxy_get_type'
udisks2-scan.c:(.text.startup.main+0x62e): undefined reference to `udisks_volume_group_skeleton_get_type'
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/usr/bin/gtkdoc-scangobj", line 71, in <module>
    sys.exit(scangobj.run(options))
  File "/usr/share/gtk-doc/python/gtkdoc/scangobj.py", line 1264, in run
    res = subprocess.check_call(command, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/bin/sh ../libtool --tag=CC --mode=link gcc -lgobject-2.0 -lglib-2.0  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wall -W -Wextra -Wcast-align -Wdeclaration-after-statement -Wendif-labels -Werror=format-security -Werror=implicit-function-declaration -Werror=overflow -Wformat-nonliteral -Wformat=2 -Wimplicit -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wno-inline -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-switch-enum -Wno-unused-parameter -Wno-unused-result -Wold-style-definition -Wpacked -Wpointer-arith -Wshadow -Wsign-compare -Wstrict-aliasing=2 -Wstrict-prototypes -Wundef -Wuninitialized -Wmaybe-uninitialized -Wunsafe-loop-optimizations -Wvla -Wwrite-strings -fdata-sections -fdiagnostics-show-option -ffast-math -ffunction-sections -fno-common -fno-strict-aliasing -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Wl,-O1,--sort-common,--as-needed,-z,relro >/dev/null udisks2-scan.lo -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 ../udisks/libudisks2.la ../src/libudisks-daemon.la        -Wl,-O1,--sort-common,--as-needed,-z,relro -o udisks2-scan' returned non-zero exit status 1.

this is how i configure it :

> ./autogen.sh 	--prefix=/usr \
				--sysconfdir=/etc \
				--sbindir=/usr/bin \
				--libexecdir=/usr/lib \
				--localstatedir=/var \
				--disable-static \
				--with-systemdsystemunitdir=no 

this is the list of dependencies installed for the build:

> 'docbook-xsl' 'gobject-introspection' 'gnome-common' 'intltool' 'parted' 'libiscsi' 'which' 'gettext'

maybe i forgot something?

Build made under Arch based system, up to date.

**Comment by vojtechtrefny** [comment]
This is really strange. I've tried this on clean Fedora VM and on a Debian VM and both works. Can you please paste somewhere full output of the autogen command (with english locale please)?



>> 'docbook-xsl' 'gobject-introspection' 'gnome-common' 'intltool' 'parted' 'libiscsi' 'which' 'gettext'

> maybe i forgot something?

`gtk-doc` is missing, but configure should check for that.

**Comment by Obarun** [comment]
here the autogen output : https://bpaste.net/show/d8e4d2d5e5c2
note : adding gtk-doc don't change anything.

**Comment by Obarun** [comment]
i found the trouble, fedora build the release with gtk-doc  gtk-doc.x86_64 1.25-2.fc25  , see here https://copr-be.cloud.fedoraproject.org/results/%40storage/udisks-daily/fedora-25-x86_64/00586519-udisks2/builder-live.log. 
Downgrading the version on my system with the same version (1.25) the build go smoothly and successfully.
If i use the last gtk-doc version it's mean 1.26 (commit=01844e70cae73bfc95a7746fd958c1756a62c340) the build crash.

So....

**Comment by vojtechtrefny** [comment]
@Obarun #397 should fix this issue.

**Comment by Obarun** [comment]
Works for me too, thanks @vojtechtrefny
