### ISSUE TITLE
udisksd consumes an extra 20MB of memory per day.

### ISSUE THREAD

**Issue by hussamT** [storaged-project/udisks#396]
For some reason, every 24 hours, udisksd memory usage as measured by gnome-system-monitor increases by around 20MB.

udisksctl dump output https://pastebin.com/raw/j0dyUjWq
udevadm info --export-db output https://pastebin.com/raw/vUMMWQyS
 /proc/self/mountinfo https://pastebin.com/raw/BUehNDE4

I saw this with udisksd 2.7.2 so I installed the latest udisksd from git master branch and the same issue happens.

gvfs is 1.33.91.

**Comment by hussamT** [comment]
valgrind log https://pastebin.com/raw/hPUsFhgC

**Comment by vpodzime** [comment]
Thanks for the report! We need to take a look at this, 20 MiB per day is a lot!

**Comment by hussamT** [comment]
Thank you. If you need any more information about my system, let me know please.
For now, 
/dev/sda1 is /boot
/dev/sda3 is root partition luks encrypted -> /dev/mapper/root
/dev/mapper/swap is luks encrypted swap (/dev/sda2)
/dev/sdb1 another internal sata disk luks encrypted -> /dev/mapper/cache. I use this one to store random things like source code trees mounted to /home/hussam/cache.

**Comment by hussamT** [comment]
I don't know yet if it is increasing at regular intervals or something that happens randomly yet frequently is causing udisksd to do this. What would be the best way to find clues?
The 20MB/per day reading seems accurate though. After 32 hours, it is up to 33.5MB. It started at 3.2MB.

**Comment by vpodzime** [comment]
> What would be the best way to find clues?

I'm thinking about adding some memory consumption logging to *udisks2*. It's now logging some of the actions it's doing (like updating SMART information for disks, etc.). So if it also added info about current memory footprint, it should be possible to see if it grows in correlation to that or not.

**Comment by hussamT** [comment]
I just patched my glibc with the patch in this bug https://sourceware.org/bugzilla/show_bug.cgi?id=22111#add_comment 
With any luck, I may just be getting bitten that glibc leak.
I'll reboot now and report on Tuesday if this mitigates the leak in udisksd.

**Comment by hussamT** [comment]
It started with 3.3MB and ended up at 3.5MB. I think it is safe to say that glibc was the root cause of this particular leak.

**Comment by vpodzime** [comment]
> It started with 3.3MB and ended up at 3.5MB. I think it is safe to say that glibc was the root cause of this particular leak.

Great, thanks for the update! I'm closing this issue now, feel free to reopen it if you encounter the memory issues again.
