### ISSUE TITLE
Resize/Repair job progress indication and cancelation

### ISSUE THREAD

**Issue by pothos** [storaged-project/udisks#402]
The Progress property of the job object is not used for resize and repair jobs. Also canceling jobs is not possible with the current libblockdev function calls. Maybe there needs to be another set of generic resize/repair/check functions which handles this (needs parsing of the utility's stdout and process killing).

**Comment by vpodzime** [comment]
Some of the *libblockdev* functions actually provide progress indication (e.g. ``bd_lvm_pvmove()``). It should be fairly easy to add progress reporting to FS operations.

As for cancellation, the situation is a bit more complicated as there's no existing implementation for anything like that in *libblockdev* now. However, the following would be easy to implement:

1. add an internal mapping between libblockdev's *tasks* and internal structs allowing the respective task to be canceled

2. add a function to cancel a task like ``bd_exec_cancel_task()`` to *libbd_utils*.

**Comment by pothos** [comment]
Unfortunately it does not seem easy to use the progress indication as it is because multiple jobs can be running at the same time. A global callback needs to be registered which maps libblockdev's internal task IDs to UDisks jobs. But getting the task ID from libblockdev needs a lot of API changes. A workaround would be to query the task IDs from UDisks before the operation in libblockdev starts and infer that the next one but this is still racing if two jobs are started, right? Any ideas? How about thread-local reporting functions in libblockdev?

FIY: I tried to use a closure (C nested function, a GCC extension) instead of a global callback, but this would result in parallel tasks overwriting the callback.
Here the code which needs to be executed in the callback:
```
if (!udisks_job_get_progress_valid (UDISKS_JOB (job)))
      udisks_job_set_progress_valid (UDISKS_JOB (job), TRUE);

    udisks_job_set_progress (UDISKS_JOB (job), completion / 100.0);

```

**Comment by pothos** [comment]
Went for thread local reporting in https://github.com/storaged-project/udisks/pull/531

**Comment by vpodzime** [comment]
> Went for thread local reporting in #531

Merged. I believe this can be closed now.
