### ISSUE TITLE
Please allow mounting read-only filesystems with less restrictive permissions

### ISSUE THREAD

**Issue by io7m** [storaged-project/udisks#413]
I've been searching for around an hour trying to determine how to have a CDROM be automatically mounted in a directory that everyone on the system can read. By using a udev rule found on the Arch Linux wiki, I now at least have the filesystem mounting in `/media` instead of `/run/media/$USER/`. However, the device is mounted with a file mode of `0400` and a directory mode of `0500`. As far as I can tell, this is hardcoded and not configurable:

https://github.com/storaged-project/udisks/blob/5ed1d6eb0cf8e030854a71e9069a17eca3536bab/src/udiskslinuxfilesystem.c#L306

This would appear to make the `UDISKS_FILESYSTEM_SHARED` option pointless: Why would I bother to have a filesystem mounted in a shared directory if I can't make that filesystem accessible to anyone other than the owner?

A comment further down the file:

https://github.com/storaged-project/udisks/blob/5ed1d6eb0cf8e030854a71e9069a17eca3536bab/src/udiskslinuxfilesystem.c#L717

> always prepend some reasonable default mount options; these are
> chosen here; the user can override them if he wants to

Where can the user override them? This doesn't appear to be specified in any configuration file `udisksd` knows about, and isn't documented anywhere that I can see.

**Comment by vpodzime** [comment]
> This would appear to make the UDISKS_FILESYSTEM_SHARED option pointless: Why would I bother to have a filesystem mounted in a shared directory if I can't make that filesystem accessible to anyone other than the owner?

It makes a lot of sense for filesystems that support file permissions (stored with the files not specified as mount options).
