### ISSUE TITLE
mkfs.vfat fails when not specifying a partition label

### ISSUE THREAD

**Issue by genodeftest** [storaged-project/udisks#414]
Steps to reproduce:
1. open gnome-disks
2. insert any device capable of hosting a FAT partition
3. use gnome-disks to create FAT partition. Do not specify a name.

What happens:
udisksd calls `mkfs.vfat -I -n  /dev/sdb1`, putting in no name. This way, mkfs.vfat gets confused about the command line argument and interprets "/dev/sdb1" as label. Thus, it fails with an error because the device name is missing:
```
$ mkfs.vfat -I -n /dev/sdb1
mkfs.fat 4.1 (2017-01-24)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
No device specified.
Usage: mkfs.fat [-a][-A][-c][-C][-v][-I][-l bad-block-file][-b backup-boot-sector]
       [-m boot-msg-file][-n volume-name][-i volume-id]
       [-s sectors-per-cluster][-S logical-sector-size][-f number-of-FATs]
       [-h hidden-sectors][-F fat-size][-r root-dir-entries][-R reserved-sectors]
       [-M FAT-media-byte][-D drive_number]
       [--invariant]
       [--help]
       /dev/name [blocks]
```

**Comment by genodeftest** [comment]
Workaround: Do not allow empty labels at all.

Fix: Invoke different command line when no label is specified.

**Comment by vojtechtrefny** [comment]
What version of udisks and GNOME Disks are you using? I've just tested this with different versions of udisks and I wasn't able to reproduce this bug.

Udisks should actually call `mkfs.vfat -I -n "" /dev/sdb1` if you don't specify label. (This is not a good way to do it, but it works.)

**Comment by genodeftest** [comment]
> What version of udisks and GNOME Disks are you using? I've just tested this with different versions of udisks and I wasn't able to reproduce this bug.

udisks2-2.6.5-3.fc26.x86_64
gnome-disk-utility-3.24.1-1.fc26.x86_64
glib2-2.52.3-1.fc26.x86_64
gvfs-1.32.1-2.fc26.x86_64

**Comment by vojtechtrefny** [comment]
I've tried this with a clean Fedora 26 installation and still wasn't able to reproduce this issues. Are you using some special shell (for root account) or locales?

**Comment by genodeftest** [comment]
My shell is bash and my locale is de_DE. Is that what you wanted to know?

**Comment by vojtechtrefny** [comment]
I've tried this again with a clean installation of Fedora 26 with German locale and I still wasn't able to reproduce this issue. I was adding a new partition on an empty USB flash drive. Please take a look at the screenshot below -- is this the situation where you see the error? Are you doing something different?

https://vtrefny.fedorapeople.org/misc/gnome-disks-vfat-german.png

**Comment by genodeftest** [comment]
The situation was like yours in the screenshot. I cannot reproduce either and I don't know why. Sorry for wasting your time.

**Comment by vpodzime** [comment]
> The situation was like yours in the screenshot. I cannot reproduce either and I don't know why. Sorry for wasting your time.

No worries. Thanks for your time trying to reproduce/verify this again!
