### ISSUE TITLE
SetFlags() method may reset the partition type

### ISSUE THREAD

**Issue by intrigeri** [storaged-project/udisks#418]
Hi!

The SetFlags() method sometimes resets the type of the partition it's called on. I don't know if it's on purpose and I could not find anything about it in DevHelp. The integration test I'm adding is based on #416, that adds a test case I'm extending here.

**Comment by vojtechtrefny** [comment]
Thank you for the report (and the test too). The problem is actually in libblockdev, this -- https://github.com/storaged-project/libblockdev/pull/306 -- should fix it.

**Comment by intrigeri** [comment]
Great! Thanks for investigating, identifying the root cause and proposing a fix :)

**Comment by vojtechtrefny** [comment]
libblockdev change is merged and the test is passing -- #464 -- so I guess we can close this.
