### ISSUE TITLE
Libatasmart vs smartctl

### ISSUE THREAD

**Issue by bhack** [storaged-project/udisks#433]
libatasmart is quite unmaintained but has some advantage to be structured as a library and to has a quite parsable output.
Need we to incomrporate something from smartctl source files to maintain libatasmart in an updated status? See https://github.com/storaged-project/udisks/issues/423#issuecomment-339954239

**Comment by stikonas** [comment]
smartctl can produce json output. That should be parsable too.

**Comment by vpodzime** [comment]
> smartctl can produce json output. That should be parsable too.

Since which version? My *smartctl* on Fedora 27 (smartmontools-6.5-5) doesn't really look like it could do so.

**Comment by stikonas** [comment]
@vpodzime "since trunk". We'll be released with 6.7. We are already using it in kpmcore git.

**Comment by bhack** [comment]
https://www.smartmontools.org/ticket/766

**Comment by vpodzime** [comment]
Then I'm afraid it's not a real option for udisks now. Patches adding it as an alternative source of SMART data are of course welcome, though. :wink:

**Comment by hjmallon** [comment]
SMART data is currently available on udisks2 API under [UDisks2.Drive.Ata](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Drive.Ata.html). Smartmontools supports retrieving SMART data from other types of disks too (e.g. NVMe and USB SAT). How would the API be changed to make that work?

Also smartmontools 7.0 is out with JSON output.

**Comment by vpodzime** [comment]
> How would the API be changed to make that work?

I think it would make most sense to add a new interface `UDisks2.Drive.SMART`.

> Also smartmontools 7.0 is out with JSON output.

That's great news!

**Comment by fenio** [comment]
What's the current status of that? Is Udisks2.Drive.SMART support on a roadmap?

**Comment by cTurtle98** [comment]
any updates? I am still unable to test nvme drives with gnome-disks-utility on kubuntu 20.04 LTS

**Comment by tbzatek** [comment]
No news since my last post. No contribution from the community either.

**Comment by stikonas** [comment]
Note that just switching to smartctl wouldn't automatically fix nvme drives. smartctl has a different json fields when you have nvme, so you still have to implement nvme support separately. But at least it should be possible

**Comment by tbzatek** [comment]
> Note that just switching to smartctl wouldn't automatically fix nvme drives. smartctl has a different json fields when you have nvme, so you still have to implement nvme support separately. But at least it should be possible

Of course, that's how the new `libblockdev` layer abstraction would be designed. Actual presentation on UDisks side is a separate thing.

There's a native NVMe support planned through `libnvme` that would also provide reading SMART data. The `libblockdev` plugin priority will handle the actual backend selection seamlessly.

**Comment by xgiovio** [comment]
any news on this?

**Comment by tbzatek** [comment]
> any news on this?

No progress on `smartmontools` integration, not on a short-term roadmap for the moment.

However I'm working on NVMe support right now which will provide drive health information among other stuff.

**Comment by xgiovio** [comment]
Thank you.

**Comment by Leeo97one** [comment]
> However I'm working on NVMe support right now which will provide drive health information among other stuff.

Any progress?

**Comment by bhack** [comment]
Check also https://github.com/smartmontools/smartmontools/issues/133

**Comment by tbzatek** [comment]
> > However I'm working on NVMe support right now which will provide drive health information among other stuff.
> 
> Any progress?

Yes, please see #975. If you have any comments and suggestions for the new API, feel free to post comments in that pull request.

**Comment by tbzatek** [comment]
> Check also [smartmontools/smartmontools#133](https://github.com/smartmontools/smartmontools/issues/133)

Oh nice, thanks. I'll keep that on my watch list.

One thing I was thinking about was SAS drive support in the new `smart` `libblockdev` plugin (likely `libblockdev-3.1` and `udisks-2.11+`). With NVMe being covered natively through `libnvme`, this separate plugin would focus to IDE/SATA/SAS only.
