### ISSUE TITLE
udisks_client_get_id_for_display issues

### ISSUE THREAD

**Issue by jonnygrant** [storaged-project/udisks#444]
Copying from here
https://gitlab.gnome.org/GNOME/nautilus/issues/98#note_8380

Had a quick look at udisks_client_get_id_for_display function.
Lots of possible issues..

 https://github.com/storaged-project/udisks/blob/master/udisks/udisksclient.c#L1948

It has goto, which is nearly always bad.
None of the 4 pointers passed are checked for non-NULL: client, usage, type, version
strlen(version) will crash if called on NULL.
Braces are missing in various places. eg

if (long_string)
                ret = g_strdup_printf (g_dpgettext2 (GETTEXT_PACKAGE, "fs-type", id_type[n].long_name), version);
              else
                ret = g_strdup_printf (g_dpgettext2 (GETTEXT_PACKAGE, "fs-type", id_type[n].short_name), version);
              goto out;

^ the lack of new line before the goto makes control flow not immediately obvious. Although of course we know it will always be executed.

5.
BTW, on MBR partition table, this can also be exFAT

line 2314
{"dos", "microsoft", "0x07",  NC_("part-type", "HPFS/NTFS"), 0},

Can it be changed to "NTFS/exFat/HPFS"

Latest fdisk already includes this fix, I reported it there around 5 years ago...

line 2329 doesn't need this url, http://en.wikipedia.org/wiki/MINIX_file_system  can it be removed?

**Comment by vojtechtrefny** [comment]
I fixed the partition type for the 0x07 id and the potential NULL "input" problem in #454

I think we don't need to remove the wikipedia link -- it's just a comment and it might be useful someday. And I also don't plan to remove the `goto out` statement -- it is used in all udisks function and I think it would be more confusing to change it just for one function.

**Comment by vpodzime** [comment]
> And I also don't plan to remove the goto out statement -- it is used in all udisks function and I think it would be more confusing to change it just for one function.

Patches removing ``goto`` from all the places in udisks are definitely more than welcome. Well, as long as they really make the code better.

**Comment by jonnygrant** [comment]
I think anyone can find a minix web link if needed right? Why is it in a source code file?

Thank you for making the updates.

Which line are the NULL ptr checks? I could only see this, which also crashes. strlen() only works on a valid pointer.

if ((id_type[n].version == NULL && strlen (version) == 0))

should be checking for empty strings too.

if((NULL == usage) || (NULL == type) || (NULL == version))
{
    goto out;
}

#define NUL '\0'

if((NUL == usage[0]) || (NUL == type[0]) || (NUL == version[0]))
{
    goto out;
}

I saw many other matching NULL ptr de-reference issues, can they all be checked?

**Comment by vpodzime** [comment]
> Which line are the NULL ptr checks? I could only see this, which also crashes. strlen() only works on a valid pointer.
> 
> if ((id_type[n].version == NULL && strlen (version) == 0))

This line is after the line were ``version`` is checked for not being NULL. So it seems safe to me.

**Comment by vpodzime** [comment]
> should be checking for empty strings too.

All the relevant places seem to be using ``strlen(version) > 0`` or similar which is equivalent to:
```
#define NUL '\0'

if (NUL == version[0])
```

**Comment by jonnygrant** [comment]
I'm looking at the file, but I can't see any changes that you are mentioning...

https://github.com/storaged-project/udisks/blob/master/udisks/udisksclient.c

Which line number are you referring to? can't see any changes to udisks_client_get_id_for_display

Likewise for the strlen(version) > 0, can you tell me which line please?

**Comment by vojtechtrefny** [comment]
The changes are not merged yet -- https://github.com/storaged-project/udisks/pull/454

**Comment by jonnygrant** [comment]
Would be good if there was a way that regular windows NTFS discs could be reported as such, currently they only show up as "fuse" (Filesystem in Userspace)

**Comment by vpodzime** [comment]
> Would be good if there was a way that regular windows NTFS discs could be reported as such, currently they only show up as "fuse" (Filesystem in Userspace)

Please create a separate issue here at GH for this.

**Comment by vpodzime** [comment]
I'm closing this issue now as the major change required here is merged now. Please feel free to create separate issues for the other things mentioned above if you consider them worth doing so.

**Comment by jonnygrant** [comment]
if (usage == NULL || type == NULL || version == NULL)
    {
      g_critical ("Invalid device ID specification. Usage, type and version must not be NULL");
      goto out;
    }

While the change is good, it doesn't follow regular coding standards to pass static analysis. NULL should be on the left of the check, and the checks should be in parenthesis. Also should check "client".

Recommended:
if ((NULL == client) || (NULL == usage) || (NULL == type) || (NULL == version))
    {
      g_critical ("Invalid device ID specification. Client, usage, type and version must not be NULL");
      goto out;
    }
