### ISSUE TITLE
Fourth primary partition can not be created

### ISSUE THREAD

**Issue by pothos** [storaged-project/udisks#446]
Regardless of the given type argument it is not possible to create a fourth primary partition because it will instead be an extended partition (and within it a partition of the requested size is created).

**Comment by vojtechtrefny** [comment]
That's weird. We have a test for that (I changed it so it actually checks if the new partitions are primary -- #449 -- but it seems to be working). I tested it manually too (with GNOME Disks) and I was able to create 4 primary partitions.

On what version of udisks and libblockdev do you see this?

**Comment by pothos** [comment]
I haven't checked the source code yet to find where it happens, running UDisks 2.7.4-1 and libblockdev 2.14-2 on Debian sid but this was also reported some months ago by oholy. Will try again on UDisks/lbd master.

**Comment by pothos** [comment]
Ah, now I see. The default behavior has changed and `BD_PART_TYPE_REQ_NEXT` will be used if partition-type is omitted.

This here works:
`gdbus call --system --dest org.freedesktop.UDisks2 --object-path /org/freedesktop/UDisks2/block_devices/loop0 --method org.freedesktop.UDisks2.PartitionTable.CreatePartition 800000000 200000000 "0xc" "" "{'partition-type': <'primary'>}"`

While this creates two partitions, extended+logicial
`gdbus call --system --dest org.freedesktop.UDisks2 --object-path /org/freedesktop/UDisks2/block_devices/loop0 --method org.freedesktop.UDisks2.PartitionTable.CreatePartition 800000000 200000000 "0xc" "" "{}"`

**Comment by vpodzime** [comment]
> Ah, now I see. The default behavior has changed and BD_PART_TYPE_REQ_NEXT will be used if partition-type is omitted.

I must say I like this behavior. Do you find it problematic? I know it's a change in behavior, but for the better, I'd say. If nothing else, it makes UDisks2 behave more like the other partitioning tools do.

**Comment by pothos** [comment]
It's a bit more work to specify whether it is a logical, primary or extended partition ;) Will fix it in GNOME Disks which did not pass `partition-type` yet…

**Comment by vpodzime** [comment]
> Will fix it in GNOME Disks which did not pass partition-type yet…

Thanks!
