### ISSUE TITLE
Issue when I enabled the single module of libstoragemgmt on release storage-2.5.2

### ISSUE THREAD

**Issue by xhe123** [storaged-project/udisks#451]
**Questions 1** 
I tried to enable the single module of libstoragemgmt on the RHEL-7.4, I found the I can NOT enable it with this command `./configure --enable-libstoragemgmt ` , the cppflags always shows `LibStorageMgmt module:      no` . Is it the expected result? or issue? Thanks!

```
        cppflags:                   

        Maintainer mode:            no
        Building api docs:          no
        Building man pages:         yes

        BTRFS module:               no
        Dummy module:               no
        iSCSI module:               no
        LVM2  module:               no
        LVMCache:                   no
        Zram module:                no
        LibStorageMgmt module:      no         <--------see here 
        Bcache module:              no
```
**Questions 2** 
The release storage-2.5.2 doesn't have the dbus-test, do you mind to tell what testing did you run on the old release (except the install-storaged and integration-test)? 
```
# ls /tmp/storaged/udisks/src/tests/
helper.c          integration-test  Makefile.am  storadectl     storaged-test-helper  test_polkitd.py  testutil.h
install-storaged  Makefile          Makefile.in  storaged-test  test.c                testutil.c
```

**Comment by xhe123** [comment]
The warning seems the module name is unrecognized, what name should I specify for LibStorageMgmt module? 

```
configure: WARNING: unrecognized options: --enable-libstoragemgmt
configure: WARNING: unrecognized options: --enable-libstoragemgmt
```

**Comment by vojtechtrefny** [comment]
The module is called `lsm` so you need to use `--enable-lsm` to enable it.

**Comment by vpodzime** [comment]
This has been clarified.
