### ISSUE TITLE
Add a property with object path of the LUKS device to Encrypted interface

### ISSUE THREAD

**Issue by vojtechtrefny** [storaged-project/udisks#456]
It's quite hard to get object path of an unlocked LUKS device, we should add a property to the `Encrypted` interface pointing to the LUKS device. (Similar to the exisintg `CryptoBackingDevice` property of the `Block` interface pointing "back" from the LUKS device to the underlying block device.)

**Comment by sampablokuper** [comment]
Possible related: #475.
