### ISSUE TITLE
Nautilus shows NTFS discs as fuse

### ISSUE THREAD

**Issue by jonnygrant** [storaged-project/udisks#462]
Would be good if there was a way that regular windows NTFS discs could be reported as such, currently they only show up as "fuse" (Filesystem in Userspace).

Cant his be done?

**Comment by vojtechtrefny** [comment]
I assume you are talking about the [Properties dialog in Nautilus](https://user-images.githubusercontent.com/5063197/76418100-52999180-639e-11ea-93bb-2220c12efbf4.png). The filesystem type here is not from UDisks, GLib [uses statfs()](https://gitlab.gnome.org/GNOME/glib/-/blob/master/gio/glocalfile.c#L556) to get the information so this should be reported against either Nautilus or GLib. But I don't think they will be open to use something more complicated and statfs will always report "fuse" for FUSE filesystems.
