### ISSUE TITLE
Add DBus tests for the ``no-discard`` option

### ISSUE THREAD

**Issue by vpodzime** [storaged-project/udisks#466]
And ideally try to make sure that no new tests are added to the ``integration-test`` file instead of the DBus tests.

See also: #459

**Comment by mvollmer** [comment]
Whoops, I misunderstood where you wanted me to add the test, sorry.

**Comment by vpodzime** [comment]
> Whoops, I misunderstood where you wanted me to add the test, sorry.

No problem at all. We still need to figure out how to generally approach this. :)
