### ISSUE TITLE
Support LUKS2

### ISSUE THREAD

**Issue by klausenbusk** [storaged-project/udisks#481]
It seems like udisk currntly doesen't support the new LUKS2 format introduced in cryptsetup 2.0.0

See http://www.saout.de/pipermail/dm-crypt/2017-December/005771.html for more detail.
```
$ udisksctl unlock -b /dev/sdX
Passphrase: 
Error unlocking /dev/sdb: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error unlocking /dev/sdb: Failed to load device's parameters: Invalid argument
```

**Comment by vpodzime** [comment]
We first need support for [LUKS2 in libblockdev](https://github.com/storaged-project/libblockdev/issues/315)

**Comment by vojtechtrefny** [comment]
#483 fixes the unlocking issue. We still need do some more changes before supporting creating of luks2 format.
