### ISSUE TITLE
Two devices with identical Serial Number

### ISSUE THREAD

**Issue by elboulangero** [storaged-project/udisks#490]
Dear UDisks team,

I'm working on a project where we have two eMMC on an USB Hub. Unfortunately, they have the same serial number. Here are the kernel logs at boot time. Notice from the timestamps that one of the eMMC shows up later - I don't think it matters here.

```
Jan 29 16:20:21 localhost.localdomain kernel: usb 2-1.2.2: new high-speed USB device number 4 using ehci-pci
Jan 29 16:20:21 localhost.localdomain kernel: usb 2-1.2.2: New USB device found, idVendor=058f, idProduct=6366
Jan 29 16:20:21 localhost.localdomain kernel: usb 2-1.2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jan 29 16:20:21 localhost.localdomain kernel: usb 2-1.2.2: Product: Flash Card Reader/Writer
Jan 29 16:20:21 localhost.localdomain kernel: usb 2-1.2.2: Manufacturer: Generic
Jan 29 16:20:21 localhost.localdomain kernel: usb 2-1.2.2: SerialNumber: 058F63666485

...

Jan 29 16:20:27 localhost.localdomain kernel: usb 2-1.2.4: New USB device found, idVendor=058f, idProduct=6366
Jan 29 16:20:27 localhost.localdomain kernel: usb 2-1.2.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jan 29 16:20:27 localhost.localdomain kernel: usb 2-1.2.4: Product: Flash Card Reader/Writer
Jan 29 16:20:27 localhost.localdomain kernel: usb 2-1.2.4: Manufacturer: Generic
Jan 29 16:20:27 localhost.localdomain kernel: usb 2-1.2.4: SerialNumber: 058F63666485
```

As you can see, both device bear exactly the same Vendor Id, Product Id and Serial Number.

In this tricky situation, UDisks gets it wrong. A dump from `udisksctl` shows only one Drive instead of two:

```
/org/freedesktop/UDisks2/drives/Multiple_Card__Reader_058F63666485:
  org.freedesktop.UDisks2.Drive:
    CanPowerOff:                true
    Configuration:              {}
    ConnectionBus:              usb
    Ejectable:                  true
    Id:                         Multiple-Card--Reader-058F63666485
    Media:                      
    MediaAvailable:             true
    MediaChangeDetected:        true
    MediaCompatibility:         
    MediaRemovable:             true
    Model:                      Card  Reader
    Optical:                    false
    OpticalBlank:               false
    OpticalNumAudioTracks:      0
    OpticalNumDataTracks:       0
    OpticalNumSessions:         0
    OpticalNumTracks:           0
    Removable:                  true
    Revision:                   1.00
    RotationRate:               -1
    Seat:                       seat0
    Serial:                     058F63666485
    SiblingId:                  /sys/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.2/2-1.2.2/2-1.2.2:1.0
    Size:                       7818182656
    SortKey:                    00coldplug/12removable/sd____c
    TimeDetected:               1517242816390327
    TimeMediaDetected:          1517242816390327
    Vendor:                     Multiple
    WWN: 
```

And when it comes to the block devices, I have this kind of things:

```
/org/freedesktop/UDisks2/block_devices/sdc:
    Device:                     /dev/sdc
    Drive:                      '/org/freedesktop/UDisks2/drives/Multiple_Card__Reader_058F63666485'
    Symlinks:                   /dev/disk/by-id/usb-Multiple_Card_Reader_058F63666485-0:0
                                /dev/disk/by-path/pci-0000:00:1d.0-usb-0:1.2.2:1.0-scsi-0:0:0:0

...

/org/freedesktop/UDisks2/block_devices/sdd:
    Device:                     /dev/sdd
    Drive:                      '/org/freedesktop/UDisks2/drives/Multiple_Card__Reader_058F63666485'
    Symlinks:                   /dev/disk/by-id/usb-Multiple_Card_Reader_058F63666485-0:0
                                /dev/disk/by-path/pci-0000:00:1d.0-usb-0:1.2.4:1.0-scsi-0:0:0:0
```

I only paste here what's relevant, but I can provide the full output if you want.

What we see here is that:
- both devices `sdc` and `sdd` have the same `Drive` property.
- both devices `sdc` and `sdd` have the same symlinks `by-id`, although this is out of UDisks scope.
- however, the `by-path` symlinks are different.

Should I understand that UDisks rely on the `by-id` symlink internally, or at least rely on Vendor Id + Product Id + Serial, to identify devices ?

And what's the suggested workaround in this situation ?

Thanks

**Comment by vpodzime** [comment]
In general, the problem is with the devices. All the device identifiers are the same. So to the system the devices look like a single device with multiple paths (hence the warning above). 

Regarding a possible workaround -- what is it you are trying to do/achieve?

**Comment by elboulangero** [comment]
> Regarding a possible workaround -- what is it you are trying to do/achieve?

Remember, I have two devices on the same USB hub. I need to format one of them.

Let's say one device lives at `/dev/sdc`, and the other lives at `/dev/sdd`. The user wants to format `/dev/sdc`. Before I format the device, I want to check if there is any mounted partition from this device, and unmount it. Otherwise formatting will fail.

I do that in Python, using the GObject Introspection binding for UDisks.

My code is something like that:

1. Get the `Drive` property for the block device `/dev/sdc`.
2. Then browse all the block devices, and match those with the same `Drive` property.
3. If this block devices have a mounted filesystem, unmount it.
4. Done, I can format `/dev/sdc`.

The issue here is in step 2: I want to find all the block devices that belong to `/dev/sdc`, and for that I use the `Drive` property of `/dev/sdc`. However, in the example I describe here, both `/dev/sdc` and `/dev/sdd` have the same value for the `Drive` property. So it doesn't work, in the end I'm left with block devices from both `/dev/sdc` and `/dev/sdd`, and I try to unmount it all.

What I need is a reliable way to find all the block devices that belong to `/dev/sdc`. And I thought that the `Drive` property was meant for that (please correct me if I'm wrong).

So my current workaround is to check the `Device` property, and check that the device name (for example `/dev/sdc1`) starts with `/dev/sdc`. This works, except that there are some encrypted devices in the story, so I also have to check for things like `/dev/dm-1`, and it becomes a kind of slippery hack.

Additionally, in this situation, an application like `gnome-disks` also gets confused. It's not such a big deal, but here there's no workaround as I will not go and patch it.

> Honestly, first advice would be to stay away from anything that has multipath in its name because I am quite sure that would be where the real troubles would start.

I'd like to, but the fact is that on this project, we have two eMMC, and they have the same serial, and we can't do nothing about it now. We have to live with it and work with that somehow :/

**Comment by vpodzime** [comment]
The problem is that, as explained above, to the system these two block devices are actually just different paths to the same device. Because the identifiers are how multipath devices are recognized. I see that you cannot do anything about it. But I don't quite know what *udisks* could do about this while avoiding breaking the real multipath setups. The only thing that comes to my mind is to introduce some new flag set up by *udev* (rule) that would mark a device as "never a multipath member". So maybe something like ``NO_MULTIPATH`` literally. For such devices, *udisks* could use the path as (part of) the unique identifier.

**Comment by elboulangero** [comment]
Thanks for your feedback. I was suggested also to see if I can hook myself somewhere in udev, and tweak the name of the link `/dev/disk/by-id/...`. Apparently this link is created by udev, but don't quote me on that :)

Anyway, it's a bit out of scope for UDisks.

I'm still curious though. Do you know about the internal of UDisks enough to know how the `Drive` property is created ? Because my initial reaction was something like:

`/org/freedesktop/UDisks2/drives/Multiple_Card__Reader_058F63666485`

-> should be

`/org/freedesktop/UDisks2/drives/pci-0000_00_1d_0-usb-0_1.2.4_1.0-scsi-0_0_0_0`

In my particular case, that would have solved my issue, since apparently the symlinks in `/dev/disk/by-path/` have more warranty to be unique than the symlinks in `/dev/disk/by-id`, so they make a better candidate to create the `Drives` property. Although such a `Drive` property is now super ugly and not user-friendly at all.

I'm definitely not asking for such a change, but I'm just wondering if there's pros and cons for `by-path` versus `by-id`, and if what I'm saying here makes sense or not, from your point of view as a UDisks maintainer.

**Comment by vpodzime** [comment]
> Apparently this link is created by udev, but don't quote me on that :)

Yes, these symlinks are created by *udev*.

**Comment by vpodzime** [comment]
> I'm just wondering if there's pros and cons for by-path versus by-id, and if what I'm saying here makes sense or not, from your point of view as a UDisks maintainer.

The thing is that having multiple paths for a single drive is a valid and widely used setup. It's usually referred to as *multipath* and it provides many nice features. And since the ``Drive`` objects refer to actual drives and not paths, they are created using the drive identifiers.

**Comment by elboulangero** [comment]
Thanks for all the explanations!
