### ISSUE TITLE
Support LUKS2 encryption with F2FS/BTRFS

### ISSUE THREAD

**Issue by denji** [storaged-project/udisks#496]

**Comment by vojtechtrefny** [comment]
What is actually the issue here? We already have an issue for LUKS2 support (#481) but creating LUKS with f2fs or btrfs is currently supported (`Format` function from `org.freedesktop.UDisks2.Block` interface can create both btrfs and f2fs on top of LUKS).

**Comment by vojtechtrefny** [comment]
LUKS2 changes have been merged (#552) and will be part of the next release so I'm closing this issue. If it doesn't cover your issue/rfe feel free to reopen it with more detailed information.
