### ISSUE TITLE
Support RHEL deduplicated and/or compressed block storage (Permabit)

### ISSUE THREAD

**Issue by denji** [storaged-project/udisks#497]
> Project documentation is being converted from its proprietary form and will be added to this repository at a later date.

> With VDO's compression, multiple blocks (or shared blocks) are compressed with the fast LZ4 algorithm, and binned together where possible so that multiple compressed blocks fit within a 4 KB block on the underlying storage. Mapping from LBA is to a physical block address and index within it for the desired compressed data. All compressed blocks are individually reference counted for correctness.

* https://github.com/dm-vdo/vdo#vdo

**Comment by vojtechtrefny** [comment]
We plan to support VDO in some future release of udisks.

**Comment by vojtechtrefny** [comment]
New VDO module is part of 2.8.0
