### ISSUE TITLE
Clarify official bug tracker on Web site

### ISSUE THREAD

**Issue by paulmenzel** [storaged-project/udisks#499]
What is the official bug tracker. The [Web site][1] still says the freedesktop.org Bugzilla:

> When [filing bugs against udisks](http://bugs.freedesktop.org/enter_bug.cgi?product=udisks), please include …

The README says the GitHub issue tracker.

[1]: https://www.freedesktop.org/wiki/Software/udisks/

**Comment by vojtechtrefny** [comment]
Thank you, I'll ask admin of the freedesktop wiki to change it (I don't have edit access there). But it is still possible to use the freedesktop bugzilla to report bugs for udisks and we check them too.

**Comment by paulmenzel** [comment]
Sorry, I do not want get on your nerves, but do you have an update?

**Comment by martinpitt** [comment]
I updated the wiki page to point to GitHub only. Long-term IMHO it makes sense to direct people to one bug tracker only, and for development the github one is more comfortable as it's better integrated with the PR workflow.

**Comment by vojtechtrefny** [comment]
> Sorry, I do not want get on your nerves, but do you have an update?

No problem. I'm sorry, I completely forgot about this issue.

**Comment by vojtechtrefny** [comment]
> I updated the wiki page to point to GitHub only. Long-term IMHO it makes sense to direct people to one bug tracker only, and for development the github one is more comfortable as it's better integrated with the PR workflow.

Thank you!
