### ISSUE TITLE
No visible method to configure mount options by udev rule

### ISSUE THREAD

**Issue by 20kdc** [storaged-project/udisks#500]
On Linux, the aggressive write cache is highly problematic for usability, as users expect to be able to pull out various drives after an operation has appeared to complete.
To me, it seems this should be solvable by adding a udev rule to simply mount with, for example, 'flush' (EDIT: This might need to be more per-filesystem. Hm. The point stands.), but if such functionality exists, I haven't managed to find any documentation on it.
(Another solution may be to allow the `/etc/udisks2/IDENTIFIER.conf` options to be controllable from udev, and document this, but this offers less control than mount options.)

**Comment by vojtechtrefny** [comment]
This is currently not possible and you are not the first one asking for some configuration for mount options. We plan to do something with this, but unfortunately it won't happen anytime soon -- we have quite a lot of things in our TODO list.
