### ISSUE TITLE
jobd + parity

### ISSUE THREAD

**Issue by realies** [storaged-project/udisks#501]
Would it be possible to introduce a jbod + parity type of array?

**Comment by vpodzime** [comment]
Is it supported by ``mdadm``?

**Comment by realies** [comment]
Do not think so. It is supported by `unRAID`.

**Comment by vpodzime** [comment]
> unRAID is a Linux-based operating system optimized for media file storage.

I cannot really see how we could integrated that into *udisks*. But maybe you can do a similar thing with LVM?

**Comment by vpodzime** [comment]
> Would be interested to know.

Well, *JBOD* is the same thing as *linear* LVs (the default ones). And you can span *RAID* LVs (with parity) across multiple disks. So it is quite easy, actually.

**Comment by realies** [comment]
But RAID LVs != JBOD+Parity.

**Comment by vpodzime** [comment]
> But RAID LVs != JBOD+Parity.

Oh, I thought you wanted RAID on top of JBOD disks. So you want JBOD with just parity calculated from the respective sectors of the disks, right?

**Comment by realies** [comment]
https://lime-technology.com/wiki/UnRAID_Manual_6#Parity-Protected_Array

**Comment by vpodzime** [comment]
> https://lime-technology.com/wiki/UnRAID_Manual_6#Parity-Protected_Array
> It has a dedicated parity drive that has to be equal or bigger in size to any disk that is part of the JBOD.

I see, thanks for the link! It looks to me like something that has to suffer from terrible performance issues on writes, but I guess there are use-cases where it can be useful.

Anyway, I don't think it can be integrated into *udisks* while neither *mdraid* nor *LVM* support it.

**Comment by realies** [comment]
What do you think would be that best approach to chasing this functionality?

**Comment by vpodzime** [comment]
Well, if there is a support for this in kernel RAID personalities, then it may be easy to add it to either *mdadm* or *LVM*. But I'm afraid that's not the case as it is not a standard SNIA RAID level with proper definitions. Do you know if the *unRAID* product is using Linux and upstream kernel code? Or maybe they have some downstream patches adding this non-standard "RAID level"?
