### ISSUE TITLE
Bug -- udisks error probing device kingston ssd 

### ISSUE THREAD

**Issue by ryanmusante** [storaged-project/udisks#511]
Journalctl errors with udisks and my kingston ssd. Drive functions but what is the status of this error?

```
udisksd[2090]: Error probing device: Error sending ATA command IDENTIFY DEVICE to /dev/sdb: Unexpected sense data returned:
                                   0000: 70 00 0b 00  00 00 00 0a  00 80 00 00  47 00 00 00    p...........G...
                                   0010: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00    ................
                                    (g-io-error-quark, 0)
```
```
kernel: ata7.00: ATA-8: Kingston SHPM2280P2/240G, OC34L5TA, max UDMA/133
kernel: ata7.00: 468862128 sectors, multi 0: LBA48 NCQ (depth 31/32)
kernel: ata7.00: configured for UDMA/133
kernel: scsi 6:0:0:0: Direct-Access     ATA      Kingston SHPM228 L5TA PQ: 0 ANSI: 5
```

**Comment by vpodzime** [comment]
Looks like the device identifies itself in some way *udisks* doesn't expect. In particular the first byte should be ``72``. Not sure if this is a bug in *udisks* or if the SSD doesn't follow the protocol.

**Comment by ryanmusante** [comment]
I have some strange results with smartctl. I've been using this drive for a long time now though, is that error  something to be concerned about?

**Comment by vpodzime** [comment]
> I have some strange results with smartctl. I've been using this drive for a long time now though, is that error something to be concerned about?

Depends on what SMART reports. I haven't had time to study the ATA protocol to see if ``70`` is also a valid value or not.

**Comment by ERYuyNIrbNKrsc** [comment]
may be related

udisksd[485]: Error performing housekeeping for drive `/org/freedesktop/UDisks2/drives/Samsung_SSD_850_EVO_250GB_S3NYNB0JB07566T: Error updating SMART data: sk_disk_smart_read_data: Operation not supported (udisks-error-quark, 0)`

```
Error calling Drive.Ata.PmGetState: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: Error sending ATA command CHECK POWER MODE: Unexpected sense data returned:
0000: 01 00 1d 00  00 00 0e 09  0c 00 00 00  ff 00 00 00    ................
0010: 00 00 00 00  50 00 00 00  00 00 00 00  00 00 00 00    ....P...........
 (g-io-error-quark, 0)
```

```
ata1: SATA max UDMA/133 abar m2048@0xf7c32000 port 0xf7c32100 irq 25
ata1: SATA link up 6.0 Gbps (SStatus 133 SControl 300)
ata1.00: ATA-9: Samsung SSD 850 EVO 250GB, EMT03B6Q, max UDMA/133
scsi 0:0:0:0: Direct-Access     ATA      Samsung SSD 850  3B6Q PQ: 0 ANSI: 5
```


it happens on kernel 4.16 when on 4.15 no problem.

**Comment by vpodzime** [comment]
@ryanmusante which kernel version are you running?

**Comment by ryanmusante** [comment]
@vpodzime kernel 4.15

**Comment by ryanmusante** [comment]
Kernel 4.16 now, no change

**Comment by tbzatek** [comment]
@ryanmusante, the referenced patch from the kernel bugzilla got into stable with linux kernel release 4.16.7. What version exactly are you on?

**Comment by ryanmusante** [comment]
Manjaro stable branch, linux416 [4.16.12-1]
