### ISSUE TITLE
Running jobs should register an inhibitor lock

### ISSUE THREAD

**Issue by pothos** [storaged-project/udisks#516]
If the system is configured to suspend after being unused for 20 minutes (default in GNOME and thus the new Fedora and Ubuntu) or if a user requests suspend or shutdown, only block format and drive ATA secure erase will use `udisks_daemon_util_inhibit_system_sync` while all other possibly long-running jobs are left without inhibitors (SMART tests, resize, repair etc).

Instead of adding the inhibitor calls to every job, we could move the inhibit calls to the `UDisksBaseJob` constructor and deconstructor functions and adding the cookie as private variable. And maybe a property to set a nice inhibitor reason (but this requires reinitializing the inhibitor because it comes after the object was created).

Or should they just be added to candidates for potentially long running jobs?

**Comment by vpodzime** [comment]
> Instead of adding the inhibitor calls to every job, we could move the inhibit calls to the UDisksBaseJob

Sounds like a great idea!

> And maybe a property to set a nice inhibitor reason

We already have the job description, can't we just use that?

**Comment by vojtechtrefny** [comment]
I think we should use the inhibitor for all jobs, even some "fast" jobs could take a long time to finish in some cases (probably not more than 20 minutes, but it's better to block the suspend just to be sure).

Adding the code to `UDisksBaseJob` is definitely a good idea. And it's "safer" for new jobs too -- no one will remember to add this for new functions.

**Comment by pothos** [comment]
I didn't find time to try it yet, but I thought of just using the GObject constructor functions directly. In that case the job operation property is not set yet. But yes, if `common_job` is always used anyway, then the call to the inhibitor could be delayed to this point.

I try to do a PR maybe until next week unless somebody is faster ;)
