### ISSUE TITLE
test_md_raid_methods fails on s390x

### ISSUE THREAD

**Issue by seb128** [storaged-project/udisks#517]
The test_md_raid_methods test is failing on s390x (Ubuntu bionic, udisk 2.7.6) with that error

======================================================================
FAIL: test_md_raid_methods (__main__.MDRaid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 1772, in test_md_raid_methods
    self.assertIsNotNone(block)
AssertionError: unexpectedly None

The full testsuit log can be found there
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic/bionic/s390x/u/udisks2/20180329_111654_82a2f@/log.gz

Note that libblockdev is built without the s390x backend in Ubuntu, unsure if that can make a difference

**Comment by vpodzime** [comment]
> Note that libblockdev is built without the s390x backend in Ubuntu, unsure if that can make a difference

*udisks* is not using the *libblockdev-s390* functionality in any way, AFAIK. So it should not matter.

Is the issue 100% reproducible or is it happening just sometimes?

**Comment by seb128** [comment]
it seems 100% reproducible, let me know if I can provide some useful debug details

**Comment by vojtechtrefny** [comment]
This is a bug in mdadm on s390, it repors 2 "different" UUIDs for the array and it completely confuses udisks

```
# mdadm --detail --export /dev/md/test
MD_LEVEL=raid1
MD_DEVICES=2
MD_METADATA=0.90
MD_UUID=a97ffb8b:b3202156:55f4f69d:7c5211d7
```

```
# mdadm --detail /dev/md/test
/dev/md/test:
           Version : 0.90
...
UUID : 8bfb7fa9:562120b3:9df6f455:d711527c (local to host devel8.s390.bos.redhat.com)
```

```
# blkid /dev/sda
/dev/sda: UUID="8bfb7fa9-5621-20b3-9df6-f455d711527c" TYPE="linux_raid_member"
```

I'll create a PR to skip this test on s390 and I report this to mdadm.

**Comment by vpodzime** [comment]
I wonder how it have could possibly passed through *mdadm*'s test suite on s390...

**Comment by seb128** [comment]
The change indeed fixes the issue thanks!

There is still some flakyness on s390x with your changes backported to 2.7.6 though

"ERROR: test_luks_forced_removal (__main__.Luks)
LUKS forced removal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 1422, in test_luks_forced_removal
    mount_path = fs.call_mount_sync(no_options, None)
AttributeError: 'NoneType' object has no attribute 'call_mount_sync'"

but I guess that should be a new report?
