### ISSUE TITLE
NVME temperature reporting

### ISSUE THREAD

**Issue by erpalma** [storaged-project/udisks#518]
Hello, It would be very useful if udisks supports reading the temperature of NVME drives. Right now the only way is to use smartctl or nvme which both lack DBus:

```
# nvme smart-log /dev/nvme0n1
Smart Log for NVME device:nvme0n1 namespace-id:ffffffff
critical_warning                    : 0
temperature                         : 39 C
available_spare                     : 100%
available_spare_threshold           : 10%
percentage_used                     : 0%
...
Warning Temperature Time            : 0
Critical Composite Temperature Time : 0
Temperature Sensor 1                : 39 C
Temperature Sensor 2                : 48 C
Thermal Management T1 Trans Count   : 0
Thermal Management T2 Trans Count   : 0
Thermal Management T1 Total Time    : 0
Thermal Management T2 Total Time    : 0
```

**Comment by vpodzime** [comment]
Isn't it part of the SMART data for the device? *udisks* already provides that.

**Comment by vojtechtrefny** [comment]
This is probably duplicate of #386 Temperature is reported in the `org.freedesktop.UDisks2.Drive.Ata` interface but it doesn't work for NVME drives (the interface is missing).

@erpalma Can you please send output of `udisksctl info --drive YOUR_DRIVE` (completion should work for the drive name, or it should be visible in `udisksctl info --block-device /dev/nvme0n1` property `Drive`). Thanks.

**Comment by vojtechtrefny** [comment]
Thank you. There is no `Disk.ATA` interface so this is definitely duplicate of #386. I'll try to look at the original issue again soon.
