### ISSUE TITLE
Set up HTTPS for https://storaged.org/

### ISSUE THREAD

**Issue by paulmenzel** [storaged-project/udisks#520]
It’d be great, if you set up HTTPS for https://storaged.org, which seems to be served by GitHub.

> The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io

**Comment by vojtechtrefny** [comment]
We are using github pages for storaged.org and I'm not sure if it's possible to set https for custom domain there. I'll try to look for some solution for this, but this may take some time.

**Comment by wjt** [comment]
It's now a one-checkbox change. Go to https://github.com/storaged-project/storaged-project.github.io/settings and tick "Enforce HTTPS". The certificate will be obtained from Let's Encrypt. (I just tested this for one of my own repos.) More details: https://help.github.com/articles/securing-your-github-pages-site-with-https/#enforcing-https-for-your-github-pages-site

**Comment by vpodzime** [comment]
![enforce-https](https://user-images.githubusercontent.com/1044278/47359355-d7620d80-d6cc-11e8-919c-6ef4952fe1bc.png)

If only...

**Comment by vojtechtrefny** [comment]
We need to change the DNS records to make this work.

**Comment by paulmenzel** [comment]
Is there an easier solution available now, or do you still need to change the DNS records?

**Comment by vojtechtrefny** [comment]
This should be now fixed (including correct DNS records).
