### ISSUE TITLE
UDisks2 does not have "FindDeviceByDeviceFile" API.

### ISSUE THREAD

**Issue by amolNG** [storaged-project/udisks#522]
I am having a C++ QT project which was running on CentOS6 machine.

In which below code will, Given a device file path, e.g. /dev/sda (no ending slash), returns a pointer to the UDisks device interface or 0 if it's invalid.

static QDBusInterface* deviceFromFile(const QString &deviceFile)
{
    QDBusInterface udisks("org.freedesktop.UDisks","/org/freedesktop/UDisks", "org.freedesktop.UDisks", QDBusConnection::systemBus());
    QDBusReply<QDBusObjectPath> devicePath = udisks.call("FindDeviceByDeviceFile", deviceFile);
    if (!devicePath.isValid())
        return 0;

    QScopedPointer <QDBusInterface> device(new QDBusInterface("org.freedesktop.UDisks",
                                                              devicePath.value().path(),
                                                              "org.freedesktop.UDisks.Device",
                                                              QDBusConnection::systemBus()));
    return device->isValid() ? device.take() : 0;
}

Above code is working fine in CentOS6.

Currently we are migrating to CentOS7 and this is not working.

I googled for "FindDeviceByDeviceFile" API alternate, but i was not able to find it.

Please let me know how to use "FindDeviceByDeviceFile" API with UDisks2 as this has got blocker for me.

Awaiting for your reply.

**Comment by vpodzime** [comment]
I think you should be able to leverage the [ResolveDevice](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Manager.html#gdbus-method-org-freedesktop-UDisks2-Manager.ResolveDevice) method.

**Comment by vpodzime** [comment]
> I am on CentOS7 machine.

Sorry for misleading you, the documentation for the ``ResolveDevice()`` method says:
> Since 2.7.3

I guess you have some older version then? You could use https://copr.fedorainfracloud.org/coprs/g/storage/udisks-daily/, but if that's not an option I'm afraid you would have to get all the objects under the ``/org/freedesktop/UDisks2/block_devices`` path and check them for match.

**Comment by amolNG** [comment]
Ok Thanks i will try with one.

**Comment by vpodzime** [comment]
@amoING any news on this? I'd like to close the issue as I think nothing will really be done in these regards.

**Comment by amolNG** [comment]
@vpodzime thanks that worked and sorry for the delay. You can close the ticket 👍
