### ISSUE TITLE
[feature request] move zram config file from /usr/local/lib/zram.conf.d/ to /etc/udisks2/

### ISSUE THREAD

**Issue by enihcam** [storaged-project/udisks#533]
please move zram config file from /usr/local/lib/zram.conf.d/ to /etc/udisks2/ so they can be tracked by etc-keeper.

**Comment by vpodzime** [comment]
I think a lot more should be changed in how zram is setup. See #353

**Comment by tbzatek** [comment]
I've made it configurable though opted for using `/usr/lib/zram.conf.d/` for the moment. The new post-systemd FHS rules are little weird though.
