### ISSUE TITLE
Extend the module API with error reporting

### ISSUE THREAD

**Issue by tbzatek** [storaged-project/udisks#540]
So it has happened to me just today that a module initialization failure torn down the whole daemon. Calling `udisks_error()` from modules is really not a good idea unless there's real reason for that. Citing the docs:

> \* udisks_error:
> \* \@args...: printf()-style format string and arguments
> \*
> \* Logging macro for %UDISKS_LOG_LEVEL_ERROR.
> \* Warning: THIS ALSO TERMINATES THE PROCESS with the abort() call!

In particular this comes from the `UDisksModuleInitFunc` implementation on a module side after `bd_reinit()` fails. That explains the
> /* XXX: can do nothing more here even though we know the module will be unusable! */

comments.

For an uknown reason none of the UDisksModule* funcs are taking GError** argument for error reporting and with `UDisksModuleInitFunc` the return value is even used for returning module state pointer. Since I wrote the modular API I take full responsibility for that mistake. :-)

----

While there are no defined API guarantees fortunately a warning is noted down in the docs:

> there's no support for out-of-the-tree modules and care must be taken when changing UDisks internals.

So my proposal is to revise and extend at least the `UDisksModuleInitFunc` API and adapting the in-tree modules accordingly.

Does this sound okay with you?

**Comment by tbzatek** [comment]
Another related enhancement proposal: right now the `org.freedesktop.UDisks2.Manager.EnableModules()` method can only be called once, subsequent calls are ignored since the module system is already marked as activated.

However this can be further enhanced to scan for new modules and attempt to re-initialize the failed ones.  There seems to be no real reason to prevent this, it was just a design decision for simplicity (in contrast to module deactivation which is not supported for good reasons).

Now that `libblockdev` implements another layer of plugin system this enhancement would be useful in case a new `libblockdev` plugin or its dependencies (e.g. filsystem tools) is installed. The udisks daemon could be then poked to rescan modules, e.g. from package post-install scriptlets.

With this in place we could let the udisks modules fail peacefully during the `UDisksModuleInitFunc` call so that the failed modules get another chance when e.g. `bd_reinit()` succeeds finally.

**Comment by vpodzime** [comment]
> With this in place we could let the udisks modules fail peacefully during the UDisksModuleInitFunc call so that the failed modules get another chance when e.g. bd_reinit() succeeds finally.

Another good idea. ``EnableModules()`` should also return something useful.

**Comment by tbzatek** [comment]
> Another good idea. `EnableModules()` should also return something useful.

I'm afraid that would be a public API break since D-Bus method call signatures cannot change. It's not like C calling convention where arguments are put on the stack and only picked if the implementation expects them.

A slightly different solution is being proposed: https://gist.github.com/tbzatek/515c2490d47620ca323afab7324c2457
