### ISSUE TITLE
vdo: Watch and parse /etc/vdoconf.yml

### ISSUE THREAD

**Issue by tbzatek** [storaged-project/udisks#541]
VDO maintains its own list of configured volumes and their settings in a config file. While there are plans upstream to store such data on the device itself, for now we need to support VDO in its current state. 

Apart of possible consistency issues there are several key problems in keeping the data there and not in the standard device database, aka. `udev`:
* on a stopped volume only `ID_FS_TYPE=vdo` and `ID_FS_UUID` udev attributes are exposed, no VDO name that is consumed by the `vdo` tool
* deactivated and stopped volume has to be activated first, needs VDO name
* starting a VDO volume needs VDO name
* attributes like compression and deduplication are stored in the configuration file and their change doesn't trigger udev event

As a result the udisks VDO module API has been designed with these limitations in mind but doesn't fully fit the usual udisks API style. See the udisks VDO D-Bus interface docs for details.

----

To improve the situation we may parse and watch the VDO configuration file, stored in `/etc/vdoconf.yml`. Not taking in account the optional `vdo` tool argument for providing custom path to the config file, that's out of the scope of udisks use case.

The config file is YAML-structured, containing records for all currently configured VDO volumes. Still this doesn't solve discovery and activation of foreign VDO volumes that are not configured there. No idea how to deal with possible backing device path inconsistency, e.g. when persistent or unique device paths are not used and the configured data doesn't match the actual system.

If we set a watch on this config file and parse the data out on every change, this may be potentially CPU-consuming operation, notably when comparing all the attribute values for objects we export. It would allow us however to resolve device filename for a VDO volume name (and vice versa) and also to watch for VDO attribute changes. Specifically we can expose extra D-Bus interface for stopped VDO volumes (block objects) so that udisks consumers don't need to know VDO volume name in order to activate and start it.

----

Posting as a task for the future, depending on feedback from udisks consumers. Not sure if it's worth the complications at the moment...

**Comment by vojtechtrefny** [comment]
We plan to deprecate the VDO plugin and support VDO only in LVM which doesn't use `/etc/vdoconf.yml`.
