### ISSUE TITLE
Bugfix Release for 2.7.6

### ISSUE THREAD

**Issue by pothos** [storaged-project/udisks#546]
What do you think about a bugfix release for stable UDisks? This would help users in Fedora, Debian and Ubuntu etc. experiencing the loopback password regression e.g. in GNOME Disks: https://gitlab.gnome.org/GNOME/gnome-disk-utility/issues/82

The problem was fixed in https://github.com/storaged-project/udisks/issues/519 through patch https://github.com/storaged-project/udisks/commit/b025f2bb2b148451417ae64a8c878ea4e6442a02

**Comment by vojtechtrefny** [comment]
I plan to release 2.7.7, we have more than 50 commits since 2.7.6 (and I didn't realize it's nearly 5 months since 2.7.6) so i guess it's time for new release.

**Comment by pothos** [comment]
Good to hear that, however I am not sure whether this release could get included in a feature freezed distribution like Ubuntu 18.04 or Fedora 28 – I don't know their policies well. Therefore I just suggested a point release for 2.7.6.

**Comment by vojtechtrefny** [comment]
I am not familiar with Debian/Ubuntu policies but it's not a problem for older/stable Fedora versions, we can update to new versions. I think this should be responsibility of the package maintainer -- maintainer should either update to latest upstream version (and this is only micro version update and it is backwards compatible so it shouldn't be a problem) or select just some fixes and maintain them as downstream patches (if there are some distribution policies that don't allow updating).

It would be nice to have some feedback from Ubuntu and/or Debian (or other distributions) package maintainers. It is possible that a point release for 2.7.6 would be useful for them but from my point of view (as a Fedora package maintainer) it shouldn't be necessary.

**Comment by loxK** [comment]
A point bug fix release would for sure help to have it fixed in Ubuntu.

**Comment by vpodzime** [comment]
> A point bug fix release would for sure help to have it fixed in Ubuntu.

Would it be enough for you guys if there was an upstream branch with cherry-picked/ported bugfixes you could easily use as downstream patches?

**Comment by seb128** [comment]
Speaking for Ubuntu, we don't need an upstream bug fix tarball or special branch for one fix to backport. 

Having a 2.7.6.1 could be useful if you have a stack of fixes you would like 2.7.6 users to get though since it doesn't seem likely that we would be able to do a stable update to 2.7.7 which is not a bugfix only update (it bumps the libblockdev depends to a version that isn't available in Ubuntu at the moment for example)

**Comment by seb128** [comment]
(I'm uploading the fix as a backport to Ubuntu current and stable series, see https://bugs.launchpad.net/ubuntu/+source/udisks2/+bug/1779238 for details)

**Comment by vpodzime** [comment]
> Having a 2.7.6.1 could be useful if you have a stack of fixes you would like 2.7.6 users to get though

I think this would be quite a lot of work for little gain. Adding downstream patches is common and easy. The special branch could make sense if the changes don't apply cleanly and have to be backported non-trivially. Which is not the case, AFAICT.

**Comment by pothos** [comment]
Okay, I see, will close it then. Still my fear is that this git commit gets only backported to, let's say Ubuntu and Fedora after the bugtracker noise, but most in other distros this will stay broken. Releases are a clear way of communicating bug fixes and that's why I thought it would have been appropriate. Anyway, thanks for the responses to all of you ;)
