### ISSUE TITLE
Error mounting NTFS on read-only devices

### ISSUE THREAD

**Issue by segfault3** [storaged-project/udisks#553]
When mounting a NTFS filesystem on a read-only device (I only tested read-only loop devices, not physical devices), the operation fails with:
```
Error mounting /dev/loop1 at /media/user/21F99Bd53C13C420
Command-line `mount -t "ntfs" -o "uhelper=udisks2,nodev,nosuid,uid=1000,gid=1000" "/dev/loop1" "/media/user/21F99Bd53C13C420" exited with non-zero exit status 21:
ntfs-3g-mount: mount failed: Permission denied
Failed to sync device /dev/loop1: Input/output error
Failed to close volume /dev/loop1: Input/output error
```

From the kernel log:
```
generic_make_request: Trying to write to read-only block-device loop1 (partno 0)
```

This affects NTFS-formatted VeraCrypt file containers which are mounted read-only, which is a quite common use case.

**Comment by pothos** [comment]
See here https://gitlab.gnome.org/GNOME/gnome-disk-utility/issues/19 and here https://github.com/karelzak/util-linux/issues/460

This needs to be fixed in the mount.ntfs-3g helper binary. My problem last time was that I could not reach out to the ntfs-3g devs.

**Comment by segfault3** [comment]
I found this mailing list, I think it should be reported there:
https://sourceforge.net/p/ntfs-3g/mailman/ntfs-3g-devel/

**Comment by pothos** [comment]
Thanks for picking up these loose ends. I've sent a mail to the list.

**Comment by segfault3** [comment]
I can't see your email in the mailing list archive, so I now also tried to send an email to the list.

**Comment by segfault3** [comment]
There it is: https://sourceforge.net/p/ntfs-3g/mailman/message/36385004/

**Comment by vpodzime** [comment]
@pothos @segfault3 any updates on this? I'm thinking I can close the issue because there's nothing we can/need to do in *UDisks2*, right?
