### ISSUE TITLE
Loop Device Partion Probing

### ISSUE THREAD

**Issue by mvastola** [storaged-project/udisks#564]
So I'm not entirely sure if this is a support request or a feature request (please interpret it as the latter if this functionality isn't currently available), but is there any sort of option to configure `udisks` such that when you call `udisksctl loop-setup` you get the same functionality provided by `losetup --partscan`? 

I'm hoping to do this because if this isn't an option, the user must have either a higher level of access (which will be more difficult to fine-tune) or else will need to manually calculate partition offsets.

Thanks!

**Comment by vpodzime** [comment]
Hi, AFAICT, `udisksctl loop-setup` should do what `losetup --partscan` would do because according to [the documentation](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Manager.html#gdbus-method-org-freedesktop-UDisks2-Manager.LoopSetup) there's a `no-part-scan` option to the `LoopSetup()` method call and the [code in `udisksctl`](https://github.com/storaged-project/udisks/blob/master/tools/udisksctl.c#L1613) is not passing the option to the method call.

**Comment by vojtechtrefny** [comment]
As @vpodzime says, this should work by default. I just tested this and it looks everything is working:

```
$ sudo udisksctl loop-setup --file file.img
Mapped file file.img as /dev/loop0.

$ lsblk /dev/loop0
NAME      MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
loop0       7:0    0  10M  0 loop 
├─loop0p1 259:1    0   2M  0 loop 
└─loop0p2 259:2    0   7M  0 loop
```

```
$ udevadm monitor
...
KERNEL[99516.501214] change   /devices/virtual/block/loop0 (block)
KERNEL[99516.502640] add      /devices/virtual/block/loop0/loop0p1 (block)
KERNEL[99516.503534] add      /devices/virtual/block/loop0/loop0p2 (block)
```

```
$ journalctl -r
Aug 15 15:48:21 vt_storaged kernel:  loop0: p1 p2
Aug 15 15:48:22 vt_storaged udisksd[26578]: Set up loop device /dev/loop0 (backed by /home/vtrefny/file.img)
```

@mvastola Is this broken for you? What version of udisks (and what distribution) are you using?

**Comment by mvastola** [comment]
Okay. So now I'm really confused because this seems to be totally working now. (To make things worse, I also can't remember the image I used this on when I had the issue, so it's hard to reproduce.)

Going to close this. I'll reopen if I figure out how to cause the problem again.

Thanks for your time.
