### ISSUE TITLE
Partitions property not returning partitions

### ISSUE THREAD

**Issue by mdhowle** [storaged-project/udisks#570]
I have an SD card with two partitions.  The "Partitions" property of the org.freedesktop.UDisks2.PartitionTable interface is returning an empty array.  I've done a Rescan() on the "sdb" block device and tried rebooted, and I'm still unable to get the PartitionTable to populate.

The partition block devices appear in dbus /org/freedesktop/UDisks2/sdb1 and sdb2, and I can query them.

I'm on ArchLinux, udisks2 2.7.7-1

#### fdisk -l /dev/sdb
    Disk /dev/sdb: 7.4 GiB, 7948206080 bytes, 15523840 sectors
    Units: sectors of 1 * 512 = 512 bytes
    Sector size (logical/physical): 512 bytes / 512 bytes
    I/O size (minimum/optimal): 512 bytes / 512 bytes
    Disklabel type: dos
    Disk identifier: 0x78780cc4

    Device     Boot Start      End  Sectors  Size Id Type
    /dev/sdb1        8192    93596    85405 41.7M  c W95 FAT32 (LBA)
    /dev/sdb2       94208 15523839 15429632  7.4G 83 Linux

#### udisksctl info --block-device /dev/sdb
    /org/freedesktop/UDisks2/block_devices/sdb:
      org.freedesktop.UDisks2.Block:
        Configuration:              []
        CryptoBackingDevice:        '/'
        Device:                     /dev/sdb
        DeviceNumber:               2064
        Drive:                      '/org/freedesktop/UDisks2/drives/TS_RDF5_SD__Transcend_000000000037'
        HintAuto:                   true
        HintIconName:               
        HintIgnore:                 false
        HintName:                   
        HintPartitionable:          true
        HintSymbolicIconName:       
        HintSystem:                 false
        Id:                         
        IdLabel:                    
        IdType:                     
        IdUUID:                     
        IdUsage:                    
        IdVersion:                  
        MDRaid:                     '/'
        MDRaidMember:               '/'
        PreferredDevice:            /dev/sdb
        ReadOnly:                   false
        Size:                       7948206080
        Symlinks:                   /dev/disk/by-id/usb-TS-RDF5_SD_Transcend_000000000037-0:0
                                    /dev/disk/by-path/pci-0000:00:14.0-usb-0:6.1:1.0-scsi-0:0:0:0
                                    /dev/usbport1
        UserspaceMountOptions:      
      org.freedesktop.UDisks2.PartitionTable:
        Partitions:         []
        Type:               dos

#### udisksctl info -b /dev/sdb2
    /org/freedesktop/UDisks2/block_devices/sdb2:
      org.freedesktop.UDisks2.Block:
        Configuration:              []
        CryptoBackingDevice:        '/'
        Device:                     /dev/sdb2
        DeviceNumber:               2066
        Drive:                      '/org/freedesktop/UDisks2/drives/TS_RDF5_SD__Transcend_000000000037'
        HintAuto:                   true
        HintIconName:               
        HintIgnore:                 false
        HintName:                   
        HintPartitionable:          true
        HintSymbolicIconName:       
        HintSystem:                 false
        Id:                         by-uuid-62ca0b6d-6291-4c40-b1fd-11bc291e4a38
        IdLabel:                    
        IdType:                     ext4
        IdUUID:                     62ca0b6d-6291-4c40-b1fd-11bc291e4a38
        IdUsage:                    filesystem
        IdVersion:                  1.0
        MDRaid:                     '/'
        MDRaidMember:               '/'
        PreferredDevice:            /dev/sdb2
        ReadOnly:                   false
        Size:                       7899971584
        Symlinks:                   /dev/disk/by-id/usb-TS-RDF5_SD_Transcend_000000000037-0:0-part2
                                    /dev/disk/by-partuuid/78780cc4-02
                                    /dev/disk/by-path/pci-0000:00:14.0-usb-0:6.1:1.0-scsi-0:0:0:0-part2
                                    /dev/disk/by-uuid/62ca0b6d-6291-4c40-b1fd-11bc291e4a38
                                    /dev/usbport1p2
        UserspaceMountOptions:      
      org.freedesktop.UDisks2.Filesystem:
        MountPoints:        
        Size:               7899971584
      org.freedesktop.UDisks2.Partition:
        Flags:              0
        IsContained:        false
        IsContainer:        false
        Name:               
        Number:             2
        Offset:             48234496
        Size:               7899971584
        Table:              '/org/freedesktop/UDisks2/block_devices/sdb'
        Type:               0x83
        UUID:               78780cc4-02

**Comment by mdhowle** [comment]
If I restart the udisks2.service, it will return the partitions. However, once I change out the SD cards, or remove and re-insert the device, it no longer returns any.

**Comment by pothos** [comment]
Just a sidenote: UDisks renews all properties on udev changes, here a similar case where this leads to property loss https://github.com/storaged-project/udisks/issues/425 – Maybe run `udevadm info -q all -n …` too in order to find whether udev reports the same before and after your case.

**Comment by vojtechtrefny** [comment]
The problem basically is that we update the `Partitions` property only after a change event on the disk and there is no change event when plugging in a SD card (or flash drive). #571 should fix this.
