### ISSUE TITLE
Race condition in unmounting

### ISSUE THREAD

**Issue by pothos** [storaged-project/udisks#573]
Code that unmounts a filesystem and uses `udisks_filesystem_get_mount_points` to check if a block object or its contained volumes are mounted can get wrong results. Until the `mount-points` property update is propagated the `handle_unmount` function needs to wait before returning. Maybe by copying the `udisks_filesystem_get_mount_points` list before the unmonut and compare in the waiter if it has a reduced size.

**Comment by psusi** [comment]
I wanted to look into this some more so I thought I would try to find the previous fix for resizing you mentioned and see how that was done.  I thought you said it was a change in udisks_partition_call_resize(), but I can't find such a function in the udisks source tree.  The only reference rgrep finds is in doc/udisks2-sections.txt.in.in.

**Comment by pothos** [comment]
The first thing to is writing a test case, which I append here. I hope that this will trigger the race on your machine (despite being Python and not C). You don't need to build UDisks to run the tests, but if you want to hack on UDisks, of course you would need to start the patched build it with `-r` in order to replace the system service.

The following test can be run via 

```sudo src/tests/dbus-tests/run_tests.py -s test_80_filesystem.Ext4TestCase.test_unmount_no_race_in_mount_points```

```
diff --git a/src/tests/dbus-tests/test_80_filesystem.py b/src/tests/dbus-tests/test_80_filesystem.py
index ff664542..332a7fbb 100644
--- a/src/tests/dbus-tests/test_80_filesystem.py
+++ b/src/tests/dbus-tests/test_80_filesystem.py
@@ -307,6 +307,42 @@ class UdisksFSTestCase(udiskstestcase.UdisksTestCase):
         self.assertIn(tmp, out)
         self.assertIn('ro', out)
 
+    def test_unmount_no_race_in_mount_points(self):
+        if not self._can_create:
+            self.skipTest('Cannot create %s filesystem' % self._fs_name)
+
+        if not self._can_mount:
+            self.skipTest('Cannot mount %s filesystem' % self._fs_name)
+
+        disk = self.get_object('/block_devices/' + os.path.basename(self.vdevs[0]))
+        self.assertIsNotNone(disk)
+
+        # create filesystem
+        disk.Format(self._fs_name, self.no_options, dbus_interface=self.iface_prefix + '.Block')
+        self.addCleanup(self._clean_format, self.vdevs[0])
+
+        # not mounted
+        mounts = self.get_property(disk, '.Filesystem', 'MountPoints')
+        mounts.assertLen(0)
+
+        # mount
+        d = dbus.Dictionary(signature='sv')
+        d['fstype'] = self._fs_name
+        d['options'] = 'ro'
+        mnt_path = disk.Mount(d, dbus_interface=self.iface_prefix + '.Filesystem')
+        self.addCleanup(self._unmount, self.vdevs[0])
+
+        # dbus mountpoint
+        dbus_mounts = self.get_property(disk, '.Filesystem', 'MountPoints')
+        dbus_mounts.assertLen(1)  # just one mountpoint
+        dbus_mnt = self.ay_to_str(dbus_mounts.value[0])  # mountpoints are arrays of bytes
+        self.assertEqual(dbus_mnt, mnt_path)
+
+        # umount and check that mount-points is immediately empty
+        disk.Unmount(self.no_options, dbus_interface=self.iface_prefix + '.Filesystem')
+        mounts_after_unmount = self.get_property(disk, '.Filesystem', 'MountPoints')
+        mounts_after_unmount.assertLen(0)
+
     def test_userspace_mount_options(self):
         libmount_version = self._get_libmount_version()
         if libmount_version < LooseVersion('2.30'):

```

**Comment by pothos** [comment]
On your question on waiters in UDisks, see src/udiskslinuxpartitiontable.c `WaitForPartitionData`/`wait_data`.

**Comment by pothos** [comment]
Can you build UDisks and test if this waiter here solves your issue?
https://github.com/storaged-project/udisks/pull/574

**Comment by psusi** [comment]
I was right about the number of CPUs.  I enabled all 8 cpus in the vm and now it mounts and unmounts no problem.  When I tried running your test case I got:

psusi@psusi-HVM-domU:~/udisks2$ sudo src/tests/dbus-tests/run_tests.py -s test_80_filesystem.Ext4TestCase.test_unmount_no_race_in_mount_points
Blivet not installed: Skipping force clean
Traceback (most recent call last):
  File "src/tests/dbus-tests/run_tests.py", line 183, in <module>
    setup_vdevs()
  File "src/tests/dbus-tests/run_tests.py", line 40, in setup_vdevs
    assert subprocess.call(["targetcli", "restoreconfig src/tests/dbus-tests/targetcli_config.json"]) == 0
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'targetcli': 'targetcli'

What is blivet?

**Comment by psusi** [comment]
So I installed targetcli and now it crashes with:

psusi@psusi-HVM-domU:~/udisks2$ sudo src/tests/dbus-tests/run_tests.py -s test_80_filesystem.Ext4TestCase.test_unmount_no_race_in_mount_points
Blivet not installed: Skipping force clean
Warning: Could not load preferences file /home/psusi/.targetcli/prefs.bin.
Configuration restored from src/tests/dbus-tests/targetcli_config.json
Traceback (most recent call last):
  File "src/tests/dbus-tests/run_tests.py", line 192, in <module>
    daemon_bin = find_daemon(projdir, args.system)
  File "src/tests/dbus-tests/run_tests.py", line 31, in find_daemon
    return daemon_bin
UnboundLocalError: local variable 'daemon_bin' referenced before assignment

**Comment by pothos** [comment]
That's interesting, maybe more races could be discovered in very slow and very fast configurations.

Blivet is a GUI similar to GNOME Disks but not relying on UDisks, you can use it e.g. in the Fedora installer.

Try this patch for the time being:

```
diff --git a/src/tests/dbus-tests/run_tests.py b/src/tests/dbus-tests/run_tests.py
index 168ca23d..6994cd86 100755
--- a/src/tests/dbus-tests/run_tests.py
+++ b/src/tests/dbus-tests/run_tests.py
@@ -28,7 +28,7 @@ def find_daemon(projdir, system):
         if os.path.exists('/usr/libexec/udisks2/udisksd'):
             daemon_bin = 'udisksd'
 
-    return daemon_bin
+    return 'udisksd' #daemon_bin
 
 
 def setup_vdevs():

```

**Comment by psusi** [comment]
Now I get this:

storageobjects or targets present, not restoring
Traceback (most recent call last):
  File "src/tests/dbus-tests/run_tests.py", line 183, in <module>
    setup_vdevs()
  File "src/tests/dbus-tests/run_tests.py", line 40, in setup_vdevs
    assert subprocess.call(["targetcli", "restoreconfig src/tests/dbus-tests/targetcli_config.json"]) == 0
AssertionError

**Comment by psusi** [comment]
Ahh, it seems that when the test suite errors out, it leaves targetcli with a bunch of setups intact, then refuses to run if targetcli has anything setup already.  Does that mean you can't run the test suite if you normally have say, an iSCSI disk set up in targetcli?

Test passes with the 8 cpu config.  Rebooting the VM now to put it back to a single core.

**Comment by pothos** [comment]
I ran into the same issue and forgot to post the solution: `sudo targetcli clearconfig confirm=True`

I'm curious if the python test can produce the same race. And if it disappears when you build UDisks with the fix in https://github.com/storaged-project/udisks/pull/574

**Comment by psusi** [comment]
Strange... I ran the test case several times and it kept passing.  I checked g-d-u again and it errored out 3/4 times.

**Comment by pothos** [comment]
Hm, then maybe both the UDisks update as well as Python is too slow, shadowing the race possibility ;)

**Comment by pothos** [comment]
Closing as it was merged last week.
