### ISSUE TITLE
“Timed out waiting for object” trying to mount a partition inside an image

### ISSUE THREAD

**Issue by rgaudin** [storaged-project/udisks#580]
Not sure this is the proper place to report to as I couldn't find similar issues but hopefully you'll show me out if this is not the right place.

On Ubuntu 18.04, I am now getting errors mounting an image file while it used to work properly in the past.

```
kelson@camber:/tmp$ udisksctl loop-setup --offset 7000031744 --size 55532878336 --file /media/backup/plug-2018_09_18-22_49_34.ERROR.img --no-user-interaction
Error setting up loop device for /media/backup/plug-2018_09_18-22_49_34.ERROR.img: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating /dev/loop5Timed out waiting for object
```

* the image has been created with `qemu-img`.
* The offset matches the third partition (exfat) of a 3 partitions table.
* I have been mounting images using the above command for a long time without any issue.
* Since this Sunday, I am getting the mentioned error message.
* I am getting this out of a freshly started system.

Logs
[udevadm-info.txt](https://github.com/storaged-project/udisks/files/2397161/udevadm-info.txt)
[udiskctl-dump.txt](https://github.com/storaged-project/udisks/files/2397162/udiskctl-dump.txt)
[mountinfo.txt](https://github.com/storaged-project/udisks/files/2397163/mountinfo.txt)
[gvfs-mount-li.txt](https://github.com/storaged-project/udisks/files/2397164/gvfs-mount-li.txt)
[gvfs-mount-io.txt](https://github.com/storaged-project/udisks/files/2397165/gvfs-mount-io.txt)
[udevadm-monitor.txt](https://github.com/storaged-project/udisks/files/2397166/udevadm-monitor.txt)

**Comment by vpodzime** [comment]
What if you try to use `losetup` to set the device up?

**Comment by rgaudin** [comment]
Works completely fine with `losetup`, I forgot to mention it.

**Comment by vpodzime** [comment]
Can you please run `udisksctl monitor` in parallel to the `loop-setup` command and attach the recorded output too?

**Comment by rgaudin** [comment]
Well it worked today ; I restarted my computer and it still worked. I'll post it whenever this appears again.

**Comment by vpodzime** [comment]
> Well it worked today ; I restarted my computer and it still worked. I'll post it whenever this appears again.

Cool! Thanks for letting us know!

**Comment by tbzatek** [comment]
@rgaudin, is this still a problem? Have you managed to reproduce the issue?

**Comment by rgaudin** [comment]
Yes unfortunately, the problem is still there. It's not on _my_ computer but @kelson42's. I'll try to post logs with a clean try.

**Comment by z-s-e** [comment]
I have seen the same issue. Via googling I also found [this](https://www.reddit.com/r/archlinux/comments/ife9fi/udisks2_cant_mount_iso_images/), so something is definitely up. It is very inconsistent to reproduce, but when the issue happens, it seems to persist, i.e. repeating the loop-setup command will continue to fail. Very weird. I'll add that for me this issue only happened inside an arch Linux qemu VM as of yet, and VMs have sometimes a bit unusual timings, triggering races more easily, which this kind of seems to be.

I was running `udisksctl monitor` while the bug happened once and it didn't show anything (besides "The udisks-daemon is running") as I ran the loop-setup command.

**Comment by tbzatek** [comment]
Ah! So this is #819. The issue was there probably since the beginning, perhaps more affected by changes in recent kernels and even more pronounced by recent changes to UDisks core.

Feel free to test the pull request and shout if it's still not fixed.
