### ISSUE TITLE
Specifying default mount options for certain partition types (fat32/ntfs)

### ISSUE THREAD

**Issue by birdie-github** [storaged-project/udisks#609]
Back when we had HAL I had this configuration file for mounting FAT32 and NTFS partitions under Linux:

```xml
cat /etc/hal/fdi/policy/20-fs_options.fdi

<?xml version="1.0" encoding="UTF-8"?>

<deviceinfo version="0.2">
	<device>
		<match key="volume.fstype" string="ntfs">
			<append key="volume.mount.valid_options" type="strlist">noatime,uid=500,fmask=0133,dmask=0022,nls=utf8,rw</append>
		</match>
		<match key="volume.fstype" string="vfat">
			<append key="volume.mount.valid_options" type="strlist">noatime,showexec,iocharset=utf8,uid=500,gid=500,codepage=866,fmask=0111,dmask=0000,umask=0000,quiet,usefree,shortname=mixed</append>
		</match>
	</device>
</deviceinfo>
```

How can I do something similar with udisks? I do **not** want to specify mount options individually for 100+ flash disks that I have laying around.

I've found this patch on the Internet ( [[PATCH RFC] udisks2 mount options configuration files](https://lists.freedesktop.org/archives/devkit-devel/2015-April/001668.html) ) but it looks like it's never been merged. Why?

Also, I've found this abandoned feature request: [udisks: Allow extra mount options from udev rules](https://bugs.freedesktop.org/show_bug.cgi?id=33461)

**Comment by tbzatek** [comment]
Not at the moment though we've been wanting such feature for a long time. A policy file doesn't look that bad. We would like to tweak per-device (single) options as well in a persistent way, however use case needs to be defined first in cooperation with desktop environments that would present some GUI for that.

The linked mailing list thread is a good start and we should definitely consider the points raised in https://bugs.freedesktop.org/show_bug.cgi?id=33461 as well.

This needs more work.

**Comment by birdie-github** [comment]
To be fair I hate this XML format and I'd be glad if we had something akin to an INI file. XML files are great for machine generation/parsing but they are not really user friendly.

People have been asking for this feature for over three years now, ever since since HAL was replaced with DeviceKit and then DeviceKit was deprecated in favor of udisks. What's taking you so long to figure it out? I do understand that you want this feature to be exposed via GUI but DEs are usually slow to pick up the features added upstream, so it makes a lot of sense to implement it here and now using e.g. a system wide configuration file for all the partitions.

**Comment by tbzatek** [comment]
> People have been asking for this feature for over three years now, ever since since HAL was replaced with DeviceKit and then DeviceKit was deprecated in favor of udisks. What's taking you so long to figure it out?

Historical reasons of the original UDisks author and different priorities of the current staff. See e.g. https://lists.freedesktop.org/archives/devkit-devel/2015-April/001675.html where we would still like to find out what the original reason was.

> I do understand that you want this feature to be exposed via GUI but DEs are usually slow to pick up the features added upstream, so it makes a lot of sense to implement it here and now using e.g. a system wide configuration file for all the partitions.

We still have tight relation to GVfs and the Gnome team so reaching them for UX proposal shouldn't be that much of a problem. E.g. the work on both sides can be well coordinated here, we just have to find out requirements first (of which the system-wide policy is one of them).

**Comment by vpodzime** [comment]
@tbzatek I've added a new `config` label so that we can group all the issues/RFEs related to the fact that we don't have any good configuration file(s). Feel free to add it to the other related issues.

**Comment by tbzatek** [comment]
> @tbzatek I've added a new `config` label so that we can group all the issues/RFEs related to the fact that we don't have any good configuration file(s). Feel free to add it to the other related issues.

I've decided to use the _Projects_ feature instead. There's too many issues eligible for the _config_ label and would mix with other features that would be great to keep separate. For now I've grouped issues related to configurable mount options. The use of kanban board might not be the best way, at least it provides a level of grouping and view on the grouped issues.

**Comment by tbzatek** [comment]
Proposal about the configurable mount options: https://gist.github.com/tbzatek/b801f352df496b5e5ecc5bac2fd4a5f0

I've tried to incorporate multiple use cases and suggestions collected via different bug trackers. It may look complex, however each level has its use case.

@vojtechtrefny, @vpodzime: please review, comment and ACK/NACK. I don't want to start coding until we all agree about the design. Please also let me know how understandable my writing is. There's going to be extensive documentation in either case. May need some drawings/diagrams though.
