### ISSUE TITLE
Don't wake sleeping HDDs each time an unrelated disk is mounted/unmounted

### ISSUE THREAD

**Issue by vedgy** [storaged-project/udisks#611]
Whenever I mount/unmount any disk via GNOME/XFCE GUI or via `gio mount` or via `udisksctl`, my backup HDD that has an unmounted ext4-formatted partition is waked from sleep. My other HDD has only NTFS-formatted partitions and is not waked. The same issue was reported [here](https://unix.stackexchange.com/questions/457729/ubuntu-18-04-mount-umount-causes-drives-resume-from-standby-state). This issue encourages using inferior filesystems such as NTFS for backup disks, which I don't think is `udisks` developers' intention.

By wrapping `dumpe2fs` into a script and logging the command line and `pstree` output as described in [this answer](https://unix.stackexchange.com/a/408763), I verified that the top-level `udisksd` process executes `dumpe2fs -h <device>` for each ext4 partition on each disk device after a single mount or unmount command. It even executes this command twice for the partition that is [un]mounted (if it is an ext4 partition).

I think that the specific tail of the call stack responsible for waking HDDs is this: [`udisks_linux_filesystem_update`](https://github.com/storaged-project/udisks/blob/3b4be5f3a2b5c4ded0a9bf4370cc7ef64c6a60d4/src/udiskslinuxfilesystem.c#L201) calls [`bd_fs_ext4_get_info`](https://github.com/storaged-project/libblockdev/blob/d4f53f6add07a936ace8dbd7cb50332ef9cf9c9e/src/plugins/fs/ext.c#L653) for each ext4 partition, which in turn calls [`ext_get_info`](https://github.com/storaged-project/libblockdev/blob/d4f53f6add07a936ace8dbd7cb50332ef9cf9c9e/src/plugins/fs/ext.c#L579), which executes `dumpe2fs -h <device>`. The end result is probably the same for _ext3_ and _ext2_ filesystems because of similarly called and implemented `bd_fs_ext3_get_info` and `bd_fs_ext2_get_info`.

I renamed my `/usr/bin/dumpe2fs` utility and the issue disappeared: no matter how many disks I mount/unmount as described above, both my backup HDDs remain sleeping. This is clearly not a good workaround because this low-level filesystem utility may be used for useful purposes by other programs, so renaming it could cause different issues. Could _udisksd_ skip getting info from sleeping devices? Or at least could a user configure _udisksd_ to skip querying certain devices? Setting `ENV{UDISKS_IGNORE}="1"` for the sleeping HDD doesn't protect it from waking.

**Comment by tbzatek** [comment]
Good catch, we should check the power state first.

**Comment by vedgy** [comment]
I have noticed that _udisksd_ also executes `dumpe2fs` multiple times for each ext4 partition during startup. I wonder why are these calls needed at all? Maybe some of the calls are redundant? For example, perhaps executing `dumpe2fs` on the one partition that is being mounted/unmounted is sufficient?

**Comment by vojtechtrefny** [comment]
`lsblk` show size of the device, not the filesystem -- it is possible to have filesystem smaller (or even larger) than the underlying block device. But you are right, we definitely shouldn't update all devices in `utab_monitor_on_entry_added/removed`

**Comment by ConteZero** [comment]
I've tested the [patch](https://github.com/tblume/udisks2/pull/1) from @tblume and it solves the problem for me.

**Comment by tblume** [comment]
Ok, done.

**Comment by vedgy** [comment]
> But you are right, we definitely shouldn't update all devices in `utab_monitor_on_entry_added/removed`

Do you mean that `update_all_block_objects()` shouldn't be called from these callbacks? Since they currently do nothing else, can the `utab_monitor_on_entry_added/removed()` functions be removed along with their corresponding `g_signal_connect()` statements?
What about `fstab_monitor_on_entry_added/removed()` and `crypttab_monitor_on_entry_added/removed()`?

**Comment by Markus-N** [comment]
I'm running udisks2 2.9.2-1 on ArchLinux, and mounting or unmounting a USB device still wakes up my HDD's.

This is my media layout:  
System on a NVME device plus a md raid for data, both with with dm-crypt and LVM.

I've followed this advice to replacedumpe2fs with a logger:  
https://unix.stackexchange.com/questions/408757/why-is-dumpe2fs-called-without-user-interaction/408763  
and when I mount a USB device, dumpe2fs is called for the dm devices that correspond to the logical volumes, e.g. /dev/dm-6.

Should this issue be reopened or should I open a new one ?

**Comment by tbzatek** [comment]
Please open a new ticket for this. With the last patch only direct associated drive is checked and more complex layering is not taken in account.

Could you also post `udisksctl dump` output there to understand your storage topology?
