### ISSUE TITLE
udisks without polkit

### ISSUE THREAD

**Issue by agners** [storaged-project/udisks#615]
It seems that udisks has a hard dependency on polkit.

It this dependency strictly necessary?

Use case: on an space restricted embedded device we just use D-Bus with fixed policies. We consider using udisks to control device mounting/unmounting/device notifications via D-Bus.

**Comment by agners** [comment]
Hm, I see. It seems that polkit interaction is rather separated, so with some minimal code change the polkit library could even made optional?

**Comment by tbzatek** [comment]
Please see my answer: https://github.com/storaged-project/udisks/pull/857#issuecomment-1023357601

Closing for the time being.
