### ISSUE TITLE
Backplane LED integration

### ISSUE THREAD

**Issue by hjmallon** [storaged-project/udisks#626]
I think it could be useful for various UDisks based UIs/CLIs to have integration with Backplane LEDs. The most complete project I have found for this currently is LedMon, which is also GPL2. https://github.com/intel/ledmon

Maybe UDisks could use that (or code from that project) to provide locate / error LED control through the UDisks DBus API?

**Comment by vpodzime** [comment]
We already have an existing integration of *libstoragemgmt*:
http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Drive.LsmLocal.html

Or is this about something else?

**Comment by hjmallon** [comment]
That sounds very similar to what I am looking for. That object doesn't appear on my machine though. Maybe the backplane isn't supported. I will do some digging.

**Comment by vpodzime** [comment]
> That object doesn't appear on my machine though.

Make sure you have a new-enough *UDisks 2* **and** the *LSM* module installed.

**Comment by hjmallon** [comment]
It turns out CentOS7 builds without LSM plugin. I have rebuilt with the plugin but still nothing. Maybe it only works with SAS backplanes? Ledmon (mentioned above) works with ours. Maybe some code can be reused in libstoragemgmt. If I can prove that it is a libstoragemgmt feature request I will close this and move it upstream.

**Comment by vojtechtrefny** [comment]
If you are testing this manually, make sure to enable the module -- http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Manager.html#gdbus-method-org-freedesktop-UDisks2-Manager.EnableModules
But it is also possible that libstoragemgmt just doesn't support your hardware.

**Comment by vpodzime** [comment]
> It turns out CentOS7 builds without LSM plugin. I have rebuilt with the plugin but still nothing.

You can try packages from our daily builds: https://copr.fedorainfracloud.org/coprs/g/storage/udisks-daily/

**Comment by hjmallon** [comment]
I was blocked by seeing this issue (https://github.com/libstorage/libstoragemgmt/issues/383), also libstoragemgmt doesn't support as many types of hardware as the Intel ledmon. Anyway my problem is sorted now so I will close this, thanks for you help.

**Comment by vpodzime** [comment]
>  Anyway my problem is sorted now so I will close this, thanks for you help.

Thanks for the update!
