### ISSUE TITLE
Unable to mount davfs

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [storaged-project/udisks#627]
It would be cool to have support for mounting `davfs`. Current attempts results with following:
```
$ udisksctl mount -t davfs -b https://localhost/webdav
Error looking up object for device https://localhost/webdav
```

**Comment by vpodzime** [comment]
I believe [GVfs](https://en.wikipedia.org/wiki/GVfs) has support for that.

**Comment by mateusz-gozdek-sociomantic** [comment]
Gvfs is now deprecated (no `gvfs-mount` anymore), but I just found out, that `gio mount davs://localhost/webdav` is able to handle that. 

Feel free to close then, if you find it appropriate :+1: Thanks!

**Comment by vpodzime** [comment]
> Feel free to close then, if you find it appropriate +1 Thanks!

Done :)
