### ISSUE TITLE
'Project-Id-Version' still has the initial default value

### ISSUE THREAD

**Issue by scootergrisen** [storaged-project/udisks#628]
Seems like the value for Project-Id-Version was changed from "udisks" to "PACKAGE VERSION" in "Translations: move from transifex to zanata":
https://github.com/storaged-project/udisks/commit/edc5016f337ba489febfb0a93c8fcd54e2dd6a37#diff-a24a858b6e7f98ed5bb1acfd64a98e34

I would like it to says "udisks" for all the po files and pot files if there is one:

    "Project-Id-Version: udisks\n"

If i run msgfmt -cv file.po i get:

    warning: header field 'Project-Id-Version' still has the initial default value

**Comment by vpodzime** [comment]
I cannot see `PACKAGE VERSION` in any of the *.po* files that we have in the repo now:

```
$ grep -h Project-Id-Version po/*.po|sort|uniq
"Project-Id-Version: udisks 2.8.2\n"
"Project-Id-Version: udisks\n"
```

These files are pulled from zanata and are based on the *.pot* file that is generated by our Makefiles and contains the correct package name and version:

```
$ head po/udisks2.pot 
# SOME DESCRIPTIVE TITLE.
# This file is put in the public domain.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: udisks 2.8.4\n"
"Report-Msgid-Bugs-To: https://github.com/storaged-project/udisks/issues\n"
"POT-Creation-Date: 2019-06-16 20:29+0200\n"
```

I don't think there's anything we can do here. Feel free to reopen the issue.
