### ISSUE TITLE
TakeOwnership follows symlinks to directories

### ISSUE THREAD

**Issue by vojtechtrefny** [storaged-project/udisks#634]
See the `recursive_chown` implementation -- https://github.com/storaged-project/udisks/blob/master
/src/udiskslinuxfilesystemhelpers.c#L56-L58 -- `G_FILE_TEST_IS_DIR` returns True for directory symlinks too, so we can potentially follow a symlink outside the filesystem and change owners of files/folders on a different one.
There is also a potential race condition in checking if file/directory is a symlink without somehow "locking" the device/folder.

**Comment by tbzatek** [comment]
Agree, looks like a bug.

**Comment by vpodzime** [comment]
> "locking" the device/folder.

or using `openat()/fstatat()`

**Comment by tbzatek** [comment]
We've discussed the race condition thing in person however we still can't understand why should it be a problem or what the security implications are. Either the whole tree should be locked prior to doing further changes or we just simply expect nobody would mess up with the tree in the meanwhile (shifting the responsibility to the user).

Any kind of potentially recursive locking should be done in a way that wouldn't cause system resources exhaustion (e.g. number of open files).

I can imagine intruders from other daemons doing read-only stuff like sniffing MIME types and thumbnails but that shouldn't bother us (except of potential unmount issues - that's a rather separate issue though).

**Comment by tbzatek** [comment]
Note to myself: when not mounted mount it to a separate mount namespace to prevent intrusion and warn if it fails.

**Comment by tbzatek** [comment]
> > "locking" the device/folder.
> 
> or using `openat()/fstatat()`

Yeah, that's a good idea, however leading to filedescriptor exhaustion due to recursion :tired_face:
