### ISSUE TITLE
FS.test_existing_manual_mount_point fails with --enable-fhs-media

### ISSUE THREAD

**Issue by mbiebl** [storaged-project/udisks#640]
Version: 2.8.2

Running the integration-test, I get the following failure
```
# src/tests/integration-test FS.test_existing_manual_mount_point
Testing installed system binaries
daemon path: /usr/lib/udisks2/udisksd
[ 1241.860207] scsi host2: scsi_debug: version 0188 [20180128]
[ 1241.860207]   dev_size_mb=61, opts=0x0, submit_queues=1, statistics=0
[ 1241.864009] scsi 2:0:0:0: Direct-Access     Linux    scsi_debug       0188 PQ: 0 ANSI: 7
[ 1241.867752] sd 2:0:0:0: Power-on or device reset occurred
[ 1241.869163] sd 2:0:0:0: Attached scsi generic sg1 type 0
[ 1241.876826] sd 2:0:0:0: [sda] 124928 512-byte logical blocks: (64.0 MB/61.0 MiB)
[ 1241.882342] sd 2:0:0:0: [sda] Write Protect is off
[ 1241.891543] sd 2:0:0:0: [sda] Write cache: enabled, read cache: enabled, supports DPO and FUA
[ 1241.990849] sd 2:0:0:0: [sda] Attached SCSI disk
[ 1242.099805] scsi host3: scsi_debug: version 0188 [20180128]
[ 1242.099805]   dev_size_mb=61, opts=0x0, submit_queues=1, statistics=0
[ 1242.108055] scsi 3:0:0:0: CD-ROM            Linux    scsi_debug       0188 PQ: 0 ANSI: 7
[ 1242.115024] sr 3:0:0:0: Power-on or device reset occurred
[ 1242.129799] sr 3:0:0:0: [sr1] scsi-1 drive
[ 1242.131448] sr 3:0:0:0: Attached scsi generic sg2 type 5
Set up test device: r/w: /dev/sda, r/o: /dev/sr1
test_existing_manual_mount_point (__main__.FS)
fs: does not reuse existing manual mount point ... [ 1243.867960] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: (null)
[ 1244.113344] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: (null)
ERROR

======================================================================
ERROR: test_existing_manual_mount_point (__main__.FS)
fs: does not reuse existing manual mount point
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 786, in test_existing_manual_mount_point
    self.assertEqual(new_mount_path, mount_path + '1')
  File "/usr/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.7/unittest/case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.7/unittest/case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '/media/root/udiskstest' != '/media/root/udiskstest1'
- /media/root/udiskstest
+ /media/root/udiskstest1
?                       +


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/tests/integration-test", line 788, in test_existing_manual_mount_point
    os.rmdir(mount_path)
FileNotFoundError: [Errno 2] No such file or directory: '/media/root/udiskstest'

----------------------------------------------------------------------
Ran 1 test in 1.398s

FAILED (errors=1)
[ 1244.286273] print_req_error: I/O error, dev sda, sector 544
[ 1244.288158] print_req_error: I/O error, dev sda, sector 544
[ 1244.290047] buffer_io_error: 87 callbacks suppressed
[ 1244.290049] Buffer I/O error on dev sda, logical block 68, async page read
[ 1244.294194] print_req_error: I/O error, dev sda, sector 544
[ 1244.295207] Buffer I/O error on dev sda, logical block 68, async page read
[ 1244.296442] print_req_error: I/O error, dev sda, sector 544
[ 1244.297443] Buffer I/O error on dev sda, logical block 68, async page read
[ 1244.303971] sd 2:0:0:0: [sda] Synchronizing SCSI cache
[ 1244.310028] Buffer I/O error on dev sda, logical block 68, async page read
```

**Comment by tbzatek** [comment]
Interesting, we should try to reproduce this in our CI first, try to find the difference in the test environment.

**Comment by mbiebl** [comment]
It's a pretty standard Debian Sid container. The test was run using autopkgtest.

**Comment by mbiebl** [comment]
@tbzatek I assume the main difference is, that the Debian package uses `--enable-fhs-media`

**Comment by mbiebl** [comment]
I can confirm that after switching to `--disable-fhs-media`, the test passes. Updated the bug title accordingly.

**Comment by vojtechtrefny** [comment]
I was able to reproduce this using one of our CI Debian machines. It failed after ~20 runs so it is possible it happens even without `--enable-fhs-media`.

**Comment by mbiebl** [comment]
@vojtechtrefny hm, interesting. This would indicate there is a race condition somewhere. So far I haven't been able to reproduce the issue with `--disable-fhs-media`.

**Comment by tbzatek** [comment]
I wasn't that lucky and haven't managed to reproduce the issue on a clean Debian unstable installation. Let me have a look at the code, perhaps we could find something.

Unrelated, note to myself:
https://github.com/storaged-project/udisks/blob/fb5ff66d5a98e7b88b815ecdec50c8e90ffa57f3/src/udisksstate.c#L2110-L2115
_(Not good, first we dereference the pointer and then we check if it's NULL. The whole commit 6be904fd looks suspicious...)_

**Comment by mbiebl** [comment]
@tbzatek have you tried with `--enable-fhs-media` ?

**Comment by tbzatek** [comment]
> @tbzatek have you tried with `--enable-fhs-media` ?

I did, tested it both ways.

**Comment by mbiebl** [comment]
Hi @tbzatek , have you had chance to further look into this? I'm still running into this problem with 2.8.3

**Comment by tbzatek** [comment]
> Hi @tbzatek , have you had chance to further look into this? I'm still running into this problem with 2.8.3

I've just tried to reproduce the issue again on two different systems, without luck. Let me read the code instead and come up with potential changes (if any).

**Comment by tbzatek** [comment]
Ah, now I finally get what's going on. Something removed the mountpoint directory created by the test case. That explains the additional exception while handling the first exception. The mountpoint path calculation is correct at last.

The udisks-2.8.3 release includes a49399b3708ac4f10b026ae4636f7bddb917cc06 which takes care of a lingering mountpoint directory removal after successful unmount by running an iteration of `UDisksState` cleanup. There's kind of a queue naturally provided by the separate mainloop running in the thread. We just inject a task (that is only executed once mainloop iterates, i.e. after completing already running cleanup task) and wait until it's finished. So in the worst case there would be two cleanups ran before the unmount call returns, no harm done in this case.

---

There are couple of possible explanations. There might be something external like `systemd` that cleans up the mountpoint itself. There might be also a race condition somewhere in udisks that triggers the cleanup with old/invalid metadata.

Another thing is that we may need to flush queued events in the state cleanup thread, in case the task injection reorders priorities, etc.

---

Anyway, could you please run the `integration-test` with `--log-file=` argument and share the daemon log file with us?

What is the filesystem of `/media` btw.? Is it a local filesystem, NFS or `tmpfs`?
