### ISSUE TITLE
udisksd dumps core on stopping mdraid device

### ISSUE THREAD

**Issue by marusak** [storaged-project/udisks#643]
This comes from [cockpit testsuite](https://github.com/cockpit-project/cockpit/pull/11326) where on newer udisks (at least from version `udisks2-2.8.1-3` on debian-testing) `udisksd` dumps core.

Descriptive reproducer (will try to prepare script reproducer):
Right after assembling an array the device might be busy from udev rules probing or the mdadm monitor - in this short time try to stop the device, you should get message from [here](https://github.com/fluxer/udisks/blob/master/src/udiskslinuxmdraid.c#L843) with error message `fail to stop array /dev/md127: Device or resource busy`. Then try to stop the device again, which succeeds. Then other action such as starting it again ends up with dumping core. I am not able to reproduce this crash if stopping did not encounter the "device busy' error message.

For bull backtrace see attached file.

    Stack trace of thread 7543:
    #0  0x00007feeb381ba2d magazine_chain_pop_head (libglib-2.0.so.0)
    #1  0x00007feeb381beb9 g_slice_alloc0 (libglib-2.0.so.0)
    #2  0x00007feeb3a28dbd reply_cb (libgio-2.0.so.0)
    #3  0x00007feeb39c7719 g_task_return_now (libgio-2.0.so.0)
    #4  0x00007feeb39c8196 g_task_return (libgio-2.0.so.0)
    #5  0x00007feeb3a1db1a g_dbus_connection_call_done (libgio-2.0.so.0)
    #6  0x00007feeb39c7719 g_task_return_now (libgio-2.0.so.0)
    #7  0x00007feeb39c7759 complete_in_idle_cb (libgio-2.0.so.0)
    #8  0x00007feeb37fddd8 g_main_dispatch (libglib-2.0.so.0)
    #9  0x00007feeb37fe1c8 g_main_context_iterate (libglib-2.0.so.0)
    #10 0x00007feeb37fe4c2 g_main_loop_run (libglib-2.0.so.0)
    #11 0x00007feeb3c153f3 polkit_authority_check_authorization_sync (libpolkit-gobject-1.so.0)
    #12 0x000055c33f0a0147 udisks_daemon_util_check_authorization_sync_with_error (udisksd)
    #13 0x000055c33f0a0a1c udisks_daemon_util_check_authorization_sync (udisksd)
    #14 0x000055c33f09733a handle_start (udisksd)
    #15 0x00007feeb2dd18ee ffi_call_unix64 (libffi.so.6)
    #16 0x00007feeb2dd12bf ffi_call (libffi.so.6)
    #17 0x00007feeb38e2472 g_cclosure_marshal_generic (libgobject-2.0.so.0)
    #18 0x00007feeb38e1c7d g_closure_invoke (libgobject-2.0.so.0)
    #19 0x00007feeb38f4b9d signal_emit_unlocked_R (libgobject-2.0.so.0)
    #20 0x00007feeb38fd46f g_signal_emitv (libgobject-2.0.so.0)
    #21 0x00007feeb3b2b33a n/a (libudisks2.so.0)
    #22 0x00007feeb3a345c2 dispatch_in_thread_func (libgio-2.0.so.0)
    #23 0x00007feeb39c82c3 g_task_thread_pool_thread (libgio-2.0.so.0)
    #24 0x00007feeb3826dc3 g_thread_pool_thread_proxy (libglib-2.0.so.0)
    #25 0x00007feeb3826425 g_thread_proxy (libglib-2.0.so.0)
    #26 0x00007feeb3796fa3 start_thread (libpthread.so.0)
    #27 0x00007feeb36c782f __clone (libc.so.6)
    
    Stack trace of thread 307:
    #0  0x00007feeb36bcb69 __GI___poll (libc.so.6)
    #1  0x00007feeb37fe136 g_main_context_poll (libglib-2.0.so.0)
    #2  0x00007feeb37fe4c2 g_main_loop_run (libglib-2.0.so.0)
    #3  0x000055c33f072808 main (udisksd)
    #4  0x00007feeb35f209b __libc_start_main (libc.so.6)
    #5  0x000055c33f07291a _start (udisksd)
    
    Stack trace of thread 314:
    #0  0x00007feeb36bcb69 __GI___poll (libc.so.6)
    #1  0x00007feeb37fe136 g_main_context_poll (libglib-2.0.so.0)
    #2  0x00007feeb37fe25c g_main_context_iteration (libglib-2.0.so.0)
    #3  0x00007feeb37fe2a1 glib_worker_main (libglib-2.0.so.0)
    #4  0x00007feeb3826425 g_thread_proxy (libglib-2.0.so.0)
    #5  0x00007feeb3796fa3 start_thread (libpthread.so.0)
    #6  0x00007feeb36c782f __clone (libc.so.6)
    
    Stack trace of thread 322:
    #0  0x00007feeb36bcb69 __GI___poll (libc.so.6)
    #1  0x00007feeb37fe136 g_main_context_poll (libglib-2.0.so.0)
    #2  0x00007feeb37fe4c2 g_main_loop_run (libglib-2.0.so.0)
    #3  0x00007feeb3a2bf66 gdbus_shared_thread_func (libgio-2.0.so.0)
    #4  0x00007feeb3826425 g_thread_proxy (libglib-2.0.so.0)
    #5  0x00007feeb3796fa3 start_thread (libpthread.so.0)
    #6  0x00007feeb36c782f __clone (libc.so.6)
    
    Stack trace of thread 330:
    #0  0x00007feeb36c22a9 syscall (libc.so.6)
    #1  0x00007feeb3847f9f g_cond_wait (libglib-2.0.so.0)
    #2  0x00007feeb37d00ab g_async_queue_pop_intern_unlocked (libglib-2.0.so.0)
    #3  0x00007feeb37d04d7 g_async_queue_pop (libglib-2.0.so.0)
    #4  0x000055c33f077e09 probe_request_thread_func (udisksd)
    #5  0x00007feeb3826425 g_thread_proxy (libglib-2.0.so.0)
    #6  0x00007feeb3796fa3 start_thread (libpthread.so.0)
    #7  0x00007feeb36c782f __clone (libc.so.6)
    
    Stack trace of thread 352:
    #0  0x00007feeb36bcb69 __GI___poll (libc.so.6)
    #1  0x00007feeb37fe136 g_main_context_poll (libglib-2.0.so.0)
    #2  0x00007feeb37fe4c2 g_main_loop_run (libglib-2.0.so.0)
    #3  0x000055c33f0a2480 udisks_state_thread_func (udisksd)
    #4  0x00007feeb3826425 g_thread_proxy (libglib-2.0.so.0)
    #5  0x00007feeb3796fa3 start_thread (libpthread.so.0)
    #6  0x00007feeb36c782f __clone (libc.so.6)

[coredumpctl.log](https://github.com/storaged-project/udisks/files/2962198/coredumpctl.log)

**Comment by tbzatek** [comment]
Hmm, the backtrace looks like an aftermath after memory corruption somewhere else. Is there a chance to get more reliable reproducer?

**Comment by vpodzime** [comment]
ping @marusak

**Comment by marusak** [comment]
We don't see this anymore in CI, so closing.
