### ISSUE TITLE
Bugfix: Change the default uid and gid of ntfs-3g to 1000 (to avoid problems with WINE)

### ISSUE THREAD

**Issue by Zeioth** [storaged-project/udisks#653]
I've been redirected here from [gfvs bugtracker](https://gitlab.gnome.org/GNOME/gvfs/issues/386) (What thunar/dolphin/nemo uses to mount units)

**ISSUE**
By default udisks mount my ntfs-3g unit like:

    /run/media/zeioth/datos        /dev/sdc1    fuseblk    rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096

This, cause problems with some programs, like wine, for example. If you try to create a wineprefix in an ntfs-3g unit mounted with the previous line, and run the next command, It will [fail with writing errors](https://pastebin.com/raw/gCWPTSNk). 

    WINEPREFIX="/my_ntfs_hd/prefix/" winecfg

**SOLUTION**
The solution to this issue is mounting the unit with uid and gid 1000, like this:

    /run/media/zeioth/datos        /dev/sdc1    fuseblk    rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,default_permissions,allow_other,blksize=4096

**PROPOSAL**
Please, change the default uid and gid of ntfs-3g units to 1000 by default. 
For more info about this issue, see [this](https://gitlab.gnome.org/GNOME/gvfs/issues/386).

**Comment by tbzatek** [comment]
What are your udisks and ntfs-3g versions btw.? We recently introduced _"windows_names"_ mount option by default that may cause problems writing non-Windows compliant file names.

**Comment by Zeioth** [comment]
I'm on arch (Antergos, no AUR):
udisks2: 2.8.2-1
ntfs-3g: 2917.3.23.3

I'm not 100% sure if this issue was introduced recently. I'm only sure that wine fails on ntfs-3g units without uid and gid = 1000. Fortunately this issue is very easy to test with the line:

    WINEPREFIX="/my_ntfs_hd/prefix/" winecfg

**Comment by tannisroot** [comment]
I can confirm this. Even Valve acknowledges this issue: https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows

**Comment by Zeioth** [comment]
gfvs was willing to implement this behavior as default, but they tough it would be better to add it to udisks instead.

**Comment by vojtechtrefny** [comment]
This should be already working, we are passing the `uid=` and `gid=` options to mount:

```
Apr 17 08:19:00 localhost.localdomain ntfs-3g[25046]: Global ownership and permissions enforced, configuration type 7
Apr 17 08:19:00 localhost.localdomain ntfs-3g[25046]: Mount options: rw,nodev,nosuid,uhelper=udisks2,allow_other,nonempty,relatime,default_permissions,fsname=/dev/vde1,blkdev,blksize=4096
Apr 17 08:19:00 localhost.localdomain ntfs-3g[25046]: Cmdline options: rw,nodev,nosuid,windows_names,uid=1001,gid=1001,uhelper=udisks2
Apr 17 08:19:00 localhost.localdomain ntfs-3g[25046]: Mounted /dev/vde1 (Read-Write, label "", NTFS 3.1)
Apr 17 08:19:00 localhost.localdomain ntfs-3g[25046]: Version 2017.3.23 integrated FUSE 28
Apr 17 08:19:00 localhost.localdomain udisksd[724]: Mounted /dev/vde1 at /run/media/vtrefny/4CFA72A43D09109F on behalf of uid 1001
```

owner of the directory is also correctly set:

```
$ ls -la /run/media/vtrefny/4CFA72A43D09109F
total 4
drwxrwxrwx. 1 vtrefny vtrefny 4096 Apr 17 08:18 .
drwxr-x---+ 3 root    root      60 Apr 17 08:18 ..
```

It's interesting that `/proc/mounts` thinks both `uid` and `gid` is set to `0`:

```
/dev/vde1 /run/media/vtrefny/4CFA72A43D09109F fuseblk rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096 0 0
```

but everything seems to be working, the wine command also works.

**Comment by tannisroot** [comment]
Wine command will work but it will work incorrectly. For example, if you try install Battle.Net on NTFS partition, it will just simply bork out.

**Comment by tbzatek** [comment]
> Wine command will work but it will work incorrectly. For example, if you try install Battle.Net on NTFS partition, it will just simply bork out.

Could you please post some logs of the "bork-out"?

Also I'm wondering what happens if you `touch` a new file somewhere in the mount.

**Comment by tannisroot** [comment]
> Could you please post some logs of the "bork-out"?

I couldn't download Battle.Net at the moment, but here's me trying to create a prefix on my NTFS partition:
[wine.txt](https://github.com/storaged-project/udisks/files/3089418/wine.txt)
>Also I'm wondering what happens if you touch a new file somewhere in the mount.

It creates a file just fine.
And yeah, I see the same stuff in /proc/mounts.

**Comment by tannisroot** [comment]
>This should be already working, we are passing the uid= and gid= options to mount:

For me, those options are not getting passed? 
```
апр 17 19:05:11 shinji ntfs-3g[25775]: Version 2017.3.23 external FUSE 29
апр 17 19:05:11 shinji ntfs-3g[25775]: Mounted /dev/sdb1 (Read-Write, label "", NTFS 3.1)
апр 17 19:05:11 shinji ntfs-3g[25775]: Cmdline options: rw,nosuid,nodev,nofail
апр 17 19:05:11 shinji ntfs-3g[25775]: Mount options: rw,nosuid,nodev,nofail,allow_other,nonempty,relatime,fsname=/dev/sdb1,blkdev,blksize=4096
апр 17 19:05:11 shinji ntfs-3g[25775]: Ownership and permissions disabled, configuration type 7
апр 17 19:05:11 shinji udisksd[1029]: Mounted /dev/sdb1 (system) at /mnt/70B49DB8B49D8170 on behalf of uid 1000

```

**Comment by tbzatek** [comment]
@tannisroot, do you have a record for this device in `/etc/fstab`? You seem to be missing more mount options, like the `windows_names` we've introduced in udisks-2.8.2.

Also noticed the difference from your and @vojtechtrefny's output:
`Global ownership and permissions enforced, configuration type 7`
vs.
`Ownership and permissions disabled, configuration type 7`

**Comment by tannisroot** [comment]
@tbzatek indeed it was, and my udisks version was slightly outdated. Now I have roughly the same output:
```
апр 19 14:30:10 shinji ntfs-3g[2834]: Version 2017.3.23 external FUSE 29
апр 19 14:30:10 shinji ntfs-3g[2834]: Mounted /dev/sdb1 (Read-Write, label "", NTFS 3.1)
апр 19 14:30:10 shinji udisksd[1009]: Mounted /dev/sdb1 at /run/media/alex/70B49DB8B49D8170 on behalf of uid 1000
апр 19 14:30:10 shinji ntfs-3g[2834]: Cmdline options: rw,nodev,nosuid,windows_names,uid=1000,gid=1000,uhelper=udisks2
апр 19 14:30:10 shinji ntfs-3g[2834]: Mount options: rw,nodev,nosuid,uhelper=udisks2,allow_other,nonempty,relatime,default_permissions,fsname=/dev/sdb1,blkdev,blksize=4096
апр 19 14:30:10 shinji ntfs-3g[2834]: Global ownership and permissions enforced, configuration type 7
апр 19 14:30:11 shinji nautilus[2783]: ../glib/gobject/gsignal.c:2423: signal 'can-accept-item' is invalid for instance '0x561f405363b0' of type 'NautilusCanvasViewContainer'
апр 19 14:30:14 shinji gnome-shell[944]: g_environ_setenv: assertion 'value != NULL' failed
```
However, despite this, creation of Wine prefix still fails.

**Comment by vojtechtrefny** [comment]
Looks like the problem is the `windows_names`, because `winecfg` started working after removing it.

**Comment by etienne-lorrain** [comment]
Did noticed root is not able to provide other uid/gid than himself, unless a patch like that is applied:

--- b/src/udiskslinuxfilesystem.c       2017-05-15 22:57:51.000000000 +1200
+++ a/src/udiskslinuxfilesystem.c       2019-04-23 12:58:10.479643958 +0100
@@ -486,7 +486,7 @@
     }
 
   /* .. then check for mount options where the caller is allowed to pass
-   * in his own uid
+   * in his own uid, and root to choose whatever uid/gid
    */
   if (fsmo != NULL)
     {
@@ -498,7 +498,7 @@
               uid = strtol (option + strlen (r_mount_option), &endp, 10);
               if (*endp != '\0')
                 continue;
-              if (uid == caller_uid)
+              if (caller_uid == 0 || uid == caller_uid)
                 {
                   allowed = TRUE;
                   goto out;
@@ -519,7 +519,7 @@
               gid = strtol (option + strlen (r_mount_option), &endp, 10);
               if (*endp != '\0')
                 continue;
-              if (is_uid_in_gid (caller_uid, gid))
+              if (caller_uid == 0 || is_uid_in_gid (caller_uid, gid))
                 {


No support / no copyright claim... Cheers.

**Comment by Zeioth** [comment]
This issue is being documented by valve.
https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows/2d587c281b9dbb482032238b1fde4e6d5a96832e

**Comment by tbzatek** [comment]
The `windows_names` option prevents creating files with a colon ":" character and that's needed for wine:

```
$ WINEPREFIX="/run/media/tbzatek/NTFSTEST/wine" wineboot
wine: created the configuration directory '/run/media/tbzatek/NTFSTEST/wine'
0009:err:file:init_redirects /run/media/tbzatek/NTFSTEST/wine/dosdevices/c:/windows: No such file or directory
000b:err:wineboot:main Cannot set the dir to L"C:\\windows" (2)
```

```
$ mkdir /run/media/tbzatek/NTFSTEST/wine/dosdevices/c:/
mkdir: cannot create directory ‘/run/media/tbzatek/NTFSTEST/wine/dosdevices/c:/’: Invalid argument
```

This is something the configurable mount options will solve, after manually overriding mount options. Much better way is however to keep WINEPREFIX on a local POSIX-compliant filesystem, such as your homedir. I would be worried what happens with the wine prefix after that NTFS drive is connected back to Windows and filesystem check is run on it.

**Comment by tbzatek** [comment]
This can now be overriden through recently introduced Configurable mount options, though a proper solution (moving `WINEPREFIX` away from ntfs) is suggested.
