### ISSUE TITLE
"Error adding /dev/md127 to RAID array /dev/sda" is the wrong way around

### ISSUE THREAD

**Issue by mvollmer** [storaged-project/udisks#660]
It should be "Error adding /dev/sda to RAID array /dev/md127"

https://github.com/storaged-project/udisks/blob/39c7db4c237c786c997600d161a156a0df4ea2e4/src/udiskslinuxmdraid.c#L1216

**Comment by vpodzime** [comment]
You know you can just edit the file here at GH and submit the change as a PR, right? :wink:

**Comment by mvollmer** [comment]
> You know you can just edit the file here at GH and submit the change as a PR, right?

Ahaha, yes, I do! :-) Didn't stop to think long enough, sorry.

**Comment by mvollmer** [comment]
>> You know you can just edit the file here at GH and submit the change as a PR, right?
>
> Ahaha, yes, I do! :-) Didn't stop to think long enough, sorry.

Well... Using GitHub was harder than I thought. I had to edit the file in my own fork, which wasn't up-to-date with your master, so then I just did it the usual way via my local repo.  For my own education, should it have been easier?

**Comment by mvollmer** [comment]
>  I had to edit the file in my own fork,

No, that was the misunderstanding on my part: I was trying to edit via the link from this issue, https://github.com/storaged-project/udisks/blob/39c7db4c237c786c997600d161a156a0df4ea2e4/src/udiskslinuxmdraid.c, but I should have edited from your master.

Ok, time for coffee...

**Comment by vpodzime** [comment]
> I should have edited from your master.

Yup, you open the file from the code tree browser and then edit it, submit as PR. It creates a branch in the repo or in your fork based on what you chose.
