### ISSUE TITLE
UDisksClient should support a custom GDBusConnection

### ISSUE THREAD

**Issue by mwleeds** [storaged-project/udisks#679]
Hi,

I'm looking at making the `UDisksClient` class able to take a `GBusType` argument so that it can connect to the session bus instead of the system bus with its `GDBusObjectManagerClient`, for when the caller is in a unit test and has a GTestDBus daemon set up. Otherwise if we just set `DBUS_SYSTEM_BUS_ADDRESS` to the address of the test dbus-daemon, sometimes the connection held by the `UDisksClient` will close ungracefully with a `SIGTERM` when some I/O happens on it after the test `dbus-daemon` has been killed by `g_test_dbus_down()`.

So the obvious way to do it would be to have a `udisks_client_new_for_bus()` function which would take a `GBusType` argument, set it as a property, and this property would be used in `initable_init` and passed to `udisks_object_manager_client_new_for_bus_sync()`. However the problem is that since `UDisksClient` is a singleton, you're only guaranteed to get an object from `udisks_client_new_for_bus_finish()` that used the bus type you specified if you did the first invocation of `udisks_client_new[_for_bus]()` for the lifetime of your thread, and while that's true in the case of the unit tests I'm looking at, it doesn't seem like a safe assumption to make generally. Does anyone have an idea of a better way to go about this? Perhaps there's a way for the object to only be a singleton if the bus type wasn't specified (and therefore defaults to system)?

**Comment by wjt** [comment]
I suggest that, rather than accepting a `GBusType`, it would be better to add a `_new_for_connection` which accepts a `GDBusConnection *`, and always returns a new object, rather than a singleton.

**Comment by pwithnall** [comment]
Indeed, the standard template that I’ve used for this kind of thing is a constructor which takes a `GDBusConnection` pointer in, and returns you a new object (not a singleton) which uses that connection.

You can then build the system-bus-using singleton object on top of that.

For unit testing, you can then use your new `GDBusConnection`-using constructor with `g_dbus_connection_new_for_address()` and `g_test_dbus_get_bus_address()`.

**Comment by mwleeds** [comment]
> Indeed, the standard template that I’ve used for this kind of thing is a constructor which takes a `GDBusConnection` pointer in, and returns you a new object (not a singleton) which uses that connection.

I suppose you're right that accepting a connection gives the caller more flexibility than accepting a bus type.

> You can then build the system-bus-using singleton object on top of that.
> 
> For unit testing, you can then use your new `GDBusConnection`-using constructor with `g_dbus_connection_new_for_address()` and `g_test_dbus_get_bus_address()`.

Or just create a session connection, since `GTestDBus` sets the session bus address.

> 
> There’s a [full example of this in Mogwai](https://gitlab.freedesktop.org/pwithnall/mogwai/blob/master/libmogwai-schedule-client/scheduler.c#L684), which also does the handling of `connection` as a `GObject` property, and the use of `GInitable` and `GAsyncInitable` which is potentially necessary.

Is `MwscScheduler` ever a singleton?

**Comment by pwithnall** [comment]
> > You can then build the system-bus-using singleton object on top of that.
> > For unit testing, you can then use your new `GDBusConnection`-using constructor with `g_dbus_connection_new_for_address()` and `g_test_dbus_get_bus_address()`.
> 
> Or just create a session connection, since `GTestDBus` sets the session bus address.

I think it’s a little safer/more explicit to go via a `GDBusConnection`, since then you’re not passing state around in environment variables which are a) not thread safe, b) could be set from anywhere, c) an ugly process-global key-value table which keeps hanging around enabling hacks and really should disappear.

> > There’s a [full example of this in Mogwai](https://gitlab.freedesktop.org/pwithnall/mogwai/blob/master/libmogwai-schedule-client/scheduler.c#L684), which also does the handling of `connection` as a `GObject` property, and the use of `GInitable` and `GAsyncInitable` which is potentially necessary.
> 
> Is `MwscScheduler` ever a singleton?

No, that aspect is missing (my mistake). Everything else is there, though, and implementing a singleton is a matter of retaining the first constructed instance in a `static` variable (and deciding whether to clear that `static` variable when that instance is finalised, or whether to keep it alive forever).

**Comment by mwleeds** [comment]
Experimentally, `UDisksClient` seems to not be a singleton. Calling `udisks_client_new_sync` twice returns two different objects. Oddly the commit after the one that introduced `UDisksClient` removes a TODO comment about making it a singleton, without actually doing so: https://github.com/storaged-project/udisks/commit/8ece91f7. So maybe the comment in `initable_init` that implies it's a singleton is just wrong.

**Comment by wjt** [comment]
The API contract for [g_initable_init](https://developer.gnome.org/gio/stable/GInitable.html#g-initable-init) changed in GLib 2.54 – it's now considered an application error to initialize an object more than once, and the implementation can assume/assert it is called at most once per instance.

**Comment by mwleeds** [comment]
Yeah I saw that thanks. I'll leave in the locking though.
