### ISSUE TITLE
gio unable to see external devices for mounting

### ISSUE THREAD

**Issue by paulmenzel** [storaged-project/udisks#697]
GIO doesn’t see events from udisks2, and external devices are also not listed in the file managers (Thunar, Files). Mounting external devices (as normal user) with `udisksctl mount -b /dev/sdb1` works fine, and after that, the device also shows up in the file manager. Unmounting then also works with the file manager. What is required for proper integration? Is some PolicyKit rule needed?

```
$ gio version
2.60.5
$ /usr/libexec/udisks2/udisksd --version
Error parsing options: Unknown option --version
udisks-Message: 12:13:30.652: udisks daemon version 2.8.4 exiting
$ # after plugging in USB device
$ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 232.9G  0 disk 
├─sda1   8:1    0   128G  0 part /
├─sda2   8:2    0 104.8G  0 part /amd/XXX/0
└─sda3   8:3    0   128M  0 part 
sdb      8:16   1  29.2G  0 disk 
├─sdb1   8:17   1   701M  0 part 
└─sdb2   8:18   1     4M  0 part 
sr0     11:0    1  1024M  0 rom
$ gio mount -li
Volume(0): Filesystem root
  Type: GUnixVolume
  ids:
   label: 'root'
  themed icons:  [drive-removable-media]
  symbolic themed icons:  [drive-removable-media-symbolic]
  can_mount=1
  can_eject=0
  should_automount=1
  Mount(0): Filesystem root -> file:///
    Type: GUnixMount
    default_location=file:///
    themed icons:  [drive-harddisk]
    symbolic themed icons:  [drive-harddisk-symbolic]
    can_unmount=1
    can_eject=0
    is_shadowed=0
$ udisksctl mount -b /dev/sdb1
Mounted /dev/sdb1 at /run/media/joey/grml64-full_sid build2782.
$ gio mount -li
Volume(0): Filesystem root
  Type: GUnixVolume
  ids:
   label: 'root'
  themed icons:  [drive-removable-media]
  symbolic themed icons:  [drive-removable-media-symbolic]
  can_mount=1
  can_eject=0
  should_automount=1
  Mount(0): Filesystem root -> file:///
    Type: GUnixMount
    default_location=file:///
    themed icons:  [drive-harddisk]
    symbolic themed icons:  [drive-harddisk-symbolic]
    can_unmount=1
    can_eject=0
    is_shadowed=0
Mount(1): grml64-full_sid build2782 -> file:///run/media/joey/grml64-full_sid%20build2782
  Type: GUnixMount
  default_location=file:///run/media/joey/grml64-full_sid%20build2782
  themed icons:  [media-optical]
  symbolic themed icons:  [media-optical-symbolic]
  can_unmount=1
  can_eject=1
  is_shadowed=0
```

Plugging in the USB device, `gio mount -io` shows nothing. Only when mounting it manually with `udiskctl mount -b /dev/sdb1` it shows the output below.

```
$ gio mount -oi
Monitoring events. Press Ctrl+C to quit.
Mount added:        'grml64-full_sid build2782'
  Mount(0): grml64-full_sid build2782 -> file:///run/media/joey/grml64-full_sid%20build2782
    Type: GUnixMount
    default_location=file:///run/media/joey/grml64-full_sid%20build2782
    themed icons:  [media-optical]
    symbolic themed icons:  [media-optical-symbolic]
    can_unmount=1
    can_eject=1
    is_shadowed=0
```

Please find the rest of the [requested information](https://www.freedesktop.org/wiki/Software/udisks/) attached.

1.  [udisksctl-dump.txt](https://github.com/storaged-project/udisks/files/3670398/udisksctl-dump.txt)
1.  [udevadm-info--export-db.txt](https://github.com/storaged-project/udisks/files/3670400/udevadm-info--export-db.txt)
1.  [udisksctl-monitor.txt](https://github.com/storaged-project/udisks/files/3670472/udisksctl-monitor.txt)
1.  [udevadm-monitor--udev--property.txt](https://github.com/storaged-project/udisks/files/3670474/udevadm-monitor--udev--property.txt)

**Comment by tbzatek** [comment]
PolicyKit is not involved for passive observation. First check that you have gvfs and its backends installed, then make sure you're running your desktop or terminal session with a valid D-Bus session bus set and available. UDisks operates on system bus, GVfs operates on user session bus.

What you see are `GUnixMount` volumes that is a native and fallback implemetation within GIO. UDisks2 GVfs volume monitor takes priority when available and extends GIO in runtime. You should be seeing `GProxyVolumeMonitorUDisks2` objects in the proper case.

**Comment by paulmenzel** [comment]
Updating Gvfs from 1.24.0 to 1.42.0 fixed the issue.
