### ISSUE TITLE
Update Udisks spelling in GitHub description

### ISSUE THREAD

**Issue by paulmenzel** [storaged-project/udisks#702]
The README spells it *Udisks*, so it be great, if you updated the GitHub description to use the same spelling.

**Comment by vojtechtrefny** [comment]
We should probably first discuss what is the correct spelling. Manpages and the original [freedesktop webpage](https://www.freedesktop.org/wiki/Software/udisks/) use *udisks*, README here uses *Udisks* and documentation and API uses *UDisks* and *UDisks2* (possibly as a result of camel case naming of objects in GTK/glib). Now what is correct and what should be fixed?

I personally tend to use *UDisks* everywhere, but maybe it's wrong.

**Comment by vpodzime** [comment]
> I personally tend to use _UDisks_ everywhere, but maybe it's wrong.

Same here. *UPower* also uses this pattern. So I think it makes most sense.

**Comment by vpodzime** [comment]
Poll: The correct spelling for this project should be:

a) *UDisks* -- thumbs up
b) *Udisks* -- thumbs down

**Comment by tbzatek** [comment]
I guess it's decided. Feel free to post a patch :ghost:

**Comment by vpodzime** [comment]
Yeah, thanks for all the feedback from the community :smile: :disappointed:
