### ISSUE TITLE
already mounted error when mounting LUKS encrypted partition

### ISSUE THREAD

**Issue by juergenthomann** [storaged-project/udisks#703]
Hi,

I get currently always the following error message when I mount a encrypted partition over Dolphin (KDE Plasma 5.17, but happened already in earlier versions).

> An error occurred while accessing '731,5 GiB Hard Drive', the system responded: The device is already mounted: Device /dev/dm-0 is already mounted at `/run/media/juergen/da7af3f4-7f16-4b19-adaa-9fba75785996'.

The last part of the message seems to come from UDisks. This is a bit annoying, as Dolphin will not open the mounted location, but the disk is properly decrypted and mounted.

Is there some (easy) way to debug this? I have also the following logs from journald

> Okt 22 21:18:45 kernel: sd 6:0:0:0: [sdb] 1953458176 512-byte logical blocks: (1.00 TB/931 GiB)
> Okt 22 21:18:45 kernel: sd 6:0:0:0: [sdb] Write Protect is off
> Okt 22 21:18:45 kernel: sd 6:0:0:0: [sdb] Mode Sense: 47 00 10 08
> Okt 22 21:18:45 kernel: sd 6:0:0:0: [sdb] No Caching mode page found
> Okt 22 21:18:45 kernel: sd 6:0:0:0: [sdb] Assuming drive cache: write through
> Okt 22 21:18:45 kernel:  sdb: sdb1 sdb2
> Okt 22 21:18:45 kernel: sd 6:0:0:0: [sdb] Attached SCSI disk
> Okt 22 21:19:36 udisksd[15553]: Unlocked device /dev/sdb2 as /dev/dm-0
> Okt 22 21:19:36 kernel: XFS (dm-0): Mounting V4 Filesystem
> Okt 22 21:19:36 kernel: XFS (dm-0): Ending clean mount
> Okt 22 21:19:36 udisksd[15553]: Mounted /dev/dm-0 at /run/media/juergen/da7af3f4-7f16-4b19-adaa-9fba75785996 on behalf of uid 1000

I should be able to compile and run custom versions if required to debug this.

Thanks,
Jürgen

**Comment by vojtechtrefny** [comment]
This is something that needs to be fixed in KDE:

https://bugs.kde.org/show_bug.cgi?id=350393
https://bugs.kde.org/show_bug.cgi?id=391706

As a workaround you can compile your own version of UDisks without libmount support, see https://github.com/storaged-project/udisks/issues/502

**Comment by juergenthomann** [comment]
Thanks for having a look. I found some other still open issues with no reply and one or two which I understood as not a Dolphin problem.

I'll try to get it fixed with the KDE developers.
