### ISSUE TITLE
btrfs: Mount option 'compress=zstd:3' is not allowed

### ISSUE THREAD

**Issue by Mordaut** [storaged-project/udisks#704]
Hi,
i have a removable drive with btrfs and would like to automount this drive with the compress mount option.
I have tried this with following command:
`sudo udisksctl mount --block-device /dev/mapper/example --options "compress=zstd:3"`
Resulting in the error 
`Error mounting /dev/dm-1: GDBus.Error:org.freedesktop.UDisks2.Error.OptionNotPermitted: Mount option `compress=zstd:3' is not allowed
`
I have noticed the same problem at the udiskie git repo but haven't seen it here

[https://github.com/coldfix/udiskie/issues/73](url)

thank you for your time

**Comment by tbzatek** [comment]
Yes, that happens due to the whitelist of mount options we respect. We should probably take a look again at `btrfs`, `zfs`, `ntfs-3g`, `f2fs` and add missing _safe_ mount options.
