### ISSUE TITLE
FAT disks should not be mounted with showexec

### ISSUE THREAD

**Issue by probonopd** [storaged-project/udisks#707]
## User story

I as a user want to attach an USB drive formatted with e.g., FAT32, and execute my bash script and ELF executables from there, to run my custom scripts and applications that I carry around with me (and also use e.g., on Mac and Windows machines).

## Situation

Currenty, `udisksd` prevents me from running scripts and binaries. This has been the case for quite some time and is very annoying, as evidenced by the references below.

As far as I know, it is not even possible to remount those devices with something like `-o remount,exec`.

## Workaround

```
sudo su
systemctl stop udisks2
if [ -e /usr/lib/udisks/udisks-daemon ] ; then
  sed -i -e 's|showexec|\x00\x00\x00\x00\x00\x00\x00\x00|g' /usr/lib/udisks/udisks-daemon
fi
if [ -e /usr/lib/udisks2/udisksd ] ; then
  sed -i -e 's|showexec|\x00\x00\x00\x00\x00\x00\x00\x00|g' /usr/lib/udisks2/udisksd # Ubuntu 12.10
fi
if [ -e /usr/libexec/udisks2/udisksd ] ; then
  sed -i -e 's|showexec|\x00\x00\x00\x00\x00\x00\x00\x00|g' /usr/libexec/udisks2/udisksd # Fedora 23
fi
systemctl restart udisks2
```

Personally I have been using this workaround for more than 7 years with no negative side effects.

## Suggested cause of action

Remove the `showexec` boot option.

In case someone heavily objects with good reason, there should at least be a run-time configuration option to allow the root user to change the behavior on the system.

## References

* https://forum.kde.org/viewtopic.php?f=225&t=108693
* https://cgit.freedesktop.org/udisks/commit/?id=7e7ec1abca069e9443f8eed49acec4ea32589d0c
* https://bugzilla.redhat.com/show_bug.cgi?id=646673
* https://ubuntuforums.org/showthread.php?t=1665289
* https://bugs.launchpad.net/ubuntu/+source/udisks/+bug/663815

**Comment by tbzatek** [comment]
I suppose by removing the `showexec` mount option all files will have the executable flag set (unless `umask` option is specified). This is not a desired result, while having executable bit set just on the _.EXE_, _.COM_, or _.BAT_ files is essentially useless in linux, having it set on all files is a noticeable usability issue e.g. in case user copies the files on a POSIX-compatible filesystem. We're providing sane defaults in udisks and it's clear it won't suit everyone.

And yes, configurable mount options feature is planned, not yet implemented though.

The workaround is pretty nasty, I was always wondering how somebody could even share and spread such stuff.

**Comment by probonopd** [comment]
> I suppose by removing the showexec mount option all files will have the executable flag set (unless umask option is specified). This is not a desired result

I agree that this is not desirable, but since FAT does not have executable bits it's all or nothing. 

> having it set on all files is a noticeable usability issue e.g. in case user copies the files on a POSIX-compatible filesystem

Agree, yet it's better to have a "noticeable usability issue" rather than being outright denied to execute files from FAT filesystems altogether.

> The workaround is pretty nasty, I was always wondering how somebody could even share and spread such stuff.

Because it has made it impossible to run scripts and executables from removable FAT disks since over 7 years. And I need to run scripts and executables from removable FAT disks  every day.

> And yes, configurable mount options feature is planned, not yet implemented though.

**Comment by 7eggert** [comment]
The fix is problematic since it prevents me from "starting" non-executable files using their respective programs. Also it's a security risk (see github.com/storaged-project/udisks/issues/644)

**Comment by tbzatek** [comment]
> I agree that this is not desirable, but since FAT does not have executable bits it's all or nothing.

Yes, it's all or nothing. The mentioned issue #644 requests no executable bits at all for example.

Given that there was a purpose for the default mount option change and the use cases still look valid - i.e. limit the executable flags on non-POSIX filesystems, I would suggest to keep things at their current state.

Remember this is just a default set of mount options, clients/users have always been able to specify custom mount options via the `org.freedesktop.UDisks2.Filesystem.Mount()` method call argument. It's clear defaults don't always suit everyone, we should prioritize implementing the support for overriding such defaults instead.

> > The workaround is pretty nasty, I was always wondering how somebody could even share and spread such stuff.

FWIW, looking at the code, the binary string replace will cause putting _NULL_ in the middle of the array which causes iteration to stop. Meaning the rest of the default mount options would get ignored as well as the whitelist of allowed mount options gets truncated. So much for violent binary code modifications.
 
> Because it has made it impossible to run scripts and executables from removable FAT disks since over 7 years. And I need to run scripts and executables from removable FAT disks every day on various different Linux distributions, which I can't compile UDisks for all of them.

One of the workarounds here could be to execute files through some interpreter, i.e. the general `bash -c <command>` or in case of an exact interpreter, you may use directly `python <script>` or `bash <script>`. Perhaps also `exec` may help in some cases. This also works on `noexec` mounts.

**Comment by probonopd** [comment]
Thanks @tbzatek for picking up this issue.

**Comment by tbzatek** [comment]
> Thanks @tbzatek for picking up this issue. What would be awesome is that if could honor some boot-time kernel parameter, e.g., `vmlinuz (...) udisks2=no-showexec` so that it could be **easily** configured e.g., on Live ISOs without having to change the contents of the filesystem. One can dream, right?

I think this can be easily done via custom script called in the boot process that will set up a config file or udev rule before the `udisks2` service is started. Let's not complicate things on the daemon side, it brings noticeable maintenance burden.

**Comment by probonopd** [comment]
Thank you very much @tbzatek. I hope this will allow me to plug in a FAT32 USB drive and run applications from there.

**Comment by probonopd** [comment]
> I hope this will allow me to plug in a FAT32 USB drive and run applications from there.

So far this has not happened, likely because the default is still to use `showexec :(

**Comment by tbzatek** [comment]
> So far this has not happened, likely because the default is still to use `showexec` :( Could it be made the default _not_ to use `showexec`?

FYI, you can redefine mount options since the UDisks 2.9.0 release: http://storaged.org/doc/udisks2-api/latest/mount_options.html

**Comment by zhang-wenchao** [comment]
use zfs show this.

**Comment by zhang-wenchao** [comment]
@probonopd appimaged is reporting this issue on zfs, do you have a workaround? Thanks.

**Comment by 7eggert** [comment]
@zhang-wenchao , @probonopd

I re-checked the vfat situation on OpenSuse Tumbleweed, it does use `-o showexec` now and only DOS-executable files are executable. This would be the correct way to deal with this situation.

IDK about zfs but in this thread there is a link to the default options. You might see which ones are relevant and need a change.

**Comment by probonopd** [comment]
@zhang-wenchao can you please report this issue in the appimaged repo, together with a step-by-step way to reproduce it. Thanks!
