### ISSUE TITLE
deterministic ID's in api-index.html

### ISSUE THREAD

**Issue by raboof** [storaged-project/udisks#715]
When generating `doc/html/api-index.html` for the same sources twice, the output is not deterministic due to different id's.

This might be an upstream issue in gtk-doc, or a problem with how it is invoked. I'm not sure yet, so reporting it here first until we figure that out.

**Comment by tbzatek** [comment]
That seems to be a `docbook` issue, the following patch must be applied: https://github.com/docbook/xslt10-stylesheets/commit/07631601e6602bc49b8eac3aab9d2b35968d3e7a

`gtk-doc` then sets
```
  <xsl:param name="generate.consistent.ids" select="1"/>
```

within `gtk-doc.xsl` (see http://docbook.sourceforge.net/release/xsl/current/doc/html/generate.consistent.ids.html).

This has been an issue with other projects as well and I'm not sure we can do something about it ourselves.

**Comment by tbzatek** [comment]
There has been some work done `gtk-doc` upstream to address these issues as well: e.g. https://gitlab.gnome.org/GNOME/gtk-doc/-/merge_requests/37

**Comment by raboof** [comment]
Nice, indeed the problem seems to be solved on whatever version of gtk-doc is currently in nixos-unstable at least :). Thanks for the pointers!
