### ISSUE TITLE
Nautilus does not show correctly device labels containing accent if the device was labeled using windows system

### ISSUE THREAD

**Issue by glaubersm** [storaged-project/udisks#718]
Hi
I use udisks 2.8.4 and Gnome 3.342 on Arch Linux.
This issue was already reported in Gnome's bug tracker.
https://bugzilla.gnome.org/show_bug.cgi?id=786780

How we can read in comment 6, there is an issue with udisks.

**Comment by tbzatek** [comment]
The comment https://bugzilla.gnome.org/show_bug.cgi?id=786780#c3 describes the real issue. What we can do is to play nice and substitute the invalid UTF-8 characters with whitespaces. This will result in correct _M\_sicas_ string.
