### ISSUE TITLE
APM level reset to default value 128 after resume from suspend

### ISSUE THREAD

**Issue by frieben** [storaged-project/udisks#72]
Description of problem:
After setting the APM level of my hard disk to 255 by means of gnome-disk-utility, the APM level is actually set to 255 as verifified by means of executing 'hdparm -B /dev/sda'. However, after suspend and resume, the APM level is set to 128 as verified by executing 'hdparm -B /dev/sda' again.

Version-Release number of selected component (if applicable):
storaged-2.6.2-1.fc25

How reproducible:
Always.

Steps to Reproduce:
1. Set APM level to 255.
2. Suspend and resume.
3. Run 'hdparm -B /dev/sda'.

Actual results:
The APM level is 128.

Expected results:
The APM level is 255.

Additional info:
- This bug was initially reported for the current Fedora development tree, see
    https://bugzilla.redhat.com/show_bug.cgi?id=1357190.
- The hard disk is a Hitachi HTS723216L9SA60 installed in a Lenovo ThinkPad T400.
- Moreover, after resume from suspend, gnome-disk-utility erroneously reports the target value 255 instead of the real value 128.
- The same issue affects package udisks and was reported upstream, see
    https://bugs.freedesktop.org/show_bug.cgi?id=94618.

**Comment by tsmetana** [comment]
Here's the Fedora testing packages: https://copr.fedorainfracloud.org/coprs/tsmetana/storaged/

**Comment by tsmetana** [comment]
Udisks2/storaged is D-Bus activated... It is not guaranteed to be started on boot (and therefore set the APM level). It only starts up when something uses its D-Bus interface. There is no difference between storaged and udisks2 in this regard. You may want to unconditionally enable it by systemctl to ensure it starts and configures the drives on boot.

**Comment by frieben** [comment]
From a user's point of view, gnome-disk-utility provides the possibility to customize the drive settings, and its is up to the underlying infrastructure to make sure they are applied correctly in all circumstances. If this is not a case then this is a bug which needs to be fixed in the related packages and certainly not asking the user to tweak his system.
The APM setting -was- applied correctly upon reboot (albeit not upon resume from suspend) as long as udisks2 was installed, and this is clearly not longer the case after updating to storaged whatever the reason for this malfunction may be.
It is therefore perfectly reasonable to conclude a regression which indicates a bug in storaged or in its packaging as a Fedora RPM.

**Comment by tsmetana** [comment]
I totally understand your point and I don't intent to argue about the user-unfriendliness of the suggested workaround. Hence this issue is not closed yet. Thanks for the testing btw.

However I need to find out what is so different between storaged and udisks2 if you claim udisks2 did automatically start on boot for you and storaged did not. The simplest answer is that there was something else you did when booting with udisks2 (perhaps starting a file manager, gnome-disks, etc...).

**Comment by frieben** [comment]
I had been misled by a change of behaviour between udisks2 and storaged: udisks2 applies drive settings at runlevel 5, storaged even later after a GNOME session has been started, too. I had checked the APM settings on a virtual console before logging in. For this reason, hdparm returned the desired (custom) value of 255 in the first case but the wrong (default) value of 128 in the second case. Thus, after launching a GNOME session, the correct result is obtained in both cases. However, this leads to another question: why are drive settings applied that late? It is preferable to have them applied at runlevel 3, and I do not see any reason to postpone this action to runlevel 5 or to an even later moment after launching a GNOME session. Please consider changing the target runlevel to 3.

As far as the resume-from-suspend issue is concerned, I can confirm that storaged-2.6.2-1.fc24 fails to restore the correct APM setting after resume from suspend whereas the latest storaged-2.6.2-2.6.fc24 actually does restore the correct APM setting after resume from suspend.

**Comment by tsmetana** [comment]
@frieben: As already mentioned: both udisks2 and storaged are D-Bus activated services and in Fedora they should be off by default on boot meaning they "wake up" only when some other application calls them.

To make it worse there still seems to be some issues with the patch on my testing machine: even though the settings get applied by the log, the level is still at the default value. I need to figure out why.

**Comment by vpodzime** [comment]
Maybe we need to create a *systemd* service to (re-)apply stuff like this?

**Comment by frieben** [comment]
On current Fedora 26 with udisks2-2.6.5 and systemd-233, the correct APM level is restored correctly after resume from suspend unlike on Fedora 25 with storaged-2.6.2 and systemd-231.

**Comment by vpodzime** [comment]
> On current Fedora 26 with udisks2-2.6.5 and systemd-233, the correct APM level is restored correctly after resume from suspend unlike on Fedora 25 with storaged-2.6.2 and systemd-231.

Great! Let me close this issue now then. Feel free to reopen it at any point if you hit it again.
