### ISSUE TITLE
Why is 'unhide' mount option not allowed for udf

### ISSUE THREAD

**Issue by dsonck92** [storaged-project/udisks#721]
I work with Native Instruments VSTs which come as iso files. I need to mount these using the unhide option provided by the udf module as they hide their content packs for some reason.

Normally I would need to escalate to root as I need to mount with options, however I've seen that udisks allows mounting of disks without root. It supports most of the options I need (ro,exec) but unhide is not in the allowed options list.

I don't know if this was simply because the option was not known, or whether there were security implications. Either I would like to know the reason, or ideally if there is no reason, I'd like to see this added.

As a sidenote, if udisks supports this, I could attempt to write a patch for wine for implementing Windows disk mounting which would solve another issue I have with Native Instruments. But that's besides the point of this report

**Comment by tbzatek** [comment]
My guess is that nobody explored the additional mount options for UDF when creating a list of allowed mount options. Otherwise I see no reason to disallow that.

This will be solved by the upcoming support for configurable mount options.

**Comment by tbzatek** [comment]
The 'unhide' mount option is now allowed for UDF: https://github.com/storaged-project/udisks/commit/9d20e41684de35c33cdd8e5f4680e9c5b07997ab
