### ISSUE TITLE
Tests failing on the current Ubuntu serie

### ISSUE THREAD

**Issue by seb128** [storaged-project/udisks#724]
Udisks has a failing test when built on the current Ubuntu serie

udisks-test:ERROR:test.c:358:binary_output_on_spawned_job_completed: assertion failed (standard_output->len == 200): (0 == 200)
Bail out! udisks-test:ERROR:test.c:358:binary_output_on_spawned_job_completed: assertion failed (standard_output->len == 200): (0 == 200)
FAIL udisks-test (exit status: 134)

complete build log
https://launchpadlibrarian.net/459228943/buildlog_ubuntu-focal-amd64.udisks2_2.8.4-1_BUILDING.txt.gz
(The log is from 2.8.4 but trying git gives the same error)

**Comment by tbzatek** [comment]
Yes, this has something to do with new `glib`. It's been failing the same way in our CI on rawhide for some weeks, stable distro releases work fine with the same code.

Haven't had time to debug this yet, it's on our short-term TODO list though.
