### ISSUE TITLE
Creating raid does not create symlink

### ISSUE THREAD

**Issue by marusak** [storaged-project/udisks#735]
In Cockpit we use `udisks2` to work with storage. We use `MDRaidCreate` to create RAIDs.
In the current Fedora 32 image we hit problem that when we specify `name = 'ARR'` it creates the raid but fails with:
```
Failed to get md node for array 'ARR': Failed to read the symbolic link /dev/md/ARR: No such file or directory
```
`/dev/md127` is created correctly and the raid itself seems fine, but there is no `/dev/md` and no `/dev/md/ARR`.

Installed version:
`udisks2-2.8.4-4.fc32.x86_64`

It works correctly on Fedora 31 with `udisks2-lvm2-2.8.4-3.fc31.x86_64`.
My reproducer involves using Cockpit, but I am happy to provide any other information.

**Comment by vojtechtrefny** [comment]
This is probably result of some change in udev (or more likely mdadm udev rules). We also have some issues with mdraid in the installer so this might be not UDisks specific. I plan to take a look at this this week.

**Comment by vojtechtrefny** [comment]
Reported to mdadm in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1809117

**Comment by vojtechtrefny** [comment]
mdadm should be fixed in both rawhide and f32 now, do you still see the error?

**Comment by marusak** [comment]
Indeed, our tests don't see this anymore. Thanks!
