### ISSUE TITLE
udiskctl mount: "Transport endpoint is not connected"

### ISSUE THREAD

**Issue by markus-wa** [storaged-project/udisks#740]
Hi, I'm having trouble mounting an exFAT partition via `udisks2`.

Interestingly it was working fine this morning but I had some issues because the drive got disconnected while it was attached.
Now I can only mount the drive via standard `mount` (so it's not corrupt, all data is available).

Edit: automount was working as well and I was able to browse the drive via Nautilus

```sh
# DOESNT WORK
$ udisksctl mount -b /dev/sda1
Mounted /dev/sda1 at /media/mark/WD Ext.

$ ls /media/mark/WD\ Ext                                                                                                                                         ls: cannot access '/media/mark/WD Ext': Transport endpoint is not connected

$ udisksctl unmount -b /dev/sda1
Unmounted /dev/sda1.

# THIS WORKS FINE
$ sudo mount /dev/sda1 /mnt/WD\ Ext
FUSE exfat 1.2.8
WARN: volume was not unmounted cleanly.

$ ls /mnt/WD\ Ext
FOUND.000   Images  'Install Discovery for Mac.dmg'  'Install Discovery for Windows.exe'   Music  '$RECYCLE.BIN'  'System Volume Information'

$ sudo umount /mnt/WD\ Ext

# DOESNT WORK
$ sudo mount /dev/sda1 /media/mark/WD\ Ext                                                                                                                       FUSE exfat 1.2.8

$ ls /media/mark/WD\ Ext
ls: cannot access '/media/mark/WD Ext': Transport endpoint is not connected
```

Note also that mount only works for `/mnt`, but I'm not sure if that's normal or not for exFAT maybe.

what i tried so far:
- searching for udev rules regarding mounting -> none found
- reinstalling udisks
- reinstalling exfat-utils
- reinstalling exfat-fuse

Could someone guide me in the right direction? Would be much appreciated, thanks!

**Comment by markus-wa** [comment]
It was caused by a file with an 'invalid UTF-16' name (I lost the exact error message)

I was able to delete the file from Windows after disabling 'hide system files' (it was in the recycling bin).
From Linux it was not possible to do this as the drive disconnected as soon as I tried to do anything with the file in question.

**Comment by tbzatek** [comment]
Yes, this is a manifestation of a `fuse` module crashing. Now that the native `exfat` driver is being included in recent kernels, please check whether it's available for your distibution and remove the `exfat-fuse` package if it is. This way you'll get much more stable experience.
