### ISSUE TITLE
How to use libudisks2? Insufficient documentation

### ISSUE THREAD

**Issue by bztsrc** [storaged-project/udisks#746]
Hi,

I'd like to open a device through udisks2, but there are no examples and the documentation is extremely insufficient. http://storaged.org/doc/udisks2-api/latest/UDisksBlock.html#udisks-block-call-open-device-sync says about arg_options that "Argument to pass with the method invocation." which is not helpful at all.

What I want to do is this:
```c
fd = open(device, O_RDWR | O_SYNC | O_EXCL);
```
what is the libudisks2 equivalent? I've located the block object (using stat(device) and matching st.st_rdev), and I'm trying this (not working):
```c
g_variant_builder_init(&builder, G_VARIANT_TYPE("a{sv}"));
g_variant_builder_add(&builder, "{sv}", "O_SYNC", g_variant_new_int32(O_SYNC));
g_variant_builder_add(&builder, "{sv}", "O_EXCL", g_variant_new_int32(O_EXCL));
if(!udisks_block_call_open_device_sync(block, "rw", g_variant_builder_end(&builder),
  NULL, &var, NULL, NULL, &error)) {
    printf("error=%s\n", error->message);
    fd = 0;
} else
    fd = (int)g_variant_get_int32(var);
```
How can I pass O_SYNC and O_EXCL flags? How do I retrieve the out_fd (integer)? Why does this function have an out_fd list when the underlying UDisks.Block.OpenDevice() method can return only one out_fd? So many questions not answered in the documentation... A working example would be very much appreciated!

Thanks,
bzt

**Comment by vojtechtrefny** [comment]
You are right, we could definitely use some examples for libudisks. It took me embarrassingly long to write this and there might be some bugs, but I hope it will help: https://gist.github.com/vojtechtrefny/24524cc5580f418a28d00c991dc9fa29

> How can I pass O_SYNC and O_EXCL flags?

It's an extra option for the function. These are always dictionaries with a key word ("flags" in this case) and value here is just the flags.

```
g_variant_builder_add (&builder, "{sv}", "flags", g_variant_new_int32 (O_SYNC | O_EXCL));
```
> How do I retrieve the out_fd (integer)? Why does this function have an out_fd list when the underlying UDisks.Block.OpenDevice() method can return only one out_fd?

This is related to how sending fds on DBus works (the library is just a autogenerated wrapper around the DBus API). We are sending a `GUnixFDList` list of fds and `out_fd` is a variant of type `G_VARIANT_TYPE_HANDLE` which is an index into the returned array (in this case this will always be `0`).

> So many questions not answered in the documentation

Yes, unfortunately the documentation is also generated from the DBus API documentation and not really helpful.

**Comment by bztsrc** [comment]
Thank you so much!

In the meantime I've figured out how to use GUnixFDList, but I noticed some oddities:
1. it looks like udisks.h does not include gunixfdlist.h, I had to include it myself
2. first I was unable to get the fdlist, but when I created the list myself with g_unix_fd_list_new() and passed a reference to that I got results back.
3. I'm not sure if it's necessary, but reading the comments in the source suggested that I have to use g_unix_fd_list_steal_fds(), so I did, and it worked, returned a gint from the GUnixFDList just as I wanted.

About the "flags" key, thank you, I couldn't figure this out on  my own!

As all my questions has been answered, I'm going to close this ticket. Thanks again!

bzt

**Comment by tbzatek** [comment]
Well, `libudisks` client interface is by larger part autogenerated and is essentially a convenient wrapper around `GDBusProxy` with all the advantages of integration with Glib main loop. Things like fd passing follow Glib semantics. Basic knowledge of Glib and GIO is expected when using `libudisks` API, it's not self-hosting. You'll need to understand how `GObject` lifecycle works, that there's a `GDBus` worker thread with its mainloop that could clash with your (other) application framework, etc.

Generally, if using complex framework like Qt, it's better to let the toolkit generate native objects for you from the D-Bus interface XML file.

Also, there are number of examples in GIO docs: https://developer.gnome.org/gio/stable/

**Comment by bztsrc** [comment]
Hi,

Thanks for your reply, but I think you misunderstood my issue.

> with all the advantages of integration with Glib main loop.

And disadvantages. I don't want to use the Glib main loop, as my project is a multiplatform one, with multiple backends. All I need is a simple function that opens the device and returns the fd for it.

> there's a GDBus worker thread with its mainloop that could clash with your (other) application framework, etc.

> Generally, if using complex framework like Qt

Which I don't. I'm not using any complex bloated frameworks, I'm not my own enemy :-) More precisely I always use the lowest-level lib which is native to the platform: GDI, Cocoa, etc. For Linux, I prefer X11 by default, GTK is just one of the options for me.

> Also, there are number of examples in GIO docs

Which are no good for me. I'm not looking for a wrapper around POSIX file operations, I can deal with them myself. I'm looking for a simple way to communicate with the udisks2 daemon. The issue here is, GTK incorrectly blocks any application with setgid bit. This is incorrect, because a) calls this a warning, so it should act like it, not as if it were a critical error b) I'm not using setgid root, just a plain simple group setgid. So what I need is to workaround this conceptually flawed design is a privilegized daemon to talk to. The libudisks2 with @vojtechtrefny 's gist provides exactly that. No bloated frameworks, just a simple way to talk to udisks2, which is perfect.

If you're interested, here's my project: https://gitlab.com/bztsrc/usbimager
As you can see, it compiles to a single portable executable under Windows, MacOSX and Linux. And for Linux GTK is just one of the options only used for the deb packages. With X11 I can simply use the setgid bit to gain access to block devices (and I don't need sudo, udsisk2 daemon or anything else). I like simplicity.

Anyway, thanks for your reply!
bzt

**Comment by tbzatek** [comment]
> The libudisks2 with @vojtechtrefny 's gist provides exactly that. No bloated frameworks, just a simple way to talk to udisks2, which is perfect.

Oh, interesting perception. I think we've managed to hide the bloated framework deep enough so that's invisible to users. But that's the way it should be I guess. :relaxed:

Anyway, what I was trying to say was that if you don't want to deal with GLib objects and dependencies around, you may always use different D-Bus client implementation, like the low-level `libdbus`. You don't need to use `libudisks` API at all then.

**Comment by bztsrc** [comment]
> Oh, interesting perception. I think we've managed to hide the bloated framework deep enough so that's invisible to users. But that's the way it should be I guess. ☺️

Yes you did :-) Statically linking to libudisks2 and calling udisks_call_open_device_sync() is a simple, straightforward and portable solution!

> you may always use different D-Bus client implementation, like the low-level libdbus. You don't need to use libudisks API at all then.

But then I would be vulnerable to potential protocol changes. With libudisks2 I don't have to worry about those (as a matter of fact, I don't even have to know that the communication is actually implemented with dbus as of 2020). Let's say in the future people realize the dbus is not so great and they call it obsolete and switch to (now hipothetical) wayland-bus or ebus or whatever. Then if I would have used libdbus I would have to rewrite my application. With libudisks2 all I would need to do is recompile with the latest version and that's it.

Cheers,
bzt
