### ISSUE TITLE
Thunar presents authentication dialog which cannot be canceled.

### ISSUE THREAD

**Issue by rsbrux** [storaged-project/udisks#749]
Under Ubuntu Studio 18.04 I mistakenly try to mount a drive and am presented with an authentication dialog asking for a password for an account with admin privileges.  Clicking the "Cancel" button in the authentication dialog has no effect.  I can neither get rid of the authentication dialog nor can I close Thunar.

**Comment by tbzatek** [comment]
That's most likely a Polkit agent issue. UDisks only interacts with the base PolicyKit framework and presenting an authorization dialog is agent's job. Most major desktop environments have their own agents, either integrated or as a separate packages. E.g. in Gentoo there are

```
gnome-extra/polkit-gnome
kde-plasma/polkit-kde-agent
lxqt-base/lxqt-policykit
mate-extra/mate-polkit
sys-auth/polkit-qt
```

**Comment by rsbrux** [comment]
Thanks for the explanation.  What can I do about it? The Ubuntu software utility doesn't show me anything when I search for "polkit" or "policykit".

**Comment by tbzatek** [comment]
Can you post a screenshot please?

**Comment by rsbrux** [comment]
Here it is.  This time I was able to close Thunar, but the authentication dialog remained.
![Authenticate](https://user-images.githubusercontent.com/3919699/77097169-a8aaac80-6a10-11ea-8d70-0e89dbb4da4a.png)

**Comment by tbzatek** [comment]
I think that's the standard agent shipped along `polkit`. Please open a bugreport on your distribution.

Theoretically it may also be a Thunar issue trying to call the `Mount()` method all over again.

**Comment by tbzatek** [comment]
Closing for now, please coordinate with your distribution bug tracker.
