### ISSUE TITLE
Upstream exfat driver in Linux 5.7 doesn't support `namecase`

### ISSUE THREAD

**Issue by philipl** [storaged-project/udisks#764]
If you try and use the upstream exfat driver with udisks managed mounting, mounting will fail due to the `namecase` option being unrecognised. The option should probably just be removed, but at least it has to be removed from the defaults list.

https://github.com/storaged-project/udisks/blob/master/src/udiskslinuxmountoptions.c#L83

**Comment by vojtechtrefny** [comment]
Thank you for the report, this will be fixed in next UDisks release, #737 covers this (and many other moutpoint options issues).
