### ISSUE TITLE
test_loop_rw fails since 2.9 on s390x

### ISSUE THREAD

**Issue by seb128** [storaged-project/udisks#777]
The integration tests fail on Ubuntu/s390x since we updated to 2.9.0

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/s390x/u/udisks2/20200610_155315_a918d@/log.gz

```
======================================================================
FAIL: test_loop_rw (__main__.Manager)
loop device R/W
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 616, in test_loop_rw
    self.assertEqual(block.get_property('id-label'), 'foo')
AssertionError: '' != 'foo'
+ foo
```

libblockdev was also updated from 2.23 to 2.24 but the udisks 2.8.4 tests are not failing with the updated library so it seems the issue is due to the udisks update itself

**Comment by tbzatek** [comment]
Yeah, another occurrence of randomly failing test, we've seen that on some systems.

**Comment by seb128** [comment]
It's weird, other tests are randomly failing as in https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/s390x/u/udisks2/20200609_220203_0b1a0@/log.gz

======================================================================
ERROR: test_0_create_teardown (__main__.Luks)
LUKS create/teardown
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 1354, in test_0_create_teardown
    self.setup_crypto_device()
  File "src/tests/integration-test", line 1323, in setup_crypto_device
    self.fs_create(None, 'ext4', GLib.Variant('a{sv}', {
  File "src/tests/integration-test", line 354, in fs_create
    block.call_format_sync(fs_type, options, None)
gi.repository.GLib.GError: udisks-error-quark: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error synchronizing after initial wipe: Timed out waiting for object (0)

```
======================================================================
ERROR: test_ascii_keyfile_newline (__main__.Luks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 1582, in test_ascii_keyfile_newline
    encrypted.call_lock_sync(no_options, None)
AttributeError: 'NoneType' object has no attribute 'call_lock_sync'

======================================================================
ERROR: test_binary_keyfile (__main__.Luks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 1551, in test_binary_keyfile
    self.fs_create(None, 'ext4', GLib.Variant('a{sv}', {
  File "src/tests/integration-test", line 354, in fs_create
    block.call_format_sync(fs_type, options, None)
gi.repository.GLib.GError: udisks-error-quark: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error creating LUKS device: Failed to format device: Device or resource busy (0)
```

but the id-label one was never failing in 2.8 and is always failing now on 2.9 (at least on the ~10 retried made since it was uploaded)

Note that for the flacky one increasing the timeout seems to help workarounding (it doesn't make a difference on the one initially report here though)

**Comment by tbzatek** [comment]
There were lots of changes to the daemon core wrt. processing uevents. This may be an example of uevent coming late or not at all, thus not updating D-Bus object properties in time. That's why adding sleeps to tests may help as the uevent eventually comes, even a minute later.

However we generally want to avoid adding sleeps there and there, this helps us to identify weak points. Failing a test doesn't necessarily mean the daemon is broken.

**Comment by seb128** [comment]
Thanks for the reply, shouldn't the call to
                self.client.settle()
before the assert ensure there is no pending events though?

we might just skip the test to unblock the update if you are confident it's not a real issue that's going to hit users

thanks for the replies in any case!

**Comment by tbzatek** [comment]
Unfortunately the `udisks_client_settle()` call is about settling the D-Bus communication itself, unrelated to uevent processing. There was a related discussion in https://github.com/storaged-project/udisks/issues/635#issuecomment-467470237 however that would only be a workaround, we need to solve this properly in the daemon.

**Comment by seb128** [comment]
Right, thanks for the explanations. I've tried to add a sleep before the settle call and it workarounds the issue so it does seem to confirm your uevents theory

**Comment by tbzatek** [comment]
The linked pull request should make things more stable, I was able to reproduce the original issue locally.

> Note that for the flacky one increasing the timeout seems to help workarounding (it doesn't make a difference on the one initially report here though)

As far as the `Error synchronizing after initial wipe: ` error is concerned, this has changed in 2.9.0 as well. First we trigger uevent on the block device, waiting for `#define UDISKS_DEFAULT_WAIT_TIMEOUT 20  /* seconds */` and then we wait another `UDISKS_DEFAULT_WAIT_TIMEOUT` for an `empty` `ID_FS_TYPE`. 

In total 40 seconds is quite a long time and if you say prolonging timeouts fix the problem, I'm wondering what's going on in the system. Is there a uevent traffic or just a high load?
