### ISSUE TITLE
Disable external media auto mounting

### ISSUE THREAD

**Issue by marcosfrm** [storaged-project/udisks#786]
Is there a way to disable it globally other than `UDISKS_AUTO` set via udev rules?

If not, please add to data/80-udisks2.rules an example rule that is equivalent to these checks

https://github.com/storaged-project/udisks/blob/udisks-2.9.0/src/udiskslinuxblock.c#L395

so downstream folks can easily disable it.

**Comment by tbzatek** [comment]
Mounting itself is controlled by a third party, UDisks only sets hints. Desktop environments usually have a way to disable automounting (e.g. `caja-file-management-properties` in MATE desktop), by changing schema defaults I believe this can be set globally.

What is your use case exactly?

**Comment by marcosfrm** [comment]
Indeed! Sorry for the noise!
