### ISSUE TITLE
Change the mountpoint's path, group and permissions

### ISSUE THREAD

**Issue by saitaruninaganti** [storaged-project/udisks#805]
By default (on my system), the default mountpoint is `/run/media/$USER/<UUID>`. I need it to use `PARTLABEL`/`PARTNAME` instead of `UUID`. How can I do this?

Here is my udev rules file.
```
# UDISKS_FILESYSTEM_SHARED
# ==1: mount filesystem to a shared directory (/media/VolumeName)
# ==0: mount filesystem to a private directory (/run/media/$USER/VolumeName)
# See udisks(8)
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{UDISKS_FILESYSTEM_SHARED}="0" \
, SUBSYSTEM=="block", ENV{PARTNAME}!="", ENV{UDISKS_NAME}="$env{PARTNAME}" \
# , GROUP="storage", MODE:="0664"
```

`GROUP` and `MODE` seem to affect the devices and not their mountpoints. Also, I was told that `UDISKS_NAME` changes the mountpoint's name, but that doesn't work. Can you correct the file?

**Comment by xiaoweihong** [comment]
if can change?

**Comment by vojtechtrefny** [comment]
It's currently not possible to change the mountpoint. `UDISKS_NAME` only changes the `HintName` property which is used by GUI tools like Nautilus when displaying the device, it doesn't affect the mountpoint.

Our first choice for the mountpoint is filesystem label so you can try changing the `ID_FS_LABEL_ENC` and `ID_FS_LABEL` properties of the device in your UDev rule. But I'm not sure if it will work and it might break other things, UDisks isn't the only user of UDev database.
