### ISSUE TITLE
Timed out waiting for object

### ISSUE THREAD

**Issue by tazihad** [storaged-project/udisks#817]
I am trying to mount iso. But I am getting this error

`$ udiskie-mount Win10_2004_English_x64.iso
failed to add Win10_2004_English_x64.iso: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating '/dev/loop4': Timed out waiting for object`
and
`$ udisksctl loop-setup -r -f Win10_20H2_English_x64.iso
Error setting up loop device for Win10_20H2_English_x64.iso: GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating '/dev/loop5': Timed out waiting for object`

Mount works for smaller iso. It works in Arch linux iso. But big iso(windows iso, office img files) files have this mounting problem. I have wipe out and reinstalled system. Still this problem exists. I have seen people complaining about this error in reddit and other forums. ex: [reddit](https://www.reddit.com/r/linux4noobs/comments/jntn0n/cant_mount_isos_in_popos_2004/), [manjaro forum](https://forum.manjaro.org/t/iso-not-mounting/34964)

[udisksctl_dump.txt](https://github.com/storaged-project/udisks/files/5531648/udisksctl_dump.txt)
[udevadm.txt](https://github.com/storaged-project/udisks/files/5531658/udevadm.txt)
[mountinfo.txt](https://github.com/storaged-project/udisks/files/5531662/mountinfo.txt)
[fstab.txt](https://github.com/storaged-project/udisks/files/5531669/fstab.txt)

**Comment by tbzatek** [comment]
We've seen that before (#800) and I'm actually working on this right now as this is more pronounced elsewhere.

**Comment by tblume** [comment]
I was trying to trace back the issue and found a python exception in return_value:

-->
Thread 7 "pool-udisksd" hit Breakpoint 1, _udisks_manager_skeleton_handle_method_call (connection=<optimized out>, sender=<optimized out>, object_path=<optimized out>, 
    interface_name=0x7fbd8c00fd90 "org.freedesktop.UDisks2.Manager", method_name=0x7fbd8c009610 "LoopSetup", parameters=<optimized out>, invocation=0x7fbd8c00cc00, user_data=0x7fbd90007eb0)
    at udisks-generated.c:3051
3051      g_value_unset (&return_value);
(gdb) bt full
#0  _udisks_manager_skeleton_handle_method_call
    (connection=<optimized out>, sender=<optimized out>, object_path=<optimized out>, interface_name=0x7fbd8c00fd90 "org.freedesktop.UDisks2.Manager", method_name=0x7fbd8c009610 "LoopSetup", parameters=<optimized out>, invocation=0x7fbd8c00cc00, user_data=0x7fbd90007eb0) at udisks-generated.c:3051
        skeleton = <optimized out>
        info = <optimized out>
        iter = {x = {94721443137312, 2, 2, 0, 0, 4, 511101108319, 3579507750, 140452226903108, 140452226902608, 140451738812448, 2032, 140451738832880, 39, 94721442364096, 140451738814672}}
        child = 0x0
        paramv = 0x7fbd78004a90
        num_params = <optimized out>
        n = <optimized out>
        signal_id = 32
        return_value = Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 

              {g_type = , data = {{v_int = 1, v_uint = 1, v_long = 1, v_ulong = 1, v_int64 = 1, v_uint64 = 1, v_float = 1.40129846e-45, v_double = 4.9406564584124654e-324, v_pointer = 0x1}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        __func__ = "_udisks_manager_skeleton_handle_method_call"
#1  0x00007fbd98b80a3e in  () at /usr/lib64/libgio-2.0.so.0
#2  0x00007fbd98b0e2de in  () at /usr/lib64/libgio-2.0.so.0
#3  0x00007fbd989479e4 in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007fbd989470ee in  () at /usr/lib64/libglib-2.0.so.0
#5  0x00007fbd9863b3e9 in start_thread () at /lib64/libpthread.so.0
#6  0x00007fbd987feb73 in clone () at /lib64/libc.so.6
--<

Maybe this is a pointer to the issue?

**Comment by tbzatek** [comment]
Thanks for debugging, but no, the real problem is elsewhere. UDisks heavily depends on uevents to process updates to block devices and objects it exposes. For some reason an uevent related to the particular block device might be received at the time when not all attributes are available. This is racy by nature, depends heavily on timing, kernel, etc. We usually trigger extra uevent explicitly in UDisks and wait until it's received. Same case here.
