### ISSUE TITLE
UDISKS_AUTO hint not working

### ISSUE THREAD

**Issue by psusi2** [storaged-project/udisks#842]
I am trying to test auto mounting with a hot plugged virtual disk in a Xen VM.  I made a udev rule to set UDISKS_AUTO=1 and UDISKS_SYSTEM=0 for /dev/xvdb and /dev/xvdb1.  udisksctl info -b recognizes the hinting, but it still won't auto mount the disk when it is hot plugged.  Am I missing something or is this feature no longer working?

**Comment by tbzatek** [comment]
UDisks itself only provides hints to upper layers and never performs any automounting itself. If you see the hints properly set in `udisksctl dump` then you only need something else to perform the automount. Typically it's `gvfs-udisks2-volume-monitor` running in a desktop session that triggers automount along with its own other rules.

**Comment by tbzatek** [comment]
@psusi2, does that clarify your concern?
