### ISSUE TITLE
Reload optical drive after burn/blank operation

### ISSUE THREAD

**Issue by vicr123** [storaged-project/udisks#849]
Currently, after a burn/blank operation, UDisks does not reload the drive to reflect the state of the inserted media, until the drive is ejected and reinserted.

It would be nice if UDisks detects when a disc has been written/blanked or at the very least provide a way to reload the state of the disc.

**Comment by tbzatek** [comment]
UDisks depends on external uevents and if there's none trigerred there's no way to find out anything happened. It is a responsibility of the burning tool to trigger uevent on the device. This is not just UDisks issue, udev itself may not have noticed the change.

Can you try running `udevadm monitor` and see if there was any event after the operation?

**Comment by vicr123** [comment]
No events triggered after the operation unfortunately. Can I manually trigger the event somehow?

**Comment by tbzatek** [comment]
You can manually trigger uevent via `udevadm trigger <device>`. UDisks should then pick up the changes.

Ideally please open a bugreport on the burning tool. If this used to work previously, it's likely than any recent kernel change made a difference. There are no guarantees until a uevent is trigerred explicitly.

**Comment by vicr123** [comment]
Unfortunately it looks like that command requires root. However, it does work and UDisks does reload the state of the disc.

The burning tool (`cdrecord`) hasn't ever fired events. I'm trying to write my own frontend for `cdrecord` but since it's not running as root there's no way for it to trigger the events. Is there any better way for my tool to let UDisks know that the state of the disc has been changed?

**Comment by tbzatek** [comment]
It's not just UDisks that suffers here. Esentially anything that pulls information from udev db would receive outdated information. It's the responsibility of the tool that modifies the data on the block device to tell the system that the contents have changed and needs to be rescanned. Making any workarounds just doesn't make sense.

**Comment by vicr123** [comment]
Gotcha. Thanks for your help!
