### ISSUE TITLE
Qt5 GUI app using udisks2 HDD identify

### ISSUE THREAD

**Issue by nestorac** [storaged-project/udisks#854]
Hello, I want to develop a Qt5 GUI app for erasing disks, I need to identify the physical HDDs (there are many org.freedesktop.UDisks2.Block devices: loops, cdroms, partitions...), how can I achieve that? Thank you!

**Comment by vojtechtrefny** [comment]
We have special objects on DBus for drives -- [/org/freedesktop/UDisks2/drives/](http://storaged.org/doc/udisks2-api/latest/ref-dbus-drives.html) On the `Block` interface the [Drive](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-property-org-freedesktop-UDisks2-Block.Drive) is set to the drive object path (or to `/` for non-disk block devices).

**Comment by nestorac** [comment]
Thank you!

**Comment by nestorac** [comment]
How can I access the Drive property from Block? It would be useful.

**Comment by vojtechtrefny** [comment]
You need to get the drive object referred in the ` org.freedesktop.UDisks2.Block` `Drive` property and it has the `org.freedesktop.UDisks2.Drive` interface.

**Comment by tbzatek** [comment]
You may have a look at https://github.com/storaged-project/udisks/blob/master/tools/udisksctl.c where object lookup is made, either by specifying a commandline argument or by walking the object manager.

**Comment by vojtechtrefny** [comment]
In Python this could look like:

```
import dbus
bus = dbus.SystemBus()

sda_obj = bus.get_object("org.freedesktop.UDisks2", "/org/freedesktop/UDisks2/block_devices/sda") 
drive_path = sda_obj.Get("org.freedesktop.UDisks2.Block", "Drive", dbus_interface=dbus.PROPERTIES_IFACE)
drive_obj = bus.get_object("org.freedesktop.UDisks2", drive_path)
disk_id = drive_obj.Get("org.freedesktop.UDisks2.Drive", "Id", dbus_interface=dbus.PROPERTIES_IFACE) 
print(disk_id)
```
which will print the disk ID from the Drive interface for `sda`: `QEMU-QEMU-HARDDISK-drive-scsi1-0-`

**Comment by nestorac** [comment]
wow, this is really helpful. BTW, I'm using C++/Qt5/Udisks2. I'll take a look at the udiskctl.c util, and I'll play with the code as @vojtechtrefny suggests, and I'll tell you soon. I hope that I keep going, if if'm stuck I'll let you know, thank you!

**Comment by tbzatek** [comment]
If you're using native Qt, might be better to use QtDBus directly. You can perhaps take the D-Bus interface XML file and generate native Qt objects from that: https://github.com/storaged-project/udisks/blob/master/data/org.freedesktop.UDisks2.xml (though not sure how exactly this works in Qt).

You don't need to stick with `libudisks2` that is built upon `GDBus` with its own mainloop, you may interface UDisks2 directly through D-Bus via QtDBus.

**Comment by nestorac** [comment]
That's perfect, thank you, tomorrow I will try QtDBus.

**Comment by nestorac** [comment]
@tbzatek , I'm now trying to guess how to use Qt DBus, there are some examples, but I don't know how to find physical disk drives, I'm a bit confused. I see the XML file, but I don't know how to use it. Do you have any piece of advice? Thank you!

**Comment by nestorac** [comment]
> In Python this could look like:

@vojtechtrefny , I have tried your python code and it works, but I need to list all HDD physical devices, could you please tell me how? I think that the code would be similar, but not the same.

**Comment by tbzatek** [comment]
For physical HDD devices, look for the Drive objects on the UDisks2 D-Bus object manager. Then look for the `Removable` and `MediaRemovable` properties.

Hint: try running `d-feet` and browse through the available objects. That way you'd get an idea on what kind of objects, what interfaces and which properties are presented. Writing a code is just about picking the right object and matching particular properties on a desired interface.

API reference can be found at http://storaged.org/doc/udisks2-api/latest/index.html
