### ISSUE TITLE
Secure Erase Support

### ISSUE THREAD

**Issue by hadess** [storaged-project/udisks#866]
It would be really useful if udisks could offer Secure Erase support to front-ends, so that there's a secure alternative to zero'ing the whole disk. Command-line instructions:
https://wiki.archlinux.org/index.php/Solid_state_drive/Memory_cell_clearing

**Comment by vojtechtrefny** [comment]
We already support it. You can use either [SecurityEraseUnit](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Drive.Ata.html#gdbus-method-org-freedesktop-UDisks2-Drive-Ata.SecurityEraseUnit) from the `org.freedesktop.UDisks2.Drive.Ata` interface or use `ata-secure-erase`/`ata-secure-erase-enhanced` with the `empty` option in [Format](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-method-org-freedesktop-UDisks2-Block.Format).

GNOME Disks is also offers this option:

![image](https://user-images.githubusercontent.com/5063197/112722361-547eb600-8f09-11eb-8852-571573853afe.png)

**Comment by hadess** [comment]
Yep, and probably only to drives actually connected via SATA, rather than random USB adapters. I managed to have the password setting lock my drive and then throw an error, which meant I couldn't then unlock it. My fault...
Thanks for the quick reply.

**Comment by tbzatek** [comment]
Yeah, USB bridges are often a problem. Some do allow ATA command passthrough but that's relatively rare.
For NVMe the support is currently being worked on.

**Comment by hadess** [comment]
In this case the problem isn't so much that the bridge allowed passthrough, it allowed _some_ passthrough, enough to add a password (probably not even the one I wrote), and yank the device off of the bus, requiring an unplug/replug and thus locking the device.
