### ISSUE TITLE
udisksctl doesn't show squashfs as supported file system

### ISSUE THREAD

**Issue by baryluk** [storaged-project/udisks#867]
Not sure why, but:

```
/org/freedesktop/UDisks2/Manager:
  org.freedesktop.UDisks2.Manager:
    DefaultEncryptionType:      luks1
    SupportedEncryptionTypes:   luks1
                                luks2
    SupportedFilesystems:       ext2
                                ext3
                                ext4
                                vfat
                                ntfs
                                exfat
                                xfs
                                reiserfs
                                nilfs2
                                btrfs
                                minix
                                udf
                                f2fs
                                swap
    Version:                    2.9.2

```

doesn't list `squashfs`.

But `squashfs` is supported, loaded, and I have some file system mounted, including some using udisks2:

```
/home/user/fex.squashfs on /media/user/disk type squashfs (ro,nosuid,nodev,relatime,uhelper=udisks2)
```

So it is supported I think.

**Comment by tbzatek** [comment]
UDisks is focused on local storage management primarily around block devices. There are many other filesystems available in your system that UDisks officially doesn't support. Such filesytems can still be mounted, but there's no support for filesystem specifics for creating filesystems, relabeling it, etc.

Can you describe in more detail what is your use case?

Filesystems supported by currently running kernel can be found in `/proc/filesystems`.

**Comment by vojtechtrefny** [comment]
We probably need a better documentation for the `SupportedFilesystems` property. This is list of filesystems UDisks "knows" and can work with -- for example we can create these filesystems using [Format](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-method-org-freedesktop-UDisks2-Block.Format), change label on them etc. It doesn't/isn't supposed to show all filesystems supported in your system.

**Comment by baryluk** [comment]
I just find udisks easy to use with images of file systems to be mounted by any user without needing sudo, and without resorting for fuse. I use `udisksctl loop-setup` for that. It is mostly for inspecting images, copying out files, and modifying them. Sure, in many respects this can also be done using `libguestfs`, but it has limitations (i.e. can't run external programs on files to do something with them).
