### ISSUE TITLE
Check sleep status of HDD's in layered structures before scanning volumes

### ISSUE THREAD

**Issue by Markus-N** [storaged-project/udisks#868]
This issue is a follow-up of https://github.com/storaged-project/udisks/issues/611#issuecomment-786049132. Having two aspects, I think it helps to separate them into individual issues, starting with the bigger one.

System and version info:  
udisks2 2.9.2-1 on Arch Linux

My PC is running mostly 24/7, and I'm trying to keep the RAID disks sleeping as much as possible, especially when the summer comes, every watt not heating up my room is valuable :-) but I often need to mount/ unmount file systems on USB devices and also remote filesystems (the latter ones covered in the second issue: #869).

However, the HDD's wake up on any mount / unmount operation. I've followed this advice to replacedumpe2fs with a logger:
https://unix.stackexchange.com/questions/408757/why-is-dumpe2fs-called-without-user-interaction/408763
and when I mount a USB device, dumpe2fs is called for the dm devices that correspond to the logical volumes, e.g. /dev/dm-6.

This is my storage layout (I think this table is clearer than a udisksctl dump):
<table>
  <tr>
    <td>hardware</td>
    <td colspan="3">/dev/nvme0n1</td>
    <td>/dev/sda</td>
    <td>/dev/sdb</td>
    <td>/dev/sdc</td>
    <td>/dev/sdd</td>
    <td>/dev/sde</td>
  </tr>
  <tr>
    <td>partitions</td>    
    <td>p1: EFI</td>
    <td>p2: /boot</td>
    <td>p3: all the rest</td>
    <td colspan="5">one partition each, part of the md-raid</td>
  </tr>
  <tr>
    <td>encryption</td>    
    <td></td>
    <td></td>
    <td>crypt 1</td>
    <td colspan="5"> crypt 2</td>
  </tr>
  <tr>
    <td>LVM PV's</td>    
    <td></td>
    <td></td>
    <td>PV 1</td>
    <td colspan="5">PV 2</td>
  </tr>
  <tr>
    <td>LVM VG's</td>    
    <td></td>
    <td></td>
    <td>VG 1</td>
    <td colspan="5">VG 2</td>
  </tr>
  <tr>
    <td>LVM LV's</td>    
    <td></td>
    <td></td>
    <td>/, /var, /home, ...</td>
    <td colspan="5">/BigData</td>
  </tr>
</table>

As you can see, everything on the RAID is separated from the rest of the system. And it contains data I don't access every day. But the HDD's spin up multiple times per day because of the mount/unmount operations on USB and remote filesystems.

I did a few further reading a while ago and I remember stumbling upon someone explaining that the volume scan is there "for a reason" but unfortunately without explaining the reason. I'd like to learn about this reason. :-)

**Comment by tbzatek** [comment]
I suppose the problem here is that an ATA drive lookup done in `UDisksLinuxFilesystem` only attempts to sniff an interface on a direct `UDisksLinuxBlockObject`, not taking a layered structure in account. In this case, it would need to walk the tree and find all physical devices and check them all. This is not easy to implement and adds quite a bit of complexity.

However, in your case, if you are not running any UDisks client that consumes the `org.freedesktop.UDisks2.Filesystem.Size` property, I think this change might cover your case: #949

Would you have a way to verify that it solves your issue please?

**Comment by Markus-N** [comment]
Welll ... although I consider myself an advanced user, I don't think I'm advanced enough to run a self-built system component. As I use my PC for my job, I also don't want to risk the stability of the OS.  
On the other hand, running Arch Linux, I think I will get an updated udisks very early when #949 is merged. I'd like to wait for that.

**Comment by tbzatek** [comment]
No worries. I've updated the pull request with a TODO about layered structure. I don't think we'd get to it anytime soon.

I would like to keep this change in a development branch for the moment as the way the object properties are overriden is kinda hacky. Needs more testing in the CI over time. Distributors are of course welcome to pick the changes up at their consideration.

**Comment by Markus-N** [comment]
Unfortunately, mounting USB devices still wakes up my internal HDDs.
