### ISSUE TITLE
exfat support is incompatible with exfatprogs

### ISSUE THREAD

**Issue by seb128** [storaged-project/udisks#882]
The current git code has the issue
https://github.com/storaged-project/udisks/blob/ea94706707bbe48e4d8264927cff27c9671c5070/src/udiskslinuxfsinfo.c#L126
     
or that command exists only in exfat-utils and not in the new exfatprogs project, which leads to the issue report on https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/issues/203 where formatting a device in exfat fails.

The mkfs.exfat command would be a better choice since it's availabe in exfat-utils and exfatprogs and what is libblockdev is using but unfortunately those projects picked different arguments for setting the label (-n vs -L) ... unsure if there is currently any framework in udisks to handle such cases?

One way would be to ignore the label and call mkfs.exfat without argument but that's suboptimal.

**Comment by seb128** [comment]
Turns out that the exfattools utility understand '-n' for compatibility reason even if the help doesn't include the option, thanks @vojtechtrefny who pointed that out, I've submitted an update fix as #883

**Comment by tbzatek** [comment]
Fixed in #883.
