### ISSUE TITLE
hard disk write protected...

### ISSUE THREAD

**Issue by daniele777** [storaged-project/udisks#885]
HI ! After replace an cdrom slot to hard disk .. i can't operate inside... i think write protection i post image... 

![Schermata 2021-04-22 18:21:18](https://user-images.githubusercontent.com/8341788/115754289-561e8b00-a39c-11eb-9c36-3bcd68c27b03.png)
![Schermata 2021-04-22 18:22:10](https://user-images.githubusercontent.com/8341788/115754300-5ae33f00-a39c-11eb-9282-a07370110048.png)

how to unlock and mount automatically'??? thxxx

**Comment by vojtechtrefny** [comment]
I'm not sure, I fully understand your problem, can you be more specific? The first screenshot showing the authentication dialog is "normal" -- you are trying to mount a non-removable harddrive, this is a privileged operation and you need to authenticate (provide your password) for that. If you want to mount the disk automatically during boot, you need to configure it in [/etc/fstab](https://wiki.archlinux.org/index.php/fstab), in GUI you can do this with [GNOME Disks](https://www.linuxuprising.com/2018/12/how-to-auto-mount-partitions-on-startup.html).

**Comment by daniele777** [comment]
First of all thx for reply ...ok.. i replace a dvdrom slot in my notebook with an slot with hard disk and format it with gparted in ext4 but after boot i need to  mont manually it and ask  system password during this operation ... and after typed  i can't write or copy and past file .. seems lock
i'll want to have normal hard disk to use same as internal....  ...

**Comment by tbzatek** [comment]
Anything in the removable CD/DVD notebook tray is a native SATA (or even IDE) device and is likely treated as an internal non-removable drive. To mount it after boot, put a record in `/etc/fstab`. Also make sure to change permissions on the new filesystem so you can write there as an user.

**Comment by daniele777** [comment]
ok now harddisk mounted automatically at startup but writeprotection enabled how to remove?

**Comment by tbzatek** [comment]
Can you please post output of `hdparm -I /dev/sda`? Please check the _Security_ section at the end. You may also try experimenting with `hdparm` to unlock the drive.
