### ISSUE TITLE
Test fails with clang compiler

### ISSUE THREAD

**Issue by justinkb** [storaged-project/udisks#891]
https://github.com/storaged-project/udisks/blob/4a05f59e29412c5473bd0551d9fb2826582bd5a3/src/tests/test.c#L326

Clang generates code that produces a SIGILL signal for the null pointer dereference code on https://github.com/storaged-project/udisks/blob/4a05f59e29412c5473bd0551d9fb2826582bd5a3/src/tests/helper.c#L66

Patch like this should fix this issue

```
--- a/src/tests/test.c	2021-05-21 15:30:56.455141008 +0200
+++ b/src/tests/test.c	2021-05-21 15:33:17.505559033 +0200
@@ -323,7 +323,11 @@ test_spawned_job_abnormal_termination (v
   job = udisks_spawned_job_new (s, NULL, getuid (), geteuid (), NULL, NULL);
   udisks_spawned_job_start (job);
   _g_assert_signal_received (job, "completed", G_CALLBACK (on_completed_expect_failure),
+#ifdef __clang__
+                             (gpointer) "Command-line `./udisks-test-helper 4' was signaled with signal SIGILL (4): "
+#else
                              (gpointer) "Command-line `./udisks-test-helper 4' was signaled with signal SIGSEGV (11): "
+#endif
                              "OK, deliberately causing a segfault\n");
   g_object_unref (job);
   g_free (s);

```

**Comment by tbzatek** [comment]
Good catch, thanks!

**Comment by MANGOPIE3** [comment]
@justinkb Hi, I also encounter the same question now, but in my environment( centos x86_64 clang 17.0 ), 
The null pointer dereference code compiled with clang will result in **SIGSEGV (11)** not  **SIGILL (4)**.
I would appreciate it if you could tell me about your environment.
