### ISSUE TITLE
Can I unlock veracrypt encrypted volumes with udisks?

### ISSUE THREAD

**Issue by PoisonFrog** [storaged-project/udisks#894]
I've seen people discussing this topic, but I don't know if it is already possible to unlock these volumes using udisks. I tried to do it but I didn't manage to make udisks unlock a veracrypt volume. I had to unlock with cryptsetup and then mount it with udisksctl. It would be much better if I could unlock veracrypt volumes with udisks since it doesn't require root.

**Comment by vojtechtrefny** [comment]
Yes, TrueCrypt/VeraCrypt devices are supported, but this support is not enabled by default, you need to create `/etc/udisks2/tcrypt.conf` file to enable it. See #589 and #495 for details.

**Comment by PoisonFrog** [comment]
> Yes, TrueCrypt/VeraCrypt devices are supported, but this support is not enabled by default, you need to create `/etc/udisks2/tcrypt.conf` file to enable it. See #589 and #495 for details.

I created the '/etc/udisks2/tcrypt.conf' file and I am still not able to unlock veracrypt volume files. I rebooted the computer and it is still not working. I tried on Fedora 34. Not a single mention of truecrypt or veracrypt in the man page or anything. Idk, maybe I should stick to cryptsetup.

**Comment by vojtechtrefny** [comment]
What does `udisks info -b /dev/sdxY` says? It should look like this:

```
$ udisksctl info -b /dev/loop2
/org/freedesktop/UDisks2/block_devices/loop2:
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/loop2
...                        
    IdLabel:                
    IdType:                     crypto_unknown
    IdUUID:                     
    IdUsage:                    crypto
...  
  org.freedesktop.UDisks2.Encrypted:
    ChildConfiguration:         []
    CleartextDevice:            '/'
    HintEncryptionType:         
    MetadataSize:               0
 ```

You can also check with GNOME Disks, it should say the device *Possibly Encrypted** and allow unlocking it.

![image](https://user-images.githubusercontent.com/5063197/121375289-e9a61e00-c940-11eb-8b1f-c18d4954caa8.png)

Because True/VeraCrypt devices don't have a cleartext header, we use a statistical test to determine whether the device seems to be encrypted or not. It's possible (but unlikely) that we simple fail to recognize the device to be encrypted.

**Comment by PoisonFrog** [comment]
> What does `udisks info -b /dev/sdxY` says? 
It says "Error looking up object for device". Maybe it is because I want to decrypt a veracrypt file volume and not a physical device?

**Comment by vojtechtrefny** [comment]
Yes, UDisks needs a block device to work with, so you need to use `udisksctl loop-setup -f <file>` first and then `udisksctl unlock -b /dev/loopX` (the `loop-setup` command will print which loop device needs to be used).

**Comment by PoisonFrog** [comment]
> Yes, UDisks needs a block device to work with, so you need to use `udisksctl loop-setup -f <file>` first and then `udisksctl unlock -b /dev/loopX` (the `loop-setup` command will print which loop device needs to be used).

It worked! Thank you very much!
