### ISSUE TITLE
Use exfatprogs instead of exfat-utils to handle exFAT filesystem operations

### ISSUE THREAD

**Issue by diazbastian** [storaged-project/udisks#903]
To understand why I got here look at: https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/issues/210

Since version 5.7 of the Kernel a native driver is available to handle the exFAT file system, whose tool for the user space is `exfatprogs`. FUSE-based tools `exfat-utils` and `fuse-exfat` were used for a long time. Some distros have already migrated to using the native driver and even not including the FUSE-based driver packages, which can lead to problems in using this widely used file system.

**Comment by vojtechtrefny** [comment]
We've already switched to a compatible `mkfs.exfat` call, see #882 and #883. This is not released yet, @tbzatek we should consider doing a new 2.9.x release or a downstream patch for Fedora.

**Comment by tbzatek** [comment]
Right, another 2.9.x series release makes sense now as the 2.10.0 release is still far away, possibly next year.

**Comment by tbzatek** [comment]
This is fixed in the recent 2.9.3 release.
