### ISSUE TITLE
Requesting support for mounting bcachefs filesystems

### ISSUE THREAD

**Issue by Managor** [storaged-project/udisks#913]
The filesystem seems to be in a usable condition right about now, at least to the common user like me. udisksctl support for bcachefs would be appreciated.

**Comment by vojtechtrefny** [comment]
libblkid (util-linux) currently doesn't support bcachefs, see https://github.com/karelzak/util-linux/pull/1274 and we use UDev (which uses libblkid) to get information about block devices (including what filesystem is on them) so without support in libblkid we can't support bcachefs in UDisks. But unless bcachefs needs something extra (special configuration before mounting or special mount options for example) we shouldn't need to change UDisks to be able to mount it.

**Comment by Managor** [comment]
Thank you. I don't know much about what depends on what so I ask around. Sorry to ask it on the bugtracker, but there was no public chat channel listed on the site that I could have popped in.

**Comment by vojtechtrefny** [comment]
> Sorry to ask it on the bugtracker, but there was no public chat channel listed on the site that I could have popped in.

No problem, we use GH issues for questions too, we don't have a dedicated IRC channel for UDisks. I'll keep this issue open, we can revisit it after the bcachefs support lands in util-linux and check if we need to adjust something in UDisks.

**Comment by tbzatek** [comment]
I've added `bcachefs` to an internal whitelist in #985. As said earlier posts, it's up to the lower layers to properly handle this.
