### ISSUE TITLE
when mount an unmounted block device sync successfully, can not get the mountpoints via UDisksFilesystem right away

### ISSUE THREAD

**Issue by itsXuSt** [storaged-project/udisks#930]
i think this is a bug, i call the `udisks_filesystem_call_mount_sync` and get the mount point via the outputed param, but i cannot get the mountpoints via `udisks_filesystem_dup_mount_points` function.
but if i make a 1s delay, the mountpoints can be obtained via the same object.
so i think when the block is mounted, the mountpoints of this object is not updated in time.
and this my test code: 
```c++
    GError *err = nullptr;
    UDisksClient *cli = udisks_client_new_sync(nullptr, &err);
    UDisksObject *blkObj = udisks_client_get_object(cli, "/org/freedesktop/UDisks2/block_devices/sdb1");
    UDisksFilesystem *fs = udisks_object_get_filesystem(blkObj);

    char **mountpoints = udisks_filesystem_dup_mount_points(fs);
    int idx = 0;
    qDebug() << "before mount: ";
    while (mountpoints && mountpoints[idx]) {
        qDebug() << "mount point: " << *mountpoints;
        idx++;
    }
    qDebug() << "\t the mount points count: " << idx;
    g_strfreev(mountpoints);

    GVariantBuilder *builder = g_variant_builder_new(G_VARIANT_TYPE ("a{sv}"));
    GVariant *ret = g_variant_builder_end(builder);
    g_variant_builder_unref(builder);

    char *mountPoint = nullptr;
    if (err) g_error_free(err);
    mountpoints = nullptr;
    udisks_filesystem_call_mount_sync(fs, ret, &mountPoint, nullptr, &err);
    qDebug() << "\nafter mount it is mounted at: " << mountPoint;

    qDebug() << "\nthen get mount via filesystem handler";
    mountpoints = udisks_filesystem_dup_mount_points(fs);
    idx = 0;
    while (mountpoints && mountpoints[idx]) {
        qDebug() << "mount point: " << *mountpoints;
        idx ++;
    }
    qDebug() << "mountpoint count: " << idx;

    qDebug() << "\nafter a while delay: ";
    QTimer::singleShot(1000, nullptr, [&fs, &mountpoints]{
        mountpoints = udisks_filesystem_dup_mount_points(fs);
        int idx = 0;
        while (mountpoints && mountpoints[idx]) {
            qDebug() << "mount point: " << *mountpoints;
            idx ++;
        }
        qDebug() << "mountpoint count: " << idx;
    });
```

and this is the output
```
before mount: 
	 the mount points count:  0

after mount it is mounted at:  /media/xust/Ventoy

then get mount via filesystem handler
mountpoint count:  0

after a while delay: 
mount point:  /media/xust/Ventoy
mountpoint count:  1
```

**Comment by tbzatek** [comment]
@itsXuSt any luck with my suggestions? Have you managed to find more information?

**Comment by itsXuSt** [comment]
>

**Comment by itsXuSt** [comment]
Thanks for your help @tbzatek , recentlly I got no time to work on this issue, my version is little old than the latest one, and I found another solution in my project, maybe later I'll concentrate on this issue and see if it can be reproduce in the newest version still.
Thanks.
( I clicked the close button carelessly

**Comment by itsXuSt** [comment]
And forgot to say, the version of libudisks2 in my environment is 2.8.1.x

**Comment by tbzatek** [comment]
Btw. what is your kernel version please?

**Comment by tbzatek** [comment]
> And forgot to say, the version of libudisks2 in my environment is 2.8.1.x

Oh, that explains a lot. This has been changed in #728 and #750, released in https://github.com/storaged-project/udisks/releases/tag/udisks-2.9.0

We always implicitly expect that bug reporters are running latest stable release. Version 2.8.1 was released over three years ago!

Closing as this should be working in recent releases.
