### ISSUE TITLE
Please support auto-creation of VDO pool name

### ISSUE THREAD

**Issue by martinpitt** [storaged-project/udisks#939]
The commands here assume a "myvg" volume group:

    vgcreate myvg /dev/sda

From the user's point of view, the vdo pool volume is an internal implementation detail, not a thing they directly interact with. Thus, the precise name of the pool is also rather uninteresting. That's why the "official" `lvcreate` CLI makes specifying the pool name optional (`--vdopool`), and the [documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/deduplicating_and_compressing_logical_volumes_on_rhel/creating-a-deduplicated-and-compressed-logical-volume_deduplicating-and-compressing-logical-volumes) does not even mention it:

    lvcreate --type vdo --size 6g --virtualsize 10g --name vdo0 myvg

will create

```
# lvs
  LV     VG   Attr       LSize  Pool   Origin Data%  Meta%  Move Log Cpy%Sync Convert
  vdo0   myvg vwi-a-v--- 10.00g vpool0        0.00                                   
  vpool0 myvg dwi-------  6.00g               66.69                 
```
And then `vpool1` etc. for the next devices.

However, with UDisks this doesn't work:

```
# busctl call org.freedesktop.UDisks2 /org/freedesktop/UDisks2/lvm/myvg org.freedesktop.UDisks2.VolumeGroup CreateVDOVolume 'sstttbbsa{sv}' vdo0 '' 6000000000 10000000000 0 True True auto 0
Error creating volume: Process reported exit code 3:   Logical volume name "" is invalid.
  Run `lvcreate --help' for more information.
```

Can you please fix this to not specify `--vdopool ''` in this case, but just drop the option altogether? Then this would use the same auto-naming behaviour.

I don't want to make the user have to specify a pool name in cockpit, so for now I'll just supply it as *volname*`_vdopool`, but that is prone to name collisions or names getting too long.

**Comment by tbzatek** [comment]
Just a minor docs update and we should be all set, right?
