### ISSUE TITLE
when plug out the USB flash the udisks still show the device and cannot remove it

### ISSUE THREAD

**Issue by Sl0v3C** [storaged-project/udisks#943]
Issue:  when plug out the USB flash disk, then udisks still show the device and cannot eject or close it.
![image](https://user-images.githubusercontent.com/18479215/145214870-a92c6148-f0a0-4dab-9a4c-ab217d1c3768.png)
![image](https://user-images.githubusercontent.com/18479215/145214980-9417ff4d-a321-4f49-9d10-774d11139265.png)
version: 磁盘实用程序 3.36.3    UDisks 2.8.4（基于 2.8.4 编译）

**Comment by tbzatek** [comment]
Uhm, could you please provide translation of the first error? The message from `eject` might be important here.

Also, when you forcefully plug out a removable device that is still mounted, bad things will happen. You'll most likely get a ton of errors from the kernel filesystem driver and after some time the device might disappear from the system or stay forever.

**Comment by tbzatek** [comment]
Closing for the time being as no answer was provided.
