### ISSUE TITLE
How i can remove this from ubuntu 20.04

### ISSUE THREAD

**Issue by Ntemis** [storaged-project/udisks#957]
I have this log in my dmesg
[    9.795910] loop10: detected capacity change from 0 to 8
After i did #udisksctl info -b /dev/loop10
```/org/freedesktop/UDisks2/block_devices/loop10:
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/loop10
    DeviceNumber:               1802
    Drive:                      '/'
    HintAuto:                   false
    HintIconName:               
    HintIgnore:                 false
    HintName:                   
    HintPartitionable:          true
    HintSymbolicIconName:       
    HintSystem:                 true
    Id:                         
    IdLabel:                    
    IdType:                     
    IdUUID:                     
    IdUsage:                    
    IdVersion:                  
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/loop10
    ReadOnly:                   false
    Size:                       0
    Symlinks:                   
    UserspaceMountOptions:      
  org.freedesktop.UDisks2.Loop:
    Autoclear:          false
    BackingFile:        
    SetupByUID:         0

I want this gone if possible

**Comment by vojtechtrefny** [comment]
Remove what? [Loop devices](https://en.wikipedia.org/wiki/Loop_device) are used by snaps in Ubuntu and it's normal that unused loop device left after detaching the associated backing file is left in the system with size 0. Most userspace tools like `lsblk` don't display these by default but they still exist in the system (`lsblk -a` will show them). UDisks keeps track of all block devices so we keep information about loop devices too, this one just happens to have no backing file attached and size 0.

**Comment by Ntemis** [comment]
So is safe to assume there is no way to stop /dev/loop10 from being used by the operating system?

**Comment by tbzatek** [comment]
The original message about capacity change you posted is unrelated to UDisks. Or are you trying to say that the capacity has changed to `8` only after you called `udisksctl info`?

**Comment by Ntemis** [comment]
That's a negative. All am trying to say is i saw the log in dmesg and tried to investigate further because it causes micro audio cut outs while playing blue-ray movies (x265/4k/etc). Audio randomly stops and then returns after X milliseconds

**Comment by tbzatek** [comment]
That's sad however unrelated to UDisks. Please open an issue at your distribution first.
