### ISSUE TITLE
udisks_mount_get_mount_path: assertion 'mount->type == UDISKS_MOUNT_TYPE_FILESYSTEM' failed

### ISSUE THREAD

**Issue by Roki100** [storaged-project/udisks#970]
hello! i am getting spammed by `udisks_mount_get_mount_path: assertion 'mount->type == UDISKS_MOUNT_TYPE_FILESYSTEM' failed` when running docker, killing udisksd solves the problem, is there any fix for this error?
im running raspberry pi os 64bit (arm64)
this seems to be udisks issue rather than docker issue as i get this issue only on my pi, and i am pretty sure it didnt happen back in 2020

**Comment by Roki100** [comment]
2.9.2, apt output: `udisks2/stable,now 2.9.2-2+deb11u1 arm64 [installed]`
i have no idea if its an old version, but if it is, how can i update it?

**Comment by tbzatek** [comment]
I have no idea, please consult the guidebook of your distribution. Alternatively, you may open a bugreport in your distribution issue tracker asking for package update.

Anyway, closing this ticket for now, feel free to reopen should the issue persist on udisks-2.9.4 or newer.
