### ISSUE TITLE
block do not have a filesystem interface but `udisks_filesystem_proxy_new_sync` function returns a valid object.

### ISSUE THREAD

**Issue by itsXuSt** [storaged-project/udisks#972]
is that designed so? 
when will the function returns nullptr? 
udisks version: `2.9.2`
![image](https://user-images.githubusercontent.com/50353838/163346092-bdc22dce-9f4d-4044-9dc0-957aece0fa00.png)

while get filesystem by UDisksObject, nullptr is returned.
![image](https://user-images.githubusercontent.com/50353838/163347517-e1f04edd-8c02-4eab-b8a7-496eb0271f3b.png)

**Comment by itsXuSt** [comment]
![image](https://user-images.githubusercontent.com/50353838/163359367-5fdd131e-5106-4d0d-bdd9-196878c57ae2.png)
and seems like #930 is not fixed in vesion 2.9.3

**Comment by itsXuSt** [comment]
@tbzatek

**Comment by tbzatek** [comment]
Could you please post `udisksctl dump`? Do you get these errors in a fully settled state?

**Comment by tbzatek** [comment]
Closing for the time being as no answer was provided.
