### ISSUE TITLE
Flooding udev change events for /dev/sdb cause high CPU load.

### ISSUE THREAD

**Issue by navid-zamani** [storaged-project/udisks#987]
When the system starts, udisks2 causes an infinite repetition of these events:

```
KERNEL[1832.422273] change   /devices/pci0000:00/0000:00:01.2/0000:15:00.1/ata2/host1/target1:0:0/1:0:0:0/block/sdb/sdb1 (block)
KERNEL[1832.628578] change   /devices/pci0000:00/0000:00:01.2/0000:15:00.1/ata2/host1/target1:0:0/1:0:0:0/block/sdb/sdb2 (block)
UDEV  [1832.643786] change   /devices/pci0000:00/0000:00:01.2/0000:15:00.1/ata2/host1/target1:0:0/1:0:0:0/block/sdb/sdb1 (block)
UDEV  [1832.732081] change   /devices/pci0000:00/0000:00:01.2/0000:15:00.1/ata2/host1/target1:0:0/1:0:0:0/block/sdb/sdb2 (block)
```

This causes a high CPU load.

Only stopping and masking the udisks2 daemon/service prevents this from coming back after the next trigger.

### Dumps and Logs
Here is all the requested data:

udisks2: 2.9.4-1ubuntu2
gvfs: 1.48.2-0ubuntu1
libatasmart4: 0.19-5build2
[/etc/fstab](https://github.com/storaged-project/udisks/files/9136978/fstab.txt)
[/proc/self/mountinfo](https://github.com/storaged-project/udisks/files/9136979/mountinfo.txt)
[skdump --save=skdump-output.sda /dev/sda](https://github.com/storaged-project/udisks/files/9136980/skdump-output.sda.txt)
[skdump --save=skdump-output.sdb /dev/sdb](https://github.com/storaged-project/udisks/files/9136981/skdump-output.sdb.txt)
[skdump /dev/sda](https://github.com/storaged-project/udisks/files/9136982/skdump.sda.txt)
[skdump /dev/sdb](https://github.com/storaged-project/udisks/files/9136983/skdump.sdb.txt)
[udevadm info --export-db](https://github.com/storaged-project/udisks/files/9136984/udevadm.info.--export-db.txt)
[udevadmin monitor](https://github.com/storaged-project/udisks/files/9136985/udevadmin.monitor.log)
[udevadmin monitor --udev --property](https://github.com/storaged-project/udisks/files/9136986/udevadmin.monitor.--udev.--property.log)
[udisksctl dump](https://github.com/storaged-project/udisks/files/9136987/udisksctl.dump.txt)
[udisksctl monitor](https://github.com/storaged-project/udisks/files/9136988/udisksctl.monitor.log)

**Comment by navid-zamani** [comment]
Duplicate of bug #946.

**Comment by tbzatek** [comment]
Closing as duplicate then.
