### ISSUE TITLE
Udisks not reading the configuration

### ISSUE THREAD

**Issue by ThePeach** [storaged-project/udisks#989]
Hello, I'm going around in loops to get something working on my Arch machine, and I seem to have pinpointed the problem at Udisks not reading the configuration.

Since I installed Arch on this machine, I can't get write permissions for my user on the external NTFS USB disk I have. 

I'm currently running udisks 2.9.4-1 with kernel 5.18.12-arch1-1.

As [suggested in the Arch wiki](https://wiki.archlinux.org/title/NTFS#Troubleshooting), I tried to apply some changes (by adding `noatime` and `prealloc`) in the configuration, but nothing changed.

```
$ grep -e ^[^#] /etc/udisks2/mount_options.conf
[defaults]
ntfs_defaults=uid=$UID,gid=$GID,noatime,prealloc
ntfs_allow=uid=$UID,gid=$GID,umask,dmask,fmask,locale,norecover,ignore_case,windows_names,compression,nocompression,big_writes,noatime,prealloc
$ sudo systemctl restart udisks2
$ udisksctl mount -b /dev/sda1
Mounted /dev/sda1 at /run/media/peach/Rugged Mini
$ mount | grep sda1
/dev/sda1 on /run/media/peach/Rugged Mini type ntfs3 (rw,nosuid,nodev,relatime,uid=0,gid=0,iocharset=utf8,uhelper=udisks2)
```

I can't see the `noatime`/`prealloc` option applied.  I'm also expecting my current user to be the owner of the files in the FS, which is not the case. I even tried to use the `noacsrules` option as a last resort, but the FS kept having the same mask on all files/dirs (i.e. not writable by the group/others). 

Am I missing something glaring?

**Comment by tbzatek** [comment]
The `ntfs3` story is being worked on in #985. For the current UDisks releases `ntfs-3g` is recommended instead. The linked Arch wiki page is ambiguous in many ways, suggesting changes to the system that would break things even in the future.

Please revert any changes done to the system, install `ntfs-3g` and retest. If `ntfs3` goes in the way, you can blacklist the module.

**Comment by tbzatek** [comment]
FYI, tested your scenario manually, with #985 I'm getting proper ownerships (`udiskctl mount` called as user):
```
/dev/loop0 on /media/tbzatek/2E1D50EF4874E7201 type ntfs3 (rw,nosuid,nodev,noatime,uid=1000,gid=1000,iocharset=utf8,prealloc,uhelper=udisks2)
```

```
$ ls -al /media/tbzatek/2E1D50EF4874E7201
total 4
drwxrwxrwx. 1 tbzatek tbzatek 4096 Jul 26 14:19 .
drwxr-x---+ 1 root    root      66 Jul 26 14:20 ..
-rw-r--r--. 1 tbzatek tbzatek    0 Jul 26 14:19 test
drwxr-xr-x. 1 tbzatek tbzatek    0 Jul 26 14:19 test2
```

**Comment by ThePeach** [comment]
Hi, @tbzatek thanks a lot for the suggestions and the help. As you pointed out, Arch messes up stuff. I found out the package `ntfsprogs-ntfs3` provides the Udev rule that the archwiki suggests against. Removing that makes the configuration shared work as expected. Sorry for the confusion.

**Comment by tbzatek** [comment]
No worries, there are things messed up on various places out in the wild. Hopefully the UDisks 2.10.0 release would be resilient against such things. The release is still a couple of months away...
