### ISSUE TITLE
Authentication Required PolicyKit1 KDE Agent

### ISSUE THREAD

**Issue by DimitriBolt** [storaged-project/udisks#992]
Authentication is required to check power state for HDD
Action: Check power state

Sensor error
Error reading power management state for sensor udisks2/CT1000BX500SSD1_2018E29FD00EGDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorized: Not authorized to perform operation 
Error reading power management state for sensor udisks2/APPLE_HDD_HTS545050A7E362_TNS5193TJ0GZSHGDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorized: Not authorized to perform operation 

The question is: How (what file) do I have to fix the PolicyKid1-file?

**Comment by tbzatek** [comment]
https://github.com/storaged-project/udisks/blob/da8a7d0dfd586d1b50c87f2345f856cffa57d9fe/data/org.freedesktop.UDisks2.policy.in#L465-L474

**Comment by tbzatek** [comment]
@DimitriBolt, did it help to solve your issue? Any further questions?
